d /var/lib/backendai 0755 root root -
d /var/lib/backendai/postgresql 0700 postgres postgres -
d /var/lib/backendai/etcd 0700 etcd etcd -
d /var/lib/backendai/valkey 0700 valkey valkey -
d /var/lib/backendai/manager 0750 backendai backendai -
d /var/lib/backendai/coordinator 0750 backendai backendai -
d /var/lib/backendai/backup 0700 backendai backendai -
