apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bai-webserver.fullname" . }}-secrets
  labels:
    {{- include "bai-webserver.labels" . | nindent 4 }}
type: Opaque
stringData:
  session-secret: {{ .Values.webserver.sessionSecret | quote }}
  redis-password: {{ default "local-dev-redis" .Values.webserver.redisPassword | quote }}
