"""RBAC GQL types package."""

from .entity import (
    EntityConnection,
    EntityEdge,
    EntityFilter,
    EntityOrderBy,
    EntityOrderField,
    EntityRefGQL,
)
from .entity_node import EntityNode
from .permission import (
    BulkAddRolePermissionFailureInfoGQL,
    BulkAddRolePermissionsInputGQL,
    BulkAddRolePermissionsPayloadGQL,
    BulkRemoveRolePermissionFailureInfoGQL,
    BulkRemoveRolePermissionsInputGQL,
    BulkRemoveRolePermissionsPayloadGQL,
    CreatePermissionInput,
    DeletePermissionInput,
    DeletePermissionPayload,
    EntityActionInfoGQL,
    EntityOperationCombinationGQL,
    OperationInfoGQL,
    OperationTypeFilterGQL,
    OperationTypeGQL,
    PermissionConnection,
    PermissionEdge,
    PermissionFilter,
    PermissionGQL,
    PermissionNestedFilterGQL,
    PermissionOrderBy,
    PermissionOrderField,
    ReplaceRolePermissionFailureInfoGQL,
    ReplaceRolePermissionsInputGQL,
    ReplaceRolePermissionsPayloadGQL,
    ScopeEntityCombinationGQL,
    ScopeEntityOperationCombinationGQL,
    UpdatePermissionInput,
)
from .role import (
    AssignRoleInput,
    BulkAssignRoleErrorGQL,
    BulkAssignRoleInputGQL,
    BulkAssignRolePayloadGQL,
    BulkRevokeRoleErrorGQL,
    BulkRevokeRoleInputGQL,
    BulkRevokeRolePayloadGQL,
    CreateRoleInput,
    DeleteRoleInput,
    DeleteRolePayload,
    PurgeRoleInput,
    PurgeRolePayload,
    RevokeRoleInput,
    RoleAssignmentConnection,
    RoleAssignmentEdge,
    RoleAssignmentFilter,
    RoleAssignmentGQL,
    RoleAssignmentOrderBy,
    RoleAssignmentOrderField,
    RoleAssignmentRoleNestedFilterGQL,
    RoleConnection,
    RoleEdge,
    RoleFilter,
    RoleGQL,
    RoleOrderBy,
    RoleOrderField,
    RoleSourceFilterGQL,
    RoleSourceGQL,
    RoleStatusFilterGQL,
    RoleStatusGQL,
    RoleUserNestedFilterGQL,
    UpdateRoleInput,
)
from .role_invitation import (
    AcceptRoleInvitationInputGQL,
    CancelRoleInvitationInputGQL,
    CreateRoleInvitationInputGQL,
    CreateRoleInvitationPayload,
    RejectRoleInvitationInputGQL,
    RoleInvitationConnection,
    RoleInvitationEdge,
    RoleInvitationFilterGQL,
    RoleInvitationGQL,
    RoleInvitationOrderByGQL,
    RoleInvitationOrderFieldGQL,
    RoleInvitationRoleNestedFilterGQL,
    RoleInvitationStateFilterGQL,
    RoleInvitationStateGQL,
    RoleInvitationUserNestedFilterGQL,
)
from .scope import RBACElementTypeFilterGQL, RBACElementTypeGQL, ScopeInputGQL

__all__ = [
    # Permission enums
    "RBACElementTypeGQL",
    "RBACElementTypeFilterGQL",
    "OperationTypeGQL",
    "OperationTypeFilterGQL",
    "PermissionOrderField",
    # Role enums
    "RoleSourceGQL",
    "RoleStatusGQL",
    # Role filter wrappers
    "RoleSourceFilterGQL",
    "RoleStatusFilterGQL",
    "RoleOrderField",
    "RoleAssignmentOrderField",
    # Entity enums
    "EntityOrderField",
    # Types
    "PermissionGQL",
    "RoleGQL",
    "RoleAssignmentGQL",
    "EntityRefGQL",
    # Filters
    "PermissionFilter",
    "RoleFilter",
    "RoleAssignmentFilter",
    "RoleAssignmentRoleNestedFilterGQL",
    "RoleUserNestedFilterGQL",
    "PermissionNestedFilterGQL",
    "EntityFilter",
    # OrderBy
    "PermissionOrderBy",
    "RoleOrderBy",
    "RoleAssignmentOrderBy",
    "EntityOrderBy",
    # Inputs
    "CreatePermissionInput",
    "UpdatePermissionInput",
    "DeletePermissionInput",
    "CreateRoleInput",
    "UpdateRoleInput",
    "DeleteRoleInput",
    "PurgeRoleInput",
    "AssignRoleInput",
    "RevokeRoleInput",
    "BulkAssignRoleInputGQL",
    "BulkRevokeRoleInputGQL",
    "BulkAddRolePermissionsInputGQL",
    "BulkRemoveRolePermissionsInputGQL",
    "ReplaceRolePermissionsInputGQL",
    # Payloads
    "DeletePermissionPayload",
    "DeleteRolePayload",
    "PurgeRolePayload",
    "BulkAssignRoleErrorGQL",
    "BulkAssignRolePayloadGQL",
    "BulkRevokeRoleErrorGQL",
    "BulkRevokeRolePayloadGQL",
    "BulkAddRolePermissionFailureInfoGQL",
    "BulkAddRolePermissionsPayloadGQL",
    "BulkRemoveRolePermissionFailureInfoGQL",
    "BulkRemoveRolePermissionsPayloadGQL",
    "ReplaceRolePermissionFailureInfoGQL",
    "ReplaceRolePermissionsPayloadGQL",
    # Connections
    "PermissionConnection",
    "PermissionEdge",
    "RoleConnection",
    "RoleEdge",
    "RoleAssignmentConnection",
    "RoleAssignmentEdge",
    # Entity types
    "EntityNode",
    "EntityEdge",
    "EntityConnection",
    # Role invitation types
    "RoleInvitationStateGQL",
    "RoleInvitationGQL",
    "RoleInvitationConnection",
    "RoleInvitationEdge",
    "RoleInvitationOrderFieldGQL",
    "RoleInvitationOrderByGQL",
    "RoleInvitationFilterGQL",
    "RoleInvitationStateFilterGQL",
    "RoleInvitationRoleNestedFilterGQL",
    "RoleInvitationUserNestedFilterGQL",
    "CreateRoleInvitationInputGQL",
    "AcceptRoleInvitationInputGQL",
    "RejectRoleInvitationInputGQL",
    "CancelRoleInvitationInputGQL",
    "CreateRoleInvitationPayload",
    # Scope types
    "ScopeInputGQL",
    # Scope-entity combination
    "ScopeEntityCombinationGQL",
    # Entity-operation combination
    "EntityOperationCombinationGQL",
    "OperationInfoGQL",
    # Scope-entity-operation combination (permission matrix)
    "EntityActionInfoGQL",
    "ScopeEntityOperationCombinationGQL",
]
