"""RBAC GQL types package."""

from .entity_node import EntityNodeGQL
from .permission import (
    BulkAddRolePermissionFailureInfoGQL,
    BulkAddRolePermissionsInputGQL,
    BulkAddRolePermissionsPayloadGQL,
    BulkRemoveRolePermissionFailureInfoGQL,
    BulkRemoveRolePermissionsInputGQL,
    BulkRemoveRolePermissionsPayloadGQL,
    CreatePermissionInput,
    DeletePermissionInput,
    DeletePermissionPayload,
    EntityActionInfoGQL,
    EntityOperationCombinationGQL,
    OperationInfoGQL,
    OperationTypeFilterGQL,
    OperationTypeGQL,
    PermissionBitFilterGQL,
    PermissionConnection,
    PermissionEdge,
    PermissionFilter,
    PermissionGQL,
    PermissionNestedFilterGQL,
    PermissionOrderBy,
    PermissionOrderField,
    ReplaceRolePermissionFailureInfoGQL,
    ReplaceRolePermissionsInputGQL,
    ReplaceRolePermissionsPayloadGQL,
    ScopeEntityCombinationGQL,
    ScopeEntityOperationCombinationGQL,
    UpdatePermissionInput,
)
from .role import (
    AssignRoleInput,
    BulkAssignRoleErrorGQL,
    BulkAssignRoleInputGQL,
    BulkAssignRolePayloadGQL,
    BulkRevokeRoleErrorGQL,
    BulkRevokeRoleInputGQL,
    BulkRevokeRolePayloadGQL,
    CreateRoleInput,
    DeleteRoleInput,
    DeleteRolePayload,
    PurgeRoleInput,
    PurgeRolePayload,
    RevokeRoleInput,
    RoleAssignmentConnection,
    RoleAssignmentEdge,
    RoleAssignmentFilter,
    RoleAssignmentGQL,
    RoleAssignmentOrderBy,
    RoleAssignmentOrderField,
    RoleAssignmentRoleNestedFilterGQL,
    RoleConnection,
    RoleEdge,
    RoleFilter,
    RoleGQL,
    RoleOrderBy,
    RoleOrderField,
    RoleSourceFilterGQL,
    RoleSourceGQL,
    RoleStatusFilterGQL,
    RoleStatusGQL,
    RoleUserNestedFilterGQL,
    UpdateRoleInput,
)
from .scope import PermissionBitGQL, ScopeInputGQL

__all__ = [
    # Permission enums
    "OperationTypeGQL",
    "OperationTypeFilterGQL",
    "PermissionBitGQL",
    "PermissionBitFilterGQL",
    "PermissionOrderField",
    # Role enums
    "RoleSourceGQL",
    "RoleStatusGQL",
    # Role filter wrappers
    "RoleSourceFilterGQL",
    "RoleStatusFilterGQL",
    "RoleOrderField",
    "RoleAssignmentOrderField",
    # Entity enums
    # Types
    "PermissionGQL",
    "RoleGQL",
    "RoleAssignmentGQL",
    # Filters
    "PermissionFilter",
    "RoleFilter",
    "RoleAssignmentFilter",
    "RoleAssignmentRoleNestedFilterGQL",
    "RoleUserNestedFilterGQL",
    "PermissionNestedFilterGQL",
    # OrderBy
    "PermissionOrderBy",
    "RoleOrderBy",
    "RoleAssignmentOrderBy",
    # Inputs
    "CreatePermissionInput",
    "UpdatePermissionInput",
    "DeletePermissionInput",
    "CreateRoleInput",
    "UpdateRoleInput",
    "DeleteRoleInput",
    "PurgeRoleInput",
    "AssignRoleInput",
    "RevokeRoleInput",
    "BulkAssignRoleInputGQL",
    "BulkRevokeRoleInputGQL",
    "BulkAddRolePermissionsInputGQL",
    "BulkRemoveRolePermissionsInputGQL",
    "ReplaceRolePermissionsInputGQL",
    # Payloads
    "DeletePermissionPayload",
    "DeleteRolePayload",
    "PurgeRolePayload",
    "BulkAssignRoleErrorGQL",
    "BulkAssignRolePayloadGQL",
    "BulkRevokeRoleErrorGQL",
    "BulkRevokeRolePayloadGQL",
    "BulkAddRolePermissionFailureInfoGQL",
    "BulkAddRolePermissionsPayloadGQL",
    "BulkRemoveRolePermissionFailureInfoGQL",
    "BulkRemoveRolePermissionsPayloadGQL",
    "ReplaceRolePermissionFailureInfoGQL",
    "ReplaceRolePermissionsPayloadGQL",
    # Connections
    "PermissionConnection",
    "PermissionEdge",
    "RoleConnection",
    "RoleEdge",
    "RoleAssignmentConnection",
    "RoleAssignmentEdge",
    # Entity types
    # Scope types
    "ScopeInputGQL",
    # Scope-entity combination
    "ScopeEntityCombinationGQL",
    # Entity-operation combination
    "EntityNodeGQL",
    "EntityOperationCombinationGQL",
    "OperationInfoGQL",
    # Scope-entity-operation combination (permission matrix)
    "EntityActionInfoGQL",
    "ScopeEntityOperationCombinationGQL",
]
