"""
Common DTOs for deployment system used by both Client SDK and Manager.
"""

from __future__ import annotations

from .request import (
    DeploymentFilter,
    DeploymentPathParam,
    RevisionFilter,
    RevisionPathParam,
    RouteFilter,
    RoutePathParam,
    SearchDeploymentsRequest,
    SearchRevisionsRequest,
    SearchRoutesRequest,
    UpdateDeploymentRequest,
    UpdateRouteTrafficStatusRequest,
)
from .response import (
    ActivateRevisionResponse,
    ClusterConfigDTO,
    CursorPaginationInfo,
    DeactivateRevisionResponse,
    DeploymentDTO,
    DestroyDeploymentResponse,
    GetDeploymentResponse,
    GetRevisionResponse,
    ListDeploymentsResponse,
    ListRevisionsResponse,
    ListRoutesResponse,
    ModelMountConfigDTO,
    ModelRuntimeConfigDTO,
    NetworkConfigDTO,
    PaginationInfo,
    ReplicaStateDTO,
    ResourceConfigDTO,
    RevisionDTO,
    RouteDTO,
    UpdateDeploymentResponse,
    UpdateRouteTrafficStatusResponse,
)
from .types import (
    DeploymentOrder,
    DeploymentOrderField,
    OrderDirection,
    RevisionOrder,
    RevisionOrderField,
    RouteOrder,
    RouteOrderField,
)

__all__ = (
    # Types
    "OrderDirection",
    "DeploymentOrderField",
    "RevisionOrderField",
    "RouteOrderField",
    "DeploymentOrder",
    "RevisionOrder",
    "RouteOrder",
    # Request DTOs
    "DeploymentFilter",
    "RevisionFilter",
    "RouteFilter",
    "SearchDeploymentsRequest",
    "SearchRevisionsRequest",
    "SearchRoutesRequest",
    "UpdateDeploymentRequest",
    "UpdateRouteTrafficStatusRequest",
    "DeploymentPathParam",
    "RevisionPathParam",
    "RoutePathParam",
    # Response DTOs
    "DeploymentDTO",
    "RevisionDTO",
    "RouteDTO",
    "NetworkConfigDTO",
    "ClusterConfigDTO",
    "ResourceConfigDTO",
    "ModelRuntimeConfigDTO",
    "ModelMountConfigDTO",
    "ReplicaStateDTO",
    "GetDeploymentResponse",
    "ListDeploymentsResponse",
    "UpdateDeploymentResponse",
    "DestroyDeploymentResponse",
    "GetRevisionResponse",
    "ListRevisionsResponse",
    "ActivateRevisionResponse",
    "DeactivateRevisionResponse",
    "ListRoutesResponse",
    "UpdateRouteTrafficStatusResponse",
    "PaginationInfo",
    "CursorPaginationInfo",
)
