"""
Common DTOs for deployment system used by both Client SDK and Manager.
"""

from __future__ import annotations

from .request import (
    AddRevisionRequest,
    BlueGreenConfigInput,
    ClusterConfigInput,
    CreateDeploymentRequest,
    DeploymentFilter,
    DeploymentMetadataInput,
    DeploymentPathParam,
    DeploymentPolicyPathParam,
    DeploymentStrategyInput,
    ExtraVFolderMountInput,
    ImageInput,
    ModelMountConfigInput,
    ModelRuntimeConfigInput,
    NetworkAccessInput,
    ResourceConfigInput,
    RevisionFilter,
    RevisionInput,
    RevisionPathParam,
    RollingUpdateConfigInput,
    RouteFilter,
    RoutePathParam,
    SearchDeploymentPoliciesRequest,
    SearchDeploymentsRequest,
    SearchRevisionsRequest,
    SearchRoutesRequest,
    UpdateDeploymentRequest,
    UpdateRouteTrafficStatusRequest,
    UpsertDeploymentPolicyRequest,
)
from .response import (
    ActivateRevisionResponse,
    AddRevisionResponse,
    ClusterConfigDTO,
    CreateDeploymentResponse,
    CursorPaginationInfo,
    DeactivateRevisionResponse,
    DeploymentDTO,
    DeploymentPolicyDTO,
    DestroyDeploymentResponse,
    GetDeploymentPolicyResponse,
    GetDeploymentResponse,
    GetModelDefinitionResponse,
    GetRevisionResponse,
    ListDeploymentPoliciesResponse,
    ListDeploymentsResponse,
    ListRevisionsResponse,
    ListRoutesResponse,
    ModelConfigDTO,
    ModelDefinitionDTO,
    ModelHealthCheckDTO,
    ModelMetadataDTO,
    ModelMountConfigDTO,
    ModelRuntimeConfigDTO,
    ModelServiceConfigDTO,
    NetworkConfigDTO,
    PaginationInfo,
    PreStartActionDTO,
    ReplicaStateDTO,
    ResourceConfigDTO,
    RevisionDTO,
    RouteDTO,
    UpdateDeploymentResponse,
    UpdateRouteTrafficStatusResponse,
    UpsertDeploymentPolicyResponse,
)
from .types import (
    DeploymentOrder,
    DeploymentOrderField,
    OrderDirection,
    RevisionOrder,
    RevisionOrderField,
    RouteOrder,
    RouteOrderField,
)

__all__ = (
    # Types
    "OrderDirection",
    "DeploymentOrderField",
    "RevisionOrderField",
    "RouteOrderField",
    "DeploymentOrder",
    "RevisionOrder",
    "RouteOrder",
    # Request DTOs - Filters
    "DeploymentFilter",
    "RevisionFilter",
    "RouteFilter",
    # Request DTOs - Path params
    "DeploymentPathParam",
    "DeploymentPolicyPathParam",
    "RevisionPathParam",
    "RoutePathParam",
    # Request DTOs - Search/List
    "SearchDeploymentPoliciesRequest",
    "SearchDeploymentsRequest",
    "SearchRevisionsRequest",
    "SearchRoutesRequest",
    # Request DTOs - Create inputs
    "RollingUpdateConfigInput",
    "BlueGreenConfigInput",
    "DeploymentMetadataInput",
    "NetworkAccessInput",
    "DeploymentStrategyInput",
    "ImageInput",
    "ClusterConfigInput",
    "ResourceConfigInput",
    "ModelMountConfigInput",
    "ModelRuntimeConfigInput",
    "ExtraVFolderMountInput",
    "RevisionInput",
    # Request DTOs - Create/Update requests
    "CreateDeploymentRequest",
    "UpsertDeploymentPolicyRequest",
    "AddRevisionRequest",
    "UpdateDeploymentRequest",
    "UpdateRouteTrafficStatusRequest",
    # Response DTOs - Data
    "DeploymentDTO",
    "DeploymentPolicyDTO",
    "RevisionDTO",
    "RouteDTO",
    "NetworkConfigDTO",
    "ClusterConfigDTO",
    "ResourceConfigDTO",
    "ModelRuntimeConfigDTO",
    "ModelMountConfigDTO",
    "ReplicaStateDTO",
    "PreStartActionDTO",
    "ModelHealthCheckDTO",
    "ModelServiceConfigDTO",
    "ModelMetadataDTO",
    "ModelConfigDTO",
    "ModelDefinitionDTO",
    # Response DTOs - Create responses
    "CreateDeploymentResponse",
    "UpsertDeploymentPolicyResponse",
    # Response DTOs - Get/List responses
    "GetDeploymentResponse",
    "GetDeploymentPolicyResponse",
    "GetModelDefinitionResponse",
    "ListDeploymentPoliciesResponse",
    "ListDeploymentsResponse",
    "UpdateDeploymentResponse",
    "DestroyDeploymentResponse",
    "GetRevisionResponse",
    "AddRevisionResponse",
    "ListRevisionsResponse",
    "ActivateRevisionResponse",
    "DeactivateRevisionResponse",
    "ListRoutesResponse",
    "UpdateRouteTrafficStatusResponse",
    # Response DTOs - Pagination
    "PaginationInfo",
    "CursorPaginationInfo",
)
