#! /bin/sh
set -eu

export LD_LIBRARY_PATH="/opt/backend.ai/lib:${LD_LIBRARY_PATH:-}"

/opt/backend.ai/bin/python -s /opt/kernel/bai_cc_bootstrap.py

while IFS='=' read -r key value; do
  [ -n "$key" ] || continue
  export "$key=$value"
done < /home/config/environ.txt

/opt/backend.ai/bin/python -s /opt/kernel/bai-guest-storage

exec /opt/kernel/entrypoint.sh "$@"
