apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bai-appproxy-worker.fullname" . }}-secrets
  labels:
    {{- include "bai-appproxy-worker.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ default "local-dev-redis" .Values.worker.redisPassword | quote }}
  jwt-secret: {{ .Values.worker.jwtSecret | quote }}
  api-token: {{ .Values.worker.apiToken | quote }}
