apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bai-appproxy-coordinator.fullname" . }}-secrets
  labels:
    {{- include "bai-appproxy-coordinator.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.coordinator.jwtSecret | quote }}
  api-token: {{ .Values.coordinator.apiToken | quote }}
  postgres-password: {{ default "local-dev-postgres" .Values.coordinator.dbPassword | quote }}
  redis-password: {{ default "local-dev-redis" .Values.coordinator.redisPassword | quote }}
