apiVersion: v1
kind: Service
metadata:
  name: {{ include "bai-appproxy-coordinator.fullname" . }}
  labels:
    {{- include "bai-appproxy-coordinator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.coordinator.service.type }}
  selector:
    {{- include "bai-appproxy-coordinator.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.coordinator.service.apiPort }}
      targetPort: {{ .Values.coordinator.bindPort }}
      {{- if and (eq .Values.coordinator.service.type "NodePort") .Values.coordinator.service.nodePort }}
      nodePort: {{ .Values.coordinator.service.nodePort }}
      {{- end }}
      protocol: TCP
