apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bai-apollo-router.fullname" . }}-supergraph
  labels:
    {{- include "bai-apollo-router.labels" . | nindent 4 }}
data:
  supergraph.graphql: |-
{{ .Files.Get "files/supergraph.graphql" | indent 4 }}
