apiVersion: v1
kind: Service
metadata:
  name: {{ include "bai-apollo-router.fullname" . }}
  labels:
    {{- include "bai-apollo-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.router.service.type }}
  selector:
    {{- include "bai-apollo-router.selectorLabels" . | nindent 4 }}
  ports:
    - name: graphql
      port: {{ .Values.router.service.port }}
      targetPort: {{ .Values.router.bindPort }}
      protocol: TCP
