python_sources(
    name="src",
    dependencies=[
        ":resources",
    ],
)

resources(
    name="resources",
    sources=[
        "*.txt",
        "*.tar.gz",
        # "*.bin",  # no matching files yet
    ],
)
