# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      # Skip building the documentation if there are no changes in the docs/ directory
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml;
        then
          exit 183;
        fi
    pre_build:
      # Auto-generate REST API reference
      - PYTHONPATH="src" python -m ai.backend.manager.openapi -o docs/manager/rest-reference/openapi.json
python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

formats: all
