# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      # Skip building the documentation if there are no changes in the docs/ directory
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml;
        then
          exit 183;
        fi
    pre_build:
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" != "external" ];
        then
          mkdir docs/fonts
          curl -L https://github.com/orioncactus/pretendard/releases/download/v1.3.9/Pretendard-1.3.9.zip -o pretendard.zip
          unzip -o pretendard.zip -d docs/fonts/Pretendard
          curl -L https://github.com/naver/d2codingfont/releases/download/VER1.3.2/D2Coding-Ver1.3.2-20180524.zip -o d2coding.zip
          unzip -o d2coding.zip -d docs/fonts/D2Coding
        fi
python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

formats: all
