# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      # Skip the build if there is no docs label
      - '([ "${READTHEDOCS_VERSION_TYPE}" = "external" ] && curl -sL https://api.github.com/repos/lablup/backend.ai/issues/${READTHEDOCS_VERSION}/labels | jq -e '.[] | select(.name == "area:docs")') && echo "continue" || exit 183'
    pre_build:
      # Auto-generate REST API reference
      - PYTHONPATH="src" python -m ai.backend.manager.openapi docs/manager/rest-reference/openapi.json
python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

formats: all
