dist: xenial
language: python
cache: pip

stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix for test stage
python:
  - "3.8"
os:
  - linux
  # - osx  # not supported yet
install:
  - pip install -U pip setuptools
  - pip install -U -r requirements/test.txt
script:
  - python -m pytest tests

# other stages
jobs:
  fast_finish: true
  include:
    - stage: test
    - stage: deploy
      python: "3.8"
      install:
        - pip install -U pip setuptools
        - pip install -r requirements/build.txt
      script: skip
      deploy:
        on:
          tags: true
        provider: pypi
        distributions: sdist bdist_wheel
        user: __token__
        password:
          secure: ""
        skip_upload_docs: true
