python_requirements(
    name="reqs",
    source="requirements.txt",
    module_mapping={
        "aiodataloader-ng": ["aiodataloader"],
        "aiohttp-session": ["aiohttp_session"],
        "aiomonitor-ng": ["aiomonitor"],
        "attrs": ["attr", "attrs"],
        "boto3": ["botocore", "boto3"],
        "etcd-client-py": ["etcd_client"],
        "graphql-core": ["graphql"],
        "graphql-relay": ["graphql_relay"],
        "habana-pyhlml": ["pyhlml"],
        "more-itertools": ["more_itertools"],
        "pycryptodome": ["Crypto"],
        "pydantic": ["pydantic", "pydantic_core"],
        "pyhumps": ["humps"],
        "pyroscope-io": ["pyroscope"],
        "pytest-mock": ["pytest_mock"],
        "python-dateutil": ["dateutil", "dateutil.parser", "dateutil.tz"],
        "python-json-logger": ["pythonjsonlogger"],
        "PyYAML": ["yaml"],
        "pyzmq": ["zmq"],
        "ruamel.yaml": ["ruamel.yaml"],
        "tomli-w": ["tomli_w"],
        "tt-smi": ["tt_smi", "tt_tools"],
        "typing-extensions": ["typing_extensions"],
        "valkey-glide": ["glide"],
        "zipstream-new": ["zipstream"],
    },
    type_stubs_module_mapping={
        "types-aiofiles": ["aiofiles"],
        "types-cachetools": ["cachetools"],
        "types-Jinja2": ["jinja2"],
        "types-python-dateutil": ["dateutil", "dateutil.parser", "dateutil.tz"],
        "types-PyYAML": ["yaml"],
        "types-redis": ["redis"],
        "types-setuptools": [
            "setuptools",
            "pkg_resources",
            "pytest",
            "ai.backend.testutils",
            "ai.backend.test",
            "tests",
        ],
        "types-six": ["six", "graphql", "promise", "ai.backend.manager.models"],
        "types-tabulate": ["tabulate"],
    },
)
