python_requirements(
    name="reqs",
    source="requirements.txt",
    module_mapping={
        "aiodataloader-ng": ["aiodataloader"],
        "aiomonitor-ng": ["aiomonitor"],
        "attrs": ["attr", "attrs"],
        "aiohttp-session": ["aiohttp_session"],
        "pycryptodome": ["Crypto"],
        "python-dateutil": ["dateutil", "dateutil.parser", "dateutil.tz"],
        "python-json-logger": ["pythonjsonlogger"],
        "pyhumps": ["humps"],
        "pyzmq": ["zmq"],
        "PyYAML": ["yaml"],
        "typing-extensions": ["typing_extensions"],
        "more-itertools": ["more_itertools"],
        "zipstream-new": ["zipstream"],
        "etcd-client-py": ["etcd_client"],
    },
    type_stubs_module_mapping={
        "types-aiofiles": ["aiofiles"],
        "types-cachetools": ["cachetools"],
        "types-Jinja2": ["jinja2"],
        "types-PyYAML": ["yaml"],
        "types-python-dateutil": ["dateutil", "dateutil.parser", "dateutil.tz"],
        "types-redis": ["redis"],
        "types-setuptools": [
            "setuptools",
            "pkg_resources",
            "pytest",
            "ai.backend.testutils",
            "ai.backend.test",
            "tests",
        ],
        "types-six": ["six", "graphql", "promise", "ai.backend.manager.models"],
        "types-tabulate": ["tabulate"],
    },
)
