version: "2.4"

services:

  backendai-half-db:
    image: postgres:13.4-alpine
    restart: unless-stopped
    command: postgres -c 'max_connections=256'
    networks:
      - half
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=DB_PASSWORD
      - POSTGRES_DB=backend
    volumes:
      - "./data/postgres:/var/lib/postgresql/data:rw"
    cpu_count: 4
    mem_limit: "2g"

  backendai-half-redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    networks:
      - half
    ports:
      - "6379:6379"
    command: redis-server --requirepass REDIS_PASSWORD
    cpu_count: 1
    mem_limit: "2g"

  backendai-half-etcd:
    image: quay.io/coreos/etcd:v3.5.1
    restart: unless-stopped
    volumes:
      - "./data/etcd:/etcd-data:rw"
    networks:
      - half
    ports:
      - "2379:2379"
    command: >
      /usr/local/bin/etcd
      --name backendai-etcd
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --initial-cluster backendai-etcd=http://0.0.0.0:2380
      --initial-cluster-token backendai-etcd-token
      --initial-cluster-state new
      --auto-compaction-retention 1
    cpu_count: 1
    mem_limit: "1g"

networks:
  half:
