version: "2.4"

services:

  backendai-half-db:
    image: postgres:12.3-alpine
    restart: unless-stopped
    command: postgres -c 'max_connections=256'
    networks:
      - half
    ports:
      - "8100:5432"
    environment:
      - POSTGRES_PASSWORD=develove
      - POSTGRES_DB=backend
    volumes:
      - "./tmp/backend.ai-halfstack/${DATADIR_PREFIX:-.}/postgres-data:/var/lib/postgresql/data:rw"

  backendai-half-redis:
    image: redis:6.0.6-alpine
    restart: unless-stopped
    networks:
      - half
    ports:
      - "8110:6379"

  backendai-half-etcd:
    image: quay.io/coreos/etcd:v3.4.10
    restart: unless-stopped
    volumes:
      - "./tmp/backend.ai-halfstack/${DATADIR_PREFIX:-.}/etcd-data:/etcd-data:rw"
    networks:
      - half
    ports:
      - "8120:2379"
    command: >
      /usr/local/bin/etcd
      --name backendai-etcd
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --initial-cluster backendai-etcd=http://0.0.0.0:2380
      --initial-cluster-token backendai-etcd-token
      --initial-cluster-state new
      --enable-v2=true
      --auto-compaction-retention 1

networks:
  half:
