[context.keypair_endpoint]
endpoint = "http://127.0.0.1:8091"

[context.login_endpoint]
endpoint = "http://127.0.0.1:8090"

[context.keypair]
access-key = "AKIAIOSFODNN7EXAMPLE"
secret-key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

[context.login-credential]
user-id = "admin@lablup.com"
password = "wJalrXUt"
