python_tests(
    name="tests",
    dependencies=[
        "//src/ai/backend/manager/services/model_serving:src",
    ],
)

python_test_utils(
    sources=[
        "conftest.py",
        "fixtures.py",
    ]
)
