FROM quay.io/coreos/etcd:v3.4.22

# Add user with UID/GID {{ bai_user_id }}/{{ bai_user_group_id }} to match host system
RUN addgroup --group --gid {{ bai_user_group_id }} etcd && adduser --ingroup etcd --uid {{ bai_user_id }} --disabled-password --no-create-home --gecos "" --shell /bin/sh etcd

USER etcd
