{
 "title": "Backend.AI Overall Resource Usages",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "TOTAL_GPU_COUNT", "label": "Total GPU Count", "query": "${VAR_TOTAL_GPU_COUNT}" },
   { "name": "GPU_COUNT_PER_NODE", "query": "${VAR_GPU_COUNT_PER_NODE}" },
   { "name": "timeAggregation", "label": "Aggregate Interval", "query": "day,hour,week,month" },
   {
    "name": "bai_project",
    "label": "Backend.AI Project",
    "query": "SELECT name FROM groups where is_active = 't';"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Agents",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(\"id\") FILTER (WHERE status = 'ALIVE') as \"Alive\",\n  COUNT(\"id\") FILTER (WHERE NOT (status IN ('LOST', 'TERMINATED') AND lost_at < CURRENT_DATE - INTERVAL '1 month')) as \"Total\"\nFROM agents\n;"
    }
   ]
  },
  {
   "title": "Current Compute Session Counts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Sessions" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) FILTER (WHERE status IN ('RUNNING', 'PENDING', 'SCHEDULED', 'PREPARING', 'PULLING', 'TERMINATING')) as \"Active\",\n  COUNT(*) FILTER (WHERE status IN ('TERMINATED', 'CANCELLED', 'ERROR')) as \"Terminated\"\nFROM sessions;"
    }
   ]
  },
  {
   "title": "Total GPU Utilization",
   "type": "timeseries",
   "description": "This panel tracks maximum and average GPU utilization, providing insights into GPU usage patterns. The maximum utilization values indicate periods of high GPU demand, while the average utilization reflects overall usage trends.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time, $__interval),\n  MAX((accel_util->>'current')::float) AS \"Maximum GPU Utilization (%)\",\n  AVG((accel_util->>'current')::float) AS \"Average GPU Utilization (%)\"\nFROM agent_agentmetric\nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1 DESC\n;"
    }
   ]
  },
  {
   "title": "Total GPU memory occupancy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time, $__interval),\n  MAX((accel_mem->>'current')::float) AS \"Maximum GPU Memory\",\n  AVG((accel_mem->>'current')::float) AS \"Average GPU Memory\"\nFROM agent_agentmetric\nWHERE $__timeFilter(time)\nGROUP BY 1\nORDER BY 1 DESC\n;"
    }
   ]
  },
  {
   "title": "GPU core utilization per node",
   "type": "timeseries",
   "description": "Utilization is 100% if a single device is fully utilized.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time, $__interval),\n  host,\n  AVG((accel_util->>'current')::float)\nFROM agent_agentmetric\nWHERE $__timeFilter(time)\nGROUP BY 1, host\nORDER BY 1, host\n;"
    }
   ]
  },
  {
   "title": "GPU memory utilization per node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time, $__interval),\n  host,\n  AVG((accel_mem->>'current')::float)\nFROM agent_agentmetric\nWHERE $__timeFilter(time)\nGROUP BY 1, host\nORDER BY 1, host\n;"
    }
   ]
  },
  { "title": "Original Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total GPU Allocation Count",
   "type": "timeseries",
   "description": "It represents the total number of GPUs allocated during aggregate interval. Even for compute sessions that are created and terminated within the same aggregate interval, the resource allocation will be counted. Therefore, a single resource can be allocated to two different compute sessions in the same interval, and the number of resource allocations can be greater than the total amount of resources available on the server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_series.date,\n  SUM(CASE\n        WHEN session_info.preparing <= date_series.date AND\n             session_info.terminated >= date_series.date\n        THEN (requested_slots->>'cuda.shares')::float\n        ELSE 0\n      END) AS \"Total Allocation\"\nFROM\n  (SELECT generate_series($__timeFrom()::date, $__timeTo()::date,\n     CASE\n       WHEN '$timeAggregation' = 'hour' THEN interval '1 hour'\n       WHEN '$timeAggregation' = 'day' THEN interval '1 day'\n       WHEN '$timeAggregation' = 'week' THEN interval '1 week'\n       WHEN '$timeAggregation' = 'month' THEN interval '1 month'\n     END) as date) as date_series\n  CROSS JOIN LATERAL\n  (SELECT\n     DATE((status_history->>'PREPARING')::timestamp) as preparing,\n     COALESCE(\n       DATE((status_history->>'TERMINATING')::timestamp),\n       DATE(terminated_at),\n       DATE((status_history->>'CANCELLED')::timestamp),\n       CURRENT_DATE\n     ) as terminated,\n     requested_slots\n   FROM\n     sessions\n   WHERE\n     status_history->>'RUNNING' IS NOT NULL AND\n     COALESCE(DATE((status_history->>'TERMINATING')::timestamp), CURRENT_DATE) >= $__timeFrom()::date) AS session_info\nGROUP BY date_series.date\nORDER BY date_series.date\n;"
    }
   ]
  },
  {
   "title": "Total Active Session Counts",
   "type": "timeseries",
   "description": "It represents the total number of active compute sessions in a day. The compute sessions that are created and terminated within the same day will also be counted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_series.date,\n  COUNT(session_times.session_id) AS \"Number of Active Sessions\"\nFROM\n  (SELECT generate_series($__timeFrom()::date, $__timeTo()::date,\n    CASE\n      WHEN '$timeAggregation' = 'hour' THEN interval '1 hour'\n      WHEN '$timeAggregation' = 'day' THEN interval '1 day'\n      WHEN '$timeAggregation' = 'week' THEN interval '1 week'\n      WHEN '$timeAggregation' = 'month' THEN interval '1 month'\n    END) as date) as date_series\n  LEFT JOIN LATERAL\n  (SELECT\n     sessions.id as session_id,\n     DATE((status_history->>'RUNNING')::timestamp) as running_start,\n     COALESCE(\n       DATE((status_history->>'TERMINATING')::timestamp),\n       DATE(terminated_at),\n       DATE((status_history->>'CANCELLED')::timestamp),\n       CURRENT_DATE\n     ) as running_end\n   FROM\n     sessions\n   WHERE\n     status_history->>'RUNNING' IS NOT NULL) AS session_times\n   ON session_times.running_start <= date_series.date\n   AND session_times.running_end >= date_series.date\nGROUP BY\n  date_series.date\nORDER BY\n  date_series.date\n;"
    }
   ]
  },
  {
   "title": "Total Allocated GPUs per Project",
   "type": "timeseries",
   "description": "It represents the total number of GPUs allocated daily per project. Even for compute sessions that are created and terminated within the same day, the resource allocation will be counted. Therefore, a single resource can be allocated to two different compute sessions in a day, and the number of resource allocations can be greater than the total amount of resources available on the project.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_series.date,\n  groups.name AS project_name,\n  SUM(CASE\n        WHEN session_info.preparing <= date_series.date AND\n             session_info.terminated >= date_series.date\n        THEN (requested_slots->>'cuda.shares')::float\n        ELSE 0\n      END) AS \"PRJ\"\nFROM\n  (SELECT generate_series($__timeFrom()::date, $__timeTo()::date,\n    CASE\n      WHEN '$timeAggregation' = 'hour' THEN interval '1 hour'\n      WHEN '$timeAggregation' = 'day' THEN interval '1 day'\n      WHEN '$timeAggregation' = 'week' THEN interval '1 week'\n      WHEN '$timeAggregation' = 'month' THEN interval '1 month'\n    END) as date) as date_series\n  CROSS JOIN LATERAL\n  (SELECT\n     DATE((status_history->>'PREPARING')::timestamp) as preparing,\n     COALESCE(\n       DATE((status_history->>'TERMINATING')::timestamp),\n       DATE(terminated_at),\n       DATE((status_history->>'CANCELLED')::timestamp),\n       CURRENT_DATE\n     ) as terminated,\n     requested_slots,\n     group_id\n   FROM\n     sessions\n   WHERE\n     status_history->>'RUNNING' IS NOT NULL AND\n     COALESCE(DATE((status_history->>'TERMINATING')::timestamp), CURRENT_DATE) >= $__timeFrom()::date) AS session_info\n  JOIN groups ON groups.id = session_info.group_id  -- Join with groups table\nGROUP BY date_series.date, groups.name\nORDER BY date_series.date, groups.name;"
    }
   ]
  },
  {
   "title": "Total Allocated GPUs per Resource Group",
   "type": "timeseries",
   "description": "It represents the total number of GPUs allocated daily per resource group. Even for compute sessions that are created and terminated within the same day, the resource allocation will be counted. Therefore, a single resource can be allocated to two different compute sessions in a day, and the number of resource allocations can be greater than the total amount of resources available on the resource group.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_series.date,\n  session_info.scaling_group_name,\n  SUM(CASE\n        WHEN session_info.preparing <= date_series.date AND\n             session_info.terminated >= date_series.date\n        THEN (requested_slots->>'cuda.shares')::float\n        ELSE 0\n      END) AS \"RG\"\nFROM\n  (SELECT generate_series($__timeFrom()::date, $__timeTo()::date,\n    CASE\n      WHEN '$timeAggregation' = 'hour' THEN interval '1 hour'\n      WHEN '$timeAggregation' = 'day' THEN interval '1 day'\n      WHEN '$timeAggregation' = 'week' THEN interval '1 week'\n      WHEN '$timeAggregation' = 'month' THEN interval '1 month'\n    END) as date) as date_series\n  CROSS JOIN LATERAL\n  (SELECT\n     DATE((status_history->>'PREPARING')::timestamp) as preparing,\n     COALESCE(\n       DATE((status_history->>'TERMINATING')::timestamp),\n       DATE(terminated_at),\n       DATE((status_history->>'CANCELLED')::timestamp),\n       CURRENT_DATE\n     ) as terminated,\n     requested_slots,\n     scaling_group_name\n   FROM\n     sessions\n   WHERE\n     status_history->>'RUNNING' IS NOT NULL AND\n     COALESCE(DATE((status_history->>'TERMINATING')::timestamp), CURRENT_DATE) >= $__timeFrom()::date) AS session_info\nGROUP BY date_series.date, session_info.scaling_group_name\nORDER BY date_series.date, session_info.scaling_group_name\n;"
    }
   ]
  },
  { "title": "New Panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Total GPU Allocation",
   "type": "timeseries",
   "description": "This metric shows the degree to which a GPU is occupied during the aggregate interval. If a single GPU is continuously allocated during the aggregate interval, the GPU allocation value will be 1.\n\nFor example, if the aggregate interval is set to \"day\" and a single GPU is allocated for 1 hour, the GPU allocation value will be 0.04 (= 1/24 hours). If a single GPU is allocated for 1 hour each in two different compute sessions at different times during the day, the GPU allocation value will be 0.08.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_series.date,\n  SUM(\n    CASE \n      WHEN EXTRACT(EPOCH FROM (\n        LEAST(session_info.terminated, date_series.date + interval '1 $timeAggregation') -\n        GREATEST(session_info.preparing, date_series.date)\n      )) > 0\n      THEN\n        (requested_slots->>'cuda.shares')::float *\n        EXTRACT(EPOCH FROM (\n          LEAST(session_info.terminated, date_series.date + interval '1 $timeAggregation') -\n          GREATEST(session_info.preparing, date_series.date)\n        ))\n        /\n        GREATEST(\n          EXTRACT(EPOCH FROM (\n            interval '1 $timeAggregation'\n          )),\n          1 -- Prevent division by zero\n        )\n        * CASE '$timeAggregation' WHEN 'hour' THEN 1.0 / 24 WHEN 'day' THEN 1 WHEN 'week' THEN 7 WHEN 'month' THEN 30 ELSE 1 END\n      ELSE 0 -- If the condition is not met (i.e., duration is zero), contribute 0 to the sum.\n    END\n  ) AS \"Total GPU Allocation\"\nFROM\n  (SELECT generate_series($__timeFrom()::date, $__timeTo()::date, interval '1 $timeAggregation') as date) as date_series\n  CROSS JOIN LATERAL\n  (SELECT\n     DATE((status_history->>'PREPARING')::timestamp) as preparing,\n     COALESCE(\n       DATE((status_history->>'TERMINATING')::timestamp),\n       DATE(terminated_at),\n       DATE((status_history->>'CANCELLED')::timestamp),\n       CURRENT_DATE + interval '1 $timeAggregation' - interval '1 second' -- just before the next period starts\n     ) as terminated,\n     requested_slots\n   FROM\n     sessions\n   WHERE\n     status_history->>'RUNNING' IS NOT NULL AND\n     COALESCE(DATE((status_history->>'TERMINATING')::timestamp), CURRENT_DATE) >= $__timeFrom()::date) AS session_info\nGROUP BY date_series.date\nORDER BY date_series.date\n;"
    }
   ]
  },
  {
   "title": "Total GPU Allocation per Project ($bai_project)",
   "type": "timeseries",
   "description": "This metric shows the degree to which a GPU is occupied during the aggregate interval PER PROJECT. If a single GPU is continuously allocated during the aggregate interval, the GPU allocation value will be 1.\n\nFor example, if the aggregate interval is set to \"day\" and a single GPU is allocated for 1 hour, the GPU allocation value will be 0.04 (= 1/24 hours). If a single GPU is allocated for 1 hour each in two different compute sessions at different times during the day, the GPU allocation value will be 0.08.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_series.date,\n  SUM(\n    CASE \n      WHEN EXTRACT(EPOCH FROM (\n        LEAST(session_info.terminated, date_series.date + interval '1 $timeAggregation') -\n        GREATEST(session_info.preparing, date_series.date)\n      )) > 0\n      THEN\n        (requested_slots->>'cuda.shares')::float *\n        EXTRACT(EPOCH FROM (\n          LEAST(session_info.terminated, date_series.date + interval '1 $timeAggregation') -\n          GREATEST(session_info.preparing, date_series.date)\n        ))\n        /\n        GREATEST(\n          EXTRACT(EPOCH FROM (\n            interval '1 $timeAggregation'\n          )),\n          1 -- Prevent division by zero\n        )\n      * CASE '$timeAggregation' WHEN 'hour' THEN 1.0 / 24 WHEN 'day' THEN 1 WHEN 'week' THEN 7 WHEN 'month' THEN 30 ELSE 1 END\n      ELSE 0 -- If the condition is not met (i.e., duration is zero), contribute 0 to the sum.\n    END\n  ) AS \"Total GPU Allocation per Project\"\nFROM\n  (SELECT generate_series($__timeFrom()::date, $__timeTo()::date, interval '1 $timeAggregation') as date) as date_series\n  CROSS JOIN LATERAL\n  (SELECT\n     DATE((status_history->>'PREPARING')::timestamp) as preparing,\n     COALESCE(\n       DATE((status_history->>'TERMINATING')::timestamp),\n       DATE(terminated_at),\n       DATE((status_history->>'CANCELLED')::timestamp),\n       CURRENT_DATE + interval '1 $timeAggregation' - interval '1 second' -- just before the next period starts\n     ) as terminated,\n     requested_slots\n   FROM\n     sessions\n   JOIN groups ON sessions.group_id = groups.id\n   WHERE\n     groups.name = '$bai_project'\n     AND status_history->>'RUNNING' IS NOT NULL\n     AND COALESCE(DATE((status_history->>'TERMINATING')::timestamp), CURRENT_DATE) >= $__timeFrom()::date) AS session_info\nGROUP BY date_series.date\nORDER BY date_series.date\n;"
    }
   ]
  },
  {
   "title": "Total GPU Allocation %",
   "type": "timeseries",
   "description": "(GPU Allocation / GPU Capacity) * 100",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_series.date,\n  SUM(\n    CASE \n      WHEN EXTRACT(EPOCH FROM (\n        LEAST(session_info.terminated, date_series.date + interval '1 $timeAggregation') -\n        GREATEST(session_info.preparing, date_series.date)\n      )) > 0\n      THEN\n        (requested_slots->>'cuda.shares')::float *\n        EXTRACT(EPOCH FROM (\n          LEAST(session_info.terminated, date_series.date + interval '1 $timeAggregation') -\n          GREATEST(session_info.preparing, date_series.date)\n        ))\n        /\n        GREATEST(\n          EXTRACT(EPOCH FROM (\n            interval '1 $timeAggregation'\n          )),\n          1 -- Prevent division by zero\n        )\n      ELSE 0 -- If the condition is not met (i.e., duration is zero), contribute 0 to the sum.\n    END\n  ) / $TOTAL_GPU_COUNT * 100 AS \"Total GPU Allocation (%)\"\nFROM\n  (SELECT generate_series($__timeFrom()::date, $__timeTo()::date, interval '1 $timeAggregation') as date) as date_series\n  CROSS JOIN LATERAL\n  (SELECT\n     DATE((status_history->>'PREPARING')::timestamp) as preparing,\n     COALESCE(\n       DATE((status_history->>'TERMINATING')::timestamp),\n       DATE(terminated_at),\n       DATE((status_history->>'CANCELLED')::timestamp),\n       CURRENT_DATE + interval '1 $timeAggregation' - interval '1 second' -- just before the next period starts\n     ) as terminated,\n     requested_slots\n   FROM\n     sessions\n   WHERE\n     status_history->>'RUNNING' IS NOT NULL AND\n     COALESCE(DATE((status_history->>'TERMINATING')::timestamp), CURRENT_DATE) >= $__timeFrom()::date) AS session_info\nGROUP BY date_series.date\nORDER BY date_series.date\n;"
    }
   ]
  },
  {
   "title": "Total GPU Allocation % per Project ($bai_project)",
   "type": "timeseries",
   "description": "(GPU Allocation / GPU Capacity) * 100",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_series.date,\n  SUM(\n    CASE \n      WHEN EXTRACT(EPOCH FROM (\n        LEAST(session_info.terminated, date_series.date + interval '1 $timeAggregation') -\n        GREATEST(session_info.preparing, date_series.date)\n      )) > 0\n      THEN\n        (requested_slots->>'cuda.shares')::float *\n        EXTRACT(EPOCH FROM (\n          LEAST(session_info.terminated, date_series.date + interval '1 $timeAggregation') -\n          GREATEST(session_info.preparing, date_series.date)\n        ))\n        /\n        GREATEST(\n          EXTRACT(EPOCH FROM (\n            interval '1 $timeAggregation'\n          )),\n          1 -- Prevent division by zero\n        )\n      -- * CASE '$timeAggregation' WHEN 'hour' THEN 1.0 / 24 WHEN 'day' THEN 1 WHEN 'week' THEN 7 WHEN 'month' THEN 30 ELSE 1 END\n      ELSE 0 -- If the condition is not met (i.e., duration is zero), contribute 0 to the sum.\n    END\n  ) / $TOTAL_GPU_COUNT * 100 AS \"Total GPU Allocation % per Project\"\nFROM\n  (SELECT generate_series($__timeFrom()::date, $__timeTo()::date, interval '1 $timeAggregation') as date) as date_series\n  CROSS JOIN LATERAL\n  (SELECT\n     DATE((status_history->>'PREPARING')::timestamp) as preparing,\n     COALESCE(\n       DATE((status_history->>'TERMINATING')::timestamp),\n       DATE(terminated_at),\n       DATE((status_history->>'CANCELLED')::timestamp),\n       CURRENT_DATE + interval '1 $timeAggregation' - interval '1 second' -- just before the next period starts\n     ) as terminated,\n     requested_slots\n   FROM\n     sessions\n   JOIN groups ON sessions.group_id = groups.id\n   WHERE\n     groups.name = '$bai_project'\n     AND status_history->>'RUNNING' IS NOT NULL\n     AND COALESCE(DATE((status_history->>'TERMINATING')::timestamp), CURRENT_DATE) >= $__timeFrom()::date) AS session_info\nGROUP BY date_series.date\nORDER BY date_series.date\n;"
    }
   ]
  },
  {
   "title": "Total Allocated GPU Utilization",
   "type": "timeseries",
   "description": "This panel tracks average GPU utilization, only for the allocated GPUs. The maximum utilization values indicate periods of high GPU demand, while the average utilization reflects overall usage trends.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeAggregation', time) AS time_aggregation,\n  AVG((accel_util->>'current')::float / (accel_util->>'capacity')::float * 100) AS \"Average GPU Utilization (%)\"\nFROM session_computesessionmetric\nWHERE time >= to_timestamp($__timeFrom(), 'YYYY-MM-DD H')\n  AND time < to_timestamp($__timeTo(), 'YYYY-MM-DD H')\n  AND accel_util->>'capacity' IS NOT NULL\n  AND (accel_util->>'capacity')::float > 0\nGROUP BY time_aggregation\nORDER BY time_aggregation DESC\n;"
    }
   ]
  },
  {
   "title": "Allocated GPU Utilization Per Project ($bai_project)",
   "type": "timeseries",
   "description": "This panel tracks average GPU utilization, only for GPUs allocated to the project. The maximum utilization values indicate periods of high GPU demand, while the average utilization reflects overall usage trends.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('$timeAggregation', time) AS time_aggregation,\n  AVG((accel_util->>'current')::float / (accel_util->>'capacity')::float * 100) AS \"Average GPU Utilization (%)\",\n  session_id\nFROM session_computesessionmetric\nWHERE time >= to_timestamp($__timeFrom(), 'YYYY-MM-DD H')\n  AND time < to_timestamp($__timeTo(), 'YYYY-MM-DD H')\n  AND accel_util->>'capacity' IS NOT NULL\n  AND (accel_util->>'capacity')::float > 0\nGROUP BY time_aggregation, session_id\nORDER BY time_aggregation DESC, session_id\n;"
    },
    {
     "rawSql": "SELECT\n  s.id AS session_id, g.name as project_name\nFROM sessions AS s\nJOIN groups g ON s.group_id = g.id\nWHERE s.created_at <= to_timestamp($__timeTo(), 'YYYY-MM-DD H')\n  AND (s.terminated_at IS NULL OR s.terminated_at >= to_timestamp($__timeFrom(), 'YYYY-MM-DD H'))\n  AND g.name = '$bai_project'\nORDER BY session_id\n;"
    }
   ]
  }
 ]
}