{
 "title": "Redis Cluster",
 "description": "Dashboard is showing state and configuration for Redis cluster",
 "tags": [
  "Redis",
  "Keydb",
  "Cache"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Has Leader",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance status",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 4, "y": 0 },
   "targets": [
    { "expr": "redis_up", "legendFormat": "__auto" },
    { "expr": "redis_uptime_in_seconds", "legendFormat": "__auto" },
    { "expr": "redis_cluster_enabled", "legendFormat": "__auto" },
    {
     "expr": "redis_instance_info{role=\"master\"}",
     "legendFormat": "__auto"
    },
    { "expr": "redis_slave_priority", "legendFormat": "__auto" },
    { "expr": "redis_master_sync_in_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Leader History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "redis_instance_info{role=\"master\"} > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "connected, {{instance}}" },
    { "expr": "redis_blocked_clients", "legendFormat": "blocked, {{instance}}" }
   ]
  },
  {
   "title": "Command Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(redis_commands_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hits / Misses Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total[5m])",
     "legendFormat": "hits, {{ instance }}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total[5m])",
     "legendFormat": "misses, {{ instance }}"
    }
   ]
  },
  {
   "title": "Network I/O Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(redis_net_input_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Replica", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Master replica offset",
   "type": "timeseries",
   "description": "The server's current replication offset",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "redis_master_repl_offset", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Second replica offset",
   "type": "timeseries",
   "description": "The offset up to which replication IDs are accepted",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "redis_second_repl_offset", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Slave replica offset",
   "type": "timeseries",
   "description": "The replication offset of the replica instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "redis_slave_repl_offset", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Master last IO seconds",
   "type": "timeseries",
   "description": "Number of seconds since the last interaction with master",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "redis_master_last_io_seconds_ago",
     "legendFormat": "Instance {{instance}} || Master host: {{master_host}}:{{master_port}}"
    }
   ]
  },
  { "title": "Backlog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Backlog is active",
   "type": "table",
   "description": "Flag indicating replication backlog is active",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    { "expr": "redis_repl_backlog_is_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backlog size",
   "type": "timeseries",
   "description": "Total size in bytes of the replication backlog buffer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_replication_backlog_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Backlog history size",
   "type": "timeseries",
   "description": "Size in bytes of the data in the replication backlog buffer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_repl_backlog_history_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Master backlog offset",
   "type": "timeseries",
   "description": "The master offset of the replication backlog buffer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "redis_repl_backlog_first_byte_offset",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}