apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bai-swarm-net.fullname" . }}-script
  labels:
    {{- include "bai-swarm-net.labels" . | nindent 4 }}
data:
  daemon.py: |
{{ .Files.Get "files/daemon.py" | indent 4 }}
