apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bai-swarm-net.fullname" . }}-secrets
  labels:
    {{- include "bai-swarm-net.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-token: {{ .Values.daemon.authToken | quote }}
