"""GraphQL types and resolvers for kernel management."""

from __future__ import annotations

from .fetcher import fetch_kernels
from .types import (
    KernelAttachedDeviceEntryGQL,
    KernelAttachedDevicesGQL,
    KernelClusterInfoGQL,
    KernelConnectionV2GQL,
    KernelDeviceModelInfoGQL,
    KernelEdgeGQL,
    KernelFilterGQL,
    KernelImageInfoGQL,
    KernelInternalDataGQL,
    KernelLifecycleInfoGQL,
    KernelMetadataInfoGQL,
    KernelMetricsInfoGQL,
    KernelNetworkInfoGQL,
    KernelOrderByGQL,
    KernelOrderFieldGQL,
    KernelResourceInfoGQL,
    KernelRuntimeInfoGQL,
    KernelSessionInfoGQL,
    KernelSessionStatusDataGQL,
    KernelStatEntryGQL,
    KernelStatGQL,
    KernelStatusDataContainerGQL,
    KernelStatusDataGQL,
    KernelStatusErrorInfoGQL,
    KernelStatusFilterGQL,
    KernelStatusGQL,
    KernelStatusHistoryEntryGQL,
    KernelStatusHistoryGQL,
    KernelUserPermissionInfoGQL,
    KernelV2GQL,
)

__all__ = [
    # Types
    "KernelAttachedDeviceEntryGQL",
    "KernelAttachedDevicesGQL",
    "KernelClusterInfoGQL",
    "KernelConnectionV2GQL",
    "KernelDeviceModelInfoGQL",
    "KernelEdgeGQL",
    "KernelFilterGQL",
    "KernelImageInfoGQL",
    "KernelInternalDataGQL",
    "KernelLifecycleInfoGQL",
    "KernelMetadataInfoGQL",
    "KernelMetricsInfoGQL",
    "KernelNetworkInfoGQL",
    "KernelOrderByGQL",
    "KernelOrderFieldGQL",
    "KernelResourceInfoGQL",
    "KernelRuntimeInfoGQL",
    "KernelSessionInfoGQL",
    "KernelSessionStatusDataGQL",
    "KernelStatEntryGQL",
    "KernelStatGQL",
    "KernelStatusDataContainerGQL",
    "KernelStatusDataGQL",
    "KernelStatusErrorInfoGQL",
    "KernelStatusFilterGQL",
    "KernelStatusGQL",
    "KernelStatusHistoryEntryGQL",
    "KernelStatusHistoryGQL",
    "KernelUserPermissionInfoGQL",
    "KernelV2GQL",
    # Fetchers
    "fetch_kernels",
]
