"""Creating a domain: who may, and what the new domain comes back as."""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID

import pytest
from bai_scenario.components.domain import (
    DomainScenario,
    SomeoneOf,
    enforcement_off,
)
from bai_scenario.runner.runner import ScenarioRunner
from bai_scenario.seeds.domain.domain import SeedDomain
from bai_scenario.seeds.seeder import Seeder, after

from ai.backend.common.data.entity.domain import DomainID
from ai.backend.common.data.user.types import UserRole
from ai.backend.common.dto.manager.v2.domain.request import CreateDomainInput
from ai.backend.common.dto.manager.v2.domain.response import (
    DomainBasicInfo,
    DomainLifecycleInfo,
    DomainNode,
    DomainPayload,
    DomainRegistryInfo,
)
from ai.backend.common.exception import InvalidAPIParameters
from ai.backend.manager.api.adapters.domain.adapter import DomainAdapter
from ai.backend.manager.errors.auth import InsufficientPrivilege
from ai.backend.testutils.typed_scenario import (
    TypedScenario,
    call,
    checked,
    exactly,
    ignored,
    needs_actor,
)


def whole_node_comes_back(seed: Seeder) -> DomainScenario:
    home = seed.creating(SeedDomain(name_hint="home"))
    superadmin = seed.within(SomeoneOf(home, role=UserRole.SUPERADMIN))
    return TypedScenario.ok(
        "creating-a-domain-answers-with-the-whole-node",
        description=(
            "슈퍼관리자가 이름과 설명만 주고 도메인을 만들면, "
            "요청에 없던 값들은 기본값으로 채워진 노드 전체가 답으로 온다"
        ),
        actor=superadmin,
        given=seed.situation(),
        when=needs_actor(
            lambda actor: call(
                DomainAdapter.admin_create,
                CreateDomainInput(name="new-domain", description="a fresh one"),
                actor,
            ),
            "admin_create",
        ),
        then=exactly(
            DomainPayload(
                domain=DomainNode(
                    id=DomainID(UUID(int=0)),
                    basic_info=DomainBasicInfo(
                        name="new-domain", description="a fresh one", integration_name=None
                    ),
                    registry=DomainRegistryInfo(allowed_docker_registries=[]),
                    lifecycle=DomainLifecycleInfo(
                        is_active=True,
                        is_default=False,
                        created_at=datetime.now(UTC),
                        modified_at=datetime.now(UTC),
                    ),
                )
            ),
            where=(
                ignored(lambda p: p.domain.id, "generated by the database"),
                checked(
                    lambda p: p.domain.lifecycle.created_at,
                    seed.since_started(),
                    "이 실행이 쓴 시각",
                ),
                checked(
                    lambda p: p.domain.lifecycle.modified_at,
                    seed.since_started(),
                    "이 실행이 쓴 시각",
                ),
            ),
        ),
    )


def duplicate_name_is_refused(seed: Seeder) -> DomainScenario:
    home = seed.creating(SeedDomain(name_hint="home"))
    taken = seed.creating(SeedDomain(name_hint="taken"))
    superadmin = seed.within(SomeoneOf(home, role=UserRole.SUPERADMIN))
    return TypedScenario.error(
        "a-name-another-domain-already-holds-is-refused",
        description=(
            "이미 어떤 도메인이 쓰고 있는 이름으로 만들려 하면, "
            "권한이 있어도 이름이 겹친다는 이유로 거부된다"
        ),
        actor=superadmin,
        given=seed.situation(),
        when=after(
            taken,
            lambda d: needs_actor(
                lambda actor: call(
                    DomainAdapter.admin_create, CreateDomainInput(name=d.name), actor
                ),
                "admin_create",
            ),
        ),
        then=InvalidAPIParameters,
    )


def blank_name_is_refused(seed: Seeder) -> DomainScenario:
    home = seed.creating(SeedDomain(name_hint="home"))
    superadmin = seed.within(SomeoneOf(home, role=UserRole.SUPERADMIN))
    return TypedScenario.error(
        "a-blank-name-is-refused",
        description="이름이 공백뿐이면 도메인을 만들 수 없다",
        actor=superadmin,
        given=seed.situation(),
        when=needs_actor(
            lambda actor: call(DomainAdapter.admin_create, CreateDomainInput(name="   "), actor),
            "admin_create",
        ),
        then=InvalidAPIParameters,
    )


def plain_user_is_refused(seed: Seeder) -> DomainScenario:
    home = seed.creating(SeedDomain(name_hint="home"))
    someone = seed.within(SomeoneOf(home))
    return TypedScenario.error(
        "a-user-who-is-not-the-superadmin-may-not-create-a-domain",
        description=(
            "슈퍼관리자가 아닌 사용자가 도메인을 만들려 하면, "
            "권한을 얼마나 받았는지와 무관하게 역할로 막힌다"
        ),
        actor=someone,
        given=seed.situation(),
        when=needs_actor(
            lambda actor: call(
                DomainAdapter.admin_create, CreateDomainInput(name="by-a-user"), actor
            ),
            "admin_create",
        ),
        then=InsufficientPrivilege,
    )


def enforcement_off_changes_nothing(seed: Seeder) -> DomainScenario:
    home = seed.creating(SeedDomain(name_hint="home"))
    someone = seed.within(SomeoneOf(home))
    return TypedScenario.error(
        "turning-enforcement-off-still-does-not-let-a-user-create-a-domain",
        description=(
            "엔티티 권한 집행을 꺼도 도메인 생성은 여전히 막힌다. "
            "이 문은 권한 그래프가 아니라 역할이 지키기 때문이다"
        ),
        actor=someone,
        given=enforcement_off(seed),
        when=needs_actor(
            lambda actor: call(
                DomainAdapter.admin_create, CreateDomainInput(name="by-a-user-again"), actor
            ),
            "admin_create",
        ),
        then=InsufficientPrivilege,
    )


BUILDERS = (
    whole_node_comes_back,
    duplicate_name_is_refused,
    blank_name_is_refused,
    plain_user_is_refused,
    enforcement_off_changes_nothing,
)
SCENARIOS: list[DomainScenario] = [build(Seeder()) for build in BUILDERS]


@pytest.mark.parametrize("scenario", SCENARIOS, ids=lambda s: s.summary)
async def test_creating(scenario: DomainScenario, run: ScenarioRunner) -> None:
    await run(scenario)
