"""Editing a domain, and who may."""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID

import pytest
from bai_scenario.components.domain import (
    ADomainIsThere,
    DomainScenario,
    the_domain_admin_role,
    within_the_run,
)
from bai_scenario.infra.personas import DOMAIN_ADMIN, MEMBER
from bai_scenario.runner.runner import ScenarioRunner

from ai.backend.common.data.entity.domain import DomainID
from ai.backend.common.dto.manager.v2.domain.request import (
    UpdateDomainInput,
)
from ai.backend.common.dto.manager.v2.domain.response import (
    DomainBasicInfo,
    DomainLifecycleInfo,
    DomainNode,
    DomainPayload,
    DomainRegistryInfo,
)
from ai.backend.manager.api.adapters.domain.adapter import DomainAdapter
from ai.backend.manager.errors.base.entity import EntityNotFoundError
from ai.backend.manager.errors.permission import NotEnoughPermission
from ai.backend.testutils.typed_scenario import (
    TypedScenario,
    after,
    at,
    call,
    checked,
    exactly,
    ignored,
    needs_actor,
    situation,
)

A_DOMAIN = ADomainIsThere()

SCENARIOS: list[DomainScenario] = [
    TypedScenario.ok(
        "superadmin-edits-a-description-and-the-rest-is-left-alone",
        given=situation(setup=A_DOMAIN),
        when=after(
            A_DOMAIN.domain,
            lambda row: needs_actor(
                lambda actor: call(
                    DomainAdapter.admin_update,
                    row.name,
                    UpdateDomainInput(description="edited"),
                    actor,
                ),
                "admin_update",
            ),
        ),
        then=exactly(
            DomainPayload(
                domain=DomainNode(
                    id=DomainID(UUID(int=0)),
                    basic_info=DomainBasicInfo(
                        name=A_DOMAIN.name, description="edited", integration_name=None
                    ),
                    registry=DomainRegistryInfo(allowed_docker_registries=[]),
                    lifecycle=DomainLifecycleInfo(
                        is_active=True,
                        is_default=False,
                        created_at=datetime.now(UTC),
                        modified_at=datetime.now(UTC),
                    ),
                )
            ),
            where=(
                ignored(lambda p: p.domain.id, "generated by the database"),
                checked(lambda p: p.domain.lifecycle.created_at, within_the_run(), "just written"),
                checked(lambda p: p.domain.lifecycle.modified_at, within_the_run(), "just edited"),
            ),
        ),
    ),
    TypedScenario.ok(
        "retiring-a-domain-is-an-edit-of-its-active-flag",
        given=situation(setup=A_DOMAIN),
        when=after(
            A_DOMAIN.domain,
            lambda row: needs_actor(
                lambda actor: call(
                    DomainAdapter.admin_update, row.name, UpdateDomainInput(is_active=False), actor
                ),
                "admin_update",
            ),
        ),
        then=at(lambda p: p.domain.lifecycle.is_active, False),
    ),
    TypedScenario.error(
        "editing-a-name-nothing-answers-to-is-not-found",
        # The literal is the point here: nothing answers to it.
        when=needs_actor(
            lambda actor: call(
                DomainAdapter.admin_update,
                "no-such-domain",
                UpdateDomainInput(description="x"),
                actor,
            ),
            "admin_update",
        ),
        then=EntityNotFoundError,
    ),
    TypedScenario.error(
        "a-member-may-not-edit-a-domain",
        actor=MEMBER,
        given=situation(setup=A_DOMAIN),
        when=after(
            A_DOMAIN.domain,
            lambda row: needs_actor(
                lambda actor: call(
                    DomainAdapter.admin_update, row.name, UpdateDomainInput(description="x"), actor
                ),
                "admin_update",
            ),
        ),
        then=NotEnoughPermission,
    ),
    TypedScenario.error(
        "the-domain-admin-may-not-edit-the-domain-either",
        actor=DOMAIN_ADMIN,
        holding=[the_domain_admin_role()],
        given=situation(setup=A_DOMAIN),
        when=after(
            A_DOMAIN.domain,
            lambda row: needs_actor(
                lambda actor: call(
                    DomainAdapter.admin_update, row.name, UpdateDomainInput(description="x"), actor
                ),
                "admin_update",
            ),
        ),
        then=NotEnoughPermission,
    ),
]


@pytest.mark.parametrize("scenario", SCENARIOS, ids=lambda s: s.summary)
async def test_editing(scenario: DomainScenario, run: ScenarioRunner) -> None:
    await run(scenario)
