"""Creating a domain: who may, and what the new domain comes back as."""

from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID

import pytest
from bai_scenario.components.domain import (
    DomainScenario,
    TheNameIsTaken,
    enforcement_off,
    the_domain_admin_role,
    within_the_run,
)
from bai_scenario.infra.personas import DOMAIN_ADMIN, MEMBER
from bai_scenario.runner.runner import ScenarioRunner

from ai.backend.common.data.entity.domain import DomainID
from ai.backend.common.dto.manager.v2.domain.request import (
    CreateDomainInput,
)
from ai.backend.common.dto.manager.v2.domain.response import (
    DomainBasicInfo,
    DomainLifecycleInfo,
    DomainNode,
    DomainPayload,
    DomainRegistryInfo,
)
from ai.backend.common.exception import InvalidAPIParameters
from ai.backend.manager.api.adapters.domain.adapter import DomainAdapter
from ai.backend.manager.errors.auth import InsufficientPrivilege
from ai.backend.testutils.typed_scenario import (
    TypedScenario,
    at,
    call,
    checked,
    exactly,
    ignored,
    needs_actor,
    situation,
)

TAKEN = TheNameIsTaken("taken")

SCENARIOS: list[DomainScenario] = [
    TypedScenario.ok(
        "superadmin-creates-a-domain-and-gets-the-whole-node-back",
        when=needs_actor(
            lambda actor: call(
                DomainAdapter.admin_create,
                CreateDomainInput(name="new-domain", description="a fresh one"),
                actor,
            ),
            "admin_create",
        ),
        then=exactly(
            DomainPayload(
                domain=DomainNode(
                    id=DomainID(UUID(int=0)),
                    basic_info=DomainBasicInfo(
                        name="new-domain", description="a fresh one", integration_name=None
                    ),
                    registry=DomainRegistryInfo(allowed_docker_registries=[]),
                    lifecycle=DomainLifecycleInfo(
                        is_active=True,
                        is_default=False,
                        created_at=datetime.now(UTC),
                        modified_at=datetime.now(UTC),
                    ),
                )
            ),
            where=(
                ignored(lambda p: p.domain.id, "generated by the database"),
                checked(lambda p: p.domain.lifecycle.created_at, within_the_run(), "just written"),
                checked(lambda p: p.domain.lifecycle.modified_at, within_the_run(), "just written"),
            ),
        ),
    ),
    TypedScenario.ok(
        "a-domain-is-created-active-unless-the-request-says-otherwise",
        when=needs_actor(
            lambda actor: call(
                DomainAdapter.admin_create,
                CreateDomainInput(name="dormant", is_active=False),
                actor,
            ),
            "admin_create",
        ),
        then=at(lambda p: p.domain.lifecycle.is_active, False),
    ),
    TypedScenario.ok(
        "the-allowed-registries-of-the-request-are-what-the-domain-gets",
        when=needs_actor(
            lambda actor: call(
                DomainAdapter.admin_create,
                CreateDomainInput(
                    name="with-registries", allowed_docker_registries=["cr.example.io"]
                ),
                actor,
            ),
            "admin_create",
        ),
        then=at(lambda p: p.domain.registry.allowed_docker_registries, ["cr.example.io"]),
    ),
    TypedScenario.error(
        "a-name-already-taken-is-refused",
        given=situation(setup=TAKEN),
        when=needs_actor(
            lambda actor: call(
                DomainAdapter.admin_create, CreateDomainInput(name=TAKEN.name), actor
            ),
            "admin_create",
        ),
        then=InvalidAPIParameters,
    ),
    TypedScenario.error(
        "a-blank-name-is-refused",
        when=needs_actor(
            lambda actor: call(DomainAdapter.admin_create, CreateDomainInput(name="   "), actor),
            "admin_create",
        ),
        then=InvalidAPIParameters,
    ),
    TypedScenario.error(
        "the-domain-admin-may-not-create-a-domain",
        actor=DOMAIN_ADMIN,
        holding=[the_domain_admin_role()],
        when=needs_actor(
            lambda actor: call(
                DomainAdapter.admin_create, CreateDomainInput(name="by-domain-admin"), actor
            ),
            "admin_create",
        ),
        then=InsufficientPrivilege,
    ),
    TypedScenario.error(
        "a-member-may-not-create-a-domain",
        actor=MEMBER,
        when=needs_actor(
            lambda actor: call(
                DomainAdapter.admin_create, CreateDomainInput(name="by-member"), actor
            ),
            "admin_create",
        ),
        then=InsufficientPrivilege,
    ),
    TypedScenario.error(
        # The gate is the role, not the permission graph, so turning enforcement off
        # changes nothing here. That is the rule this row records.
        "turning-enforcement-off-still-does-not-let-a-member-create-a-domain",
        actor=MEMBER,
        given=enforcement_off(),
        when=needs_actor(
            lambda actor: call(
                DomainAdapter.admin_create, CreateDomainInput(name="by-member-again"), actor
            ),
            "admin_create",
        ),
        then=InsufficientPrivilege,
    ),
]


@pytest.mark.parametrize("scenario", SCENARIOS, ids=lambda s: s.summary)
async def test_creating(scenario: DomainScenario, run: ScenarioRunner) -> None:
    await run(scenario)
