from collections.abc import Hashable
from typing import Any as _Any
from typing import NoReturn

from trafaret.dataerror import DataError

class TrafaretMeta(type):
    def __or__(cls, other: _Any) -> _Any: ...
    def __and__(cls, other: _Any) -> _Any: ...
    def __rshift__(cls, other: str) -> _Any: ...

class Trafaret(metaclass=TrafaretMeta):
    def check(self, value: _Any, context: _Any | None = ...) -> _Any: ...
    def _failure(self, error: str | None = None, value: _Any = ...) -> NoReturn: ...
    def append(self, other: _Any) -> _Any: ...
    def __or__(self, other: _Any) -> _Any: ...
    def __and__(self, other: _Any) -> _Any: ...
    def __rshift__(self, other: str) -> _Any: ...
    def __call__(self, val: _Any, context: _Any = None) -> _Any: ...

class Key:
    def __init__(
        self,
        name: Hashable,
        default: _Any = ...,
        optional: bool = False,
        to_name: Hashable | None = None,
        trafaret: Trafaret | None = None,
    ) -> None: ...
    def get_name(self) -> Hashable: ...
    def __rshift__(self, other: str) -> _Any: ...

def ensure_trafaret(trafaret: _Any) -> Trafaret: ...

class TypeMeta(TrafaretMeta):
    def __getitem__(self, type_: _Any) -> _Any: ...

class SquareBracketsMeta(TrafaretMeta):
    def __getitem__(self, args: _Any) -> _Any: ...

class OnError(Trafaret):
    def __init__(self, trafaret: Trafaret, message: str, code: str | None = None) -> None: ...
    def transform(self, value: _Any, context: _Any | None = None) -> _Any: ...

class WithRepr(Trafaret): ...
class TypingTrafaret(Trafaret, metaclass=TypeMeta): ...
class Subclass(TypingTrafaret): ...
class Type(TypingTrafaret): ...
class Any(Trafaret): ...
class And(Trafaret): ...
class Or(Trafaret): ...

class Dict(Trafaret):
    def __init__(self, *args: _Any, **trafarets: _Any) -> None: ...
    def allow_extra(self, *names: str, **kw: _Any) -> Dict: ...
    def ignore_extra(self, *names: str) -> Dict: ...
    def merge(self, other: Dict | list[_Any] | tuple[_Any, ...] | dict[_Any, _Any]) -> Dict: ...

class DictKeys(Trafaret): ...

class Mapping(Trafaret):
    def __init__(self, key: _Any, value: _Any) -> None: ...

class Enum(Trafaret):
    def __init__(self, *variants: _Any) -> None: ...

class Callable(Trafaret): ...

class Call(Trafaret):
    def __init__(self, fn: _Any) -> None: ...

class Forward(Trafaret): ...

class List(Trafaret, metclass=SquareBracketsMeta):
    def __init__(
        self,
        trafaret: Trafaret | type[Trafaret],
        min_length: int = 0,
        max_length: int | None = None,
    ) -> None: ...

class Iterable(Trafaret):
    def __init__(
        self, trafaret: Trafaret, min_length: int = 0, max_length: int | None = None
    ) -> None: ...

class Tuple(Trafaret):
    def __init__(self, *args: _Any) -> None: ...

class Atom(Trafaret):
    def __init__(self, value: str) -> None: ...

class String(Trafaret):
    def __init__(
        self,
        allow_blank: bool = False,
        min_length: int | None = None,
        max_length: int | None = None,
    ) -> None: ...

class Bytes(Trafaret): ...
class ToBytes(Trafaret): ...

class FromBytes(Trafaret):
    def __init__(self, encoding: str = "utf-8") -> None: ...

class Null(Trafaret): ...
class Bool(Trafaret): ...
class ToBool(Trafaret): ...
class Date(Trafaret): ...
class ToDate(Trafaret): ...
class DateTime(Trafaret): ...
class ToDateTime(Trafaret): ...

def guard(trafaret: Trafaret | None = None, **kwargs: _Any) -> _Any: ...
def ignore(val: _Any) -> _Any: ...
def catch(checker: _Any, *a: _Any, **kw: _Any) -> _Any: ...
def extract_error(checker: _Any, *a: _Any, **kw: _Any) -> _Any: ...

class GuardError(DataError): ...
