from collections.abc import Sequence
from typing import Any

from .base import Dict, Key, Trafaret

class KeysSubset(Key):
    def __init__(self, *keys: Sequence[str]) -> None: ...
    def __call__(self, data: Any) -> Any: ...

def subdict(name: str, *keys: Sequence[str | Key], trafaret: Trafaret) -> Dict: ...
def xor_key(first: Any, second: Any, trafaret: Trafaret) -> Any: ...
def confirm_key(name: Any, confirm_name: Any, trafaret: Trafaret) -> Any: ...
