from .base import Trafaret, TrafaretMeta

from typing import Any

class NumberMeta(TrafaretMeta):
    def __getitem__(cls, slice_: Any) -> Any: ...
    def __lt__(cls, lt: Any) -> Any: ...
    def __gt__(cls, gt: Any) -> Any: ...

class Float(Trafaret, metaclass=NumberMeta):
    def __init__(
        self,
        gte: float | None = None,
        lte: float | None = None,
        gt: float | None = None,
        lt: float | None = None,
    ): ...

class ToFloat(Float): ...
class Int(Float): ...
class ToInt(Int): ...
class ToDecimal(Float): ...
