from typing import Optional

from .base import Trafaret, TrafaretMeta

class NumberMeta(TrafaretMeta):
    def __getitem__(cls, slice_): ...
    def __lt__(cls, lt): ...
    def __gt__(cls, gt): ...

class Float(Trafaret, metaclass=NumberMeta):
    def __init__(
        self,
        gte: Optional[float] = None,
        lte: Optional[float] = None,
        gt: Optional[float] = None,
        lt: Optional[float] = None,
    ): ...

class ToFloat(Float): ...
class Int(Float): ...
class ToInt(Int): ...
class ToDecimal(Float): ...
