from .base import TrafaretMeta, Trafaret


class NumberMeta(TrafaretMeta):
    def __getitem__(cls, slice_): ...
    def __lt__(cls, lt): ...
    def __gt__(cls, gt): ...

class Float(Trafaret, metaclass=NumberMeta):
    def __init__(self, gte: float = None, lte: float = None,
                 gt: float = None, lt: float = None): ...
class ToFloat(Float): ...
class Int(Float): ...
class ToInt(Int): ...
class ToDecimal(Float): ...
