apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bai-manager.fullname" . }}-secrets
  labels:
    {{- include "bai-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  manager-secret: {{ .Values.manager.secret | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
  redis-password: {{ .Values.redis.password | quote }}
