"""How an action is backed, orthogonal to the target shape it declares.

An action mixing in one of these executes straight against a repository ops spec, so
the domain writes no service method for it.
"""

from .base import (
    BatchPurgeOpsAction,
    BatchUpdateOpsAction,
    BulkUpdateOpsAction,
    CreateFieldEntityOpsAction,
    FieldEntityCreateOpsAction,
    FieldEntityPurgeOpsAction,
    GetOpsAction,
    GlobalBatchPurgeOpsAction,
    GlobalBatchUpdateOpsAction,
    GlobalEntityCreateOpsAction,
    GlobalEntityPurgeOpsAction,
    GlobalSearchOpsAction,
    LookupOpsAction,
    OpsBackendAction,
    PurgeFieldEntityOpsAction,
    ScopedEntityBulkCreateOpsAction,
    ScopedEntityBulkPurgeOpsAction,
    ScopedEntityCreateOpsAction,
    ScopedEntityPurgeOpsAction,
    ScopedEntityUpsertOpsAction,
    SearchOpsAction,
    UpdateOpsAction,
)
from .result import (
    BatchOpsResult,
    BulkOpsResult,
    CreatedEntityOpsResult,
    EntitiesOpsResult,
    EntityOpsResult,
    LookupOpsResult,
    ScopedBatchOpsResult,
)

__all__ = (
    "BatchOpsResult",
    "BatchPurgeOpsAction",
    "GlobalBatchPurgeOpsAction",
    "BatchUpdateOpsAction",
    "GlobalBatchUpdateOpsAction",
    "ScopedEntityBulkCreateOpsAction",
    "BulkOpsResult",
    "ScopedEntityBulkPurgeOpsAction",
    "BulkUpdateOpsAction",
    "CreateFieldEntityOpsAction",
    "FieldEntityCreateOpsAction",
    "FieldEntityPurgeOpsAction",
    "GlobalEntityCreateOpsAction",
    "ScopedEntityCreateOpsAction",
    "CreatedEntityOpsResult",
    "EntitiesOpsResult",
    "EntityOpsResult",
    "LookupOpsAction",
    "LookupOpsResult",
    "GetOpsAction",
    "OpsBackendAction",
    "GlobalEntityPurgeOpsAction",
    "PurgeFieldEntityOpsAction",
    "ScopedEntityPurgeOpsAction",
    "GlobalSearchOpsAction",
    "ScopedBatchOpsResult",
    "SearchOpsAction",
    "UpdateOpsAction",
    "ScopedEntityUpsertOpsAction",
)
