{
 "title": "Manager Dashboard",
 "time": { "from": "now-20m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Manager Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total API Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(backendai_api_request_count_total[5m])) by (method, endpoint, status_code)",
     "legendFormat": "{{method}} : {{endpoint}} / {{status_code}}"
    }
   ]
  },
  {
   "title": "API Failure Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(backendai_api_request_count_total{status_code=~\"4..|500\"}[5m])) by (method, endpoint, status_code)",
     "legendFormat": "{{method}} : {{endpoint}} / {{status_code}}"
    }
   ]
  },
  {
   "title": "API Request Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, endpoint) (increase(backendai_api_request_duration_sec_sum[5m])) \n/\nsum by (method, endpoint) (increase(backendai_api_request_duration_sec_count[5m]))",
     "legendFormat": "{{method}} : {{endpoint}}"
    }
   ]
  },
  {
   "title": "API Request Duration (P90, P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(backendai_api_request_duration_sec_bucket) by (le, method, endpoint))",
     "legendFormat": "P95 {{method}} : {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_api_request_duration_sec_bucket) by (le, method, endpoint))",
     "legendFormat": "P90 {{method}} : {{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Event Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(backendai_event_count_total[5m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Event Failure Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(backendai_event_failure_count[5m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Event Processing Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (event_type) (increase(backendai_event_processing_time_sec_sum[5m])) \n/\nsum by (event_type) (increase(backendai_event_processing_time_sec_count[5m]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Event Processing Duration (P90, P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(backendai_event_processing_time_sec_bucket) by (le, event_type))",
     "legendFormat": "P95 {{event_type}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_event_processing_time_sec_bucket) by (le, event_type))",
     "legendFormat": "P90 {{event_type}}"
    }
   ]
  },
  {
   "title": "Total BgTask Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(backendai_bgtask_count) by (task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Total BgTask Done Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(backendai_bgtask_done_count_total[5m])) by (task_name, status)",
     "legendFormat": "{{task_name}} / {{status}}"
    }
   ]
  },
  {
   "title": "BgTask Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (task_name, status) (increase(backendai_bgtask_processing_time_sec_sum[5m])) \n/\nsum by (task_name, status) (increase(backendai_bgtask_processing_time_sec_count[5m]))",
     "legendFormat": "{{task_name}} / {{status}}"
    }
   ]
  },
  {
   "title": "BgTask Duration (P90, P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(backendai_bgtask_processing_time_sec_bucket) by (le, task_name, status))",
     "legendFormat": "P95 {{task_name}} / {{status}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_bgtask_processing_time_sec_bucket) by (le, task_name, status))",
     "legendFormat": "P90 {{task_name}} / {{status}}"
    }
   ]
  }
 ]
}