"""add_agent_max_container_count

Revision ID: 0c39a91bfe5f
Revises: 5fbd368d12a2
Create Date: 2023-06-19 16:38:43.358736

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0c39a91bfe5f"
down_revision = "5fbd368d12a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("max_container_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "max_container_count")
    # ### end Alembic commands ###
