"""empty message

Revision ID: 1a7617a57ce0
Revises: 6191962d488a
Create Date: 2023-02-15 19:15:34.998248

"""
import sqlalchemy as sa
from alembic import op

from ai.backend.manager.models.base import GUID, EndpointIDColumnType, ResourceSlotColumn

# revision identifiers, used by Alembic.
revision = "1a7617a57ce0"
down_revision = "6191962d488a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "endpoints",
        sa.Column(
            "id",
            EndpointIDColumnType(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "resource_slots",
            ResourceSlotColumn(),
            nullable=False,
        ),
        sa.Column("traffic_ratio", sa.Float(), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("image", GUID(), nullable=False),
        sa.Column("model", GUID(), nullable=False),
        sa.Column("project", sa.String(length=64), nullable=False),
        sa.Column("resource_group", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["image"], ["images.id"], name=op.f("fk_endpoints_image_images"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["model"],
            ["vfolders.id"],
            name=op.f("fk_endpoints_model_vfolders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project"],
            ["domains.name"],
            name=op.f("fk_endpoints_project_domains"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resource_group"],
            ["scaling_groups.name"],
            name=op.f("fk_endpoints_resource_group_scaling_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_endpoints")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("endpoints")
    # ### end Alembic commands ###
