"""drop endpoints.project (domains.name)

Revision ID: 1e653457d769
Revises: 9ae0980f6110
Create Date: 2023-02-16 19:52:41.694423

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e653457d769"
down_revision = "9ae0980f6110"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_endpoints_project_domains", "endpoints", type_="foreignkey")
    op.drop_column("endpoints", "project")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "endpoints",
        sa.Column("project", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_endpoints_project_domains",
        "endpoints",
        "domains",
        ["project"],
        ["name"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###
