"""add_auto_terminate_abusing_kernel_col

Revision ID: 30da949928bd
Revises: 10c58e701d87
Create Date: 2023-02-28 17:03:06.511309

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "30da949928bd"
down_revision = "10c58e701d87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column(
            "auto_terminate_abusing_kernel",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "auto_terminate_abusing_kernel")
    # ### end Alembic commands ###
