"""add_allowed_ip_column

Revision ID: 311112558c86
Revises: 35923972eddb
Create Date: 2022-08-31 13:12:17.693764

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "311112558c86"
down_revision = "35923972eddb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("allowed_client_ip", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "allowed_client_ip")
    # ### end Alembic commands ###
