"""Add object storage for artifact registry

Revision ID: 345551145801
Revises: 643deb439458
Create Date: 2025-08-05 05:48:29.768739

"""

import sqlalchemy as sa
from alembic import op

from ai.backend.manager.models.base import GUID

# revision identifiers, used by Alembic.
revision = "345551145801"
down_revision = "643deb439458"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", GUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "type", sa.Enum("MODEL", "PACKAGE", "IMAGE", name="artifacttype"), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_index(op.f("ix_artifacts_created_at"), "artifacts", ["created_at"], unique=False)
    op.create_index(op.f("ix_artifacts_name"), "artifacts", ["name"], unique=False)
    op.create_index(op.f("ix_artifacts_type"), "artifacts", ["type"], unique=False)
    op.create_table(
        "association_artifacts_storages",
        sa.Column("id", GUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("artifact_id", GUID(), nullable=False),
        sa.Column("storage_id", GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_association_artifacts_storages")),
        sa.UniqueConstraint("artifact_id", "storage_id", name="uq_artifact_id_storage_id"),
    )
    op.create_table(
        "object_storages",
        sa.Column("id", GUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("access_key", sa.String(), nullable=False),
        sa.Column("secret_key", sa.String(), nullable=False),
        sa.Column("endpoint", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("buckets", sa.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_object_storages")),
    )
    op.create_index(
        op.f("ix_object_storages_buckets"), "object_storages", ["buckets"], unique=False
    )
    op.create_index(op.f("ix_object_storages_name"), "object_storages", ["name"], unique=True)
    op.create_table(
        "storage_objects",
        sa.Column("id", GUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("artifact_id", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_objects")),
        sa.UniqueConstraint("artifact_id", "object_key", name="uq_artifact_id_object_key"),
    )
    op.create_index(
        op.f("ix_storage_objects_artifact_id"), "storage_objects", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_storage_objects_created_at"), "storage_objects", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storage_objects_created_at"), table_name="storage_objects")
    op.drop_index(op.f("ix_storage_objects_artifact_id"), table_name="storage_objects")
    op.drop_table("storage_objects")
    op.drop_index(op.f("ix_object_storages_name"), table_name="object_storages")
    op.drop_index(op.f("ix_object_storages_buckets"), table_name="object_storages")
    op.drop_table("object_storages")
    op.drop_table("association_artifacts_storages")
    op.drop_index(op.f("ix_artifacts_type"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_name"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_created_at"), table_name="artifacts")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
