"""Add artifact_storages common table

Revision ID: 35dfab3b0662
Revises: b0fb0eb6b6bc
Create Date: 2025-12-02 09:24:21.050932

"""

import sqlalchemy as sa
from alembic import op

from ai.backend.manager.models.base import GUID

# revision identifiers, used by Alembic.
revision = "35dfab3b0662"
down_revision = "b0fb0eb6b6bc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifact_storages",
        sa.Column("id", GUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("storage_id", GUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifact_storages")),
        sa.UniqueConstraint("name", name=op.f("uq_artifact_storages_name")),
        sa.UniqueConstraint("storage_id", name=op.f("uq_artifact_storages_storage_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artifact_storages")
    # ### end Alembic commands ###
