"""add_vfolder_usage_mode_type

Revision ID: 3773cf1e4077
Revises: f83d630c0bc9
Create Date: 2022-10-01 17:15:55.113376

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.sql import text

from ai.backend.manager.models.base import GUID, convention
from ai.backend.manager.models.vfolder import VFolderUsageMode

# revision identifiers, used by Alembic.
revision = "3773cf1e4077"
down_revision = "f83d630c0bc9"
branch_labels = None
depends_on = None

enum_name = "vfolderusagemode"
enum_val = "app"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE {enum_name} ADD VALUE '{enum_val}'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Update VFolderUsageMode.APP usage_mode to VFolderUsageMode.GENERAL
    connection = op.get_bind()
    metadata = sa.MetaData(naming_convention=convention)
    vfolders = sa.Table(
        "vfolders",
        metadata,
        sa.Column(
            "id",
            GUID(),
            nullable=False,
            primary_key=True,
        ),
        sa.Column(
            "usage_mode",
            ENUM,
            nullable=False,
        ),
    )
    vfolder_fetch_query = (
        sa.update(vfolders)
        .where(vfolders.c.usage_mode == VFolderUsageMode.APP)
        .values({"usage_mode": VFolderUsageMode.GENERAL.value})
    )
    connection.execute(vfolder_fetch_query)

    sql = f"""DELETE FROM pg_enum
        WHERE enumlabel = '{enum_val}'
        AND enumtypid = (
            SELECT oid FROM pg_type WHERE typname = '{enum_name}'
        )"""
    op.execute(text(sql))
    # ### end Alembic commands ###
