"""add_pending_session_policies

Revision ID: 3c06e520fe92
Revises: 85984c98b90f
Create Date: 2023-06-06 16:15:02.535768

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c06e520fe92"
down_revision = "85984c98b90f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "keypair_resource_policies",
        sa.Column("max_pending_session_count", sa.Integer(), nullable=True),
    )
    op.add_column(
        "keypair_resource_policies",
        sa.Column(
            "max_pending_session_resource_slots",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("keypair_resource_policies", "max_pending_session_resource_slots")
    op.drop_column("keypair_resource_policies", "max_pending_session_count")
    # ### end Alembic commands ###
