"""add_pending_session_policies

Revision ID: 4072c08d416c
Revises: 10c58e701d87
Create Date: 2023-04-14 17:31:14.098756

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4072c08d416c"
down_revision = "10c58e701d87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "keypair_resource_policies", sa.Column("max_pernding_sessions", sa.Integer(), nullable=True)
    )
    op.add_column(
        "keypair_resource_policies",
        sa.Column(
            "max_pending_session_resource_slots",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("keypair_resource_policies", "max_pending_session_resource_slots")
    op.drop_column("keypair_resource_policies", "max_pernding_sessions")
    # ### end Alembic commands ###
