"""add-foreign-keys-and-unique-constraint-to-endpoint-and-endpoint-tokens

Revision ID: 432c36fed34f
Revises: d04592473df7
Create Date: 2023-09-11 15:30:12.431804

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "432c36fed34f"
down_revision = "d04592473df7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_endpoint_tokens_project_groups"),
        "endpoint_tokens",
        "groups",
        ["project"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_endpoint_tokens_domain_domains"),
        "endpoint_tokens",
        "domains",
        ["domain"],
        ["name"],
        ondelete="RESTRICT",
    )
    op.create_unique_constraint(op.f("uq_endpoints_name"), "endpoints", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_endpoints_name"), "endpoints", type_="unique")
    op.drop_constraint(
        op.f("fk_endpoint_tokens_domain_domains"), "endpoint_tokens", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_endpoint_tokens_project_groups"), "endpoint_tokens", type_="foreignkey"
    )
    # ### end Alembic commands ###
