"""add-quota_scope_id

Revision ID: 565293b7395a
Revises: 10c58e701d87
Create Date: 2023-03-29 07:29:27.592211

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = "565293b7395a"
down_revision = "10c58e701d87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vfolders", sa.Column("quota_scope_id", sa.String(length=64), nullable=True))
    op.execute(
        text(
            "UPDATE vfolders "
            "SET quota_scope_id = REPLACE(\"group\"::text, '-', '') "
            "WHERE ownership_type = 'group';"
        )
    )
    op.execute(
        text(
            "UPDATE vfolders "
            "SET quota_scope_id = REPLACE(\"user\"::text, '-', '') "
            "WHERE ownership_type = 'user';"
        )
    )
    op.alter_column("vfolders", "quota_scope_id", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vfolders", "quota_scope_id")
    # ### end Alembic commands ###
