"""set_default_max_vfolder_count_zero

Revision ID: 5af079103795
Revises: 8c74e7df26f8
Create Date: 2023-10-18 15:45:22.725439

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5af079103795"
down_revision = "8c74e7df26f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_resource_policies",
        "max_vfolder_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "user_resource_policies",
        "max_vfolder_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_resource_policies",
        "max_vfolder_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "user_resource_policies",
        "max_vfolder_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
