"""add_vfolder_usage_mode_type

Revision ID: 5e22558221ce
Revises: 360af8f33d4e
Create Date: 2022-10-12 12:17:07.675013

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.sql import text

from ai.backend.manager.models.base import GUID, convention
from ai.backend.manager.models.vfolder import VFolderUsageMode

# revision identifiers, used by Alembic.
revision = "5e22558221ce"
down_revision = "360af8f33d4e"
branch_labels = None
depends_on = None

enum_name = "vfolderusagemode"
enum_val = "app"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"ALTER TYPE {enum_name} ADD VALUE '{enum_val}'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Update VFolderUsageMode.APP usage_mode to VFolderUsageMode.GENERAL
    connection = op.get_bind()
    metadata = sa.MetaData(naming_convention=convention)
    vfolders = sa.Table(
        "vfolders",
        metadata,
        sa.Column(
            "id",
            GUID(),
            nullable=False,
            primary_key=True,
        ),
        sa.Column(
            "usage_mode",
            ENUM,
            nullable=False,
        ),
    )
    vfolder_fetch_query = (
        sa.update(vfolders)
        .where(vfolders.c.usage_mode == VFolderUsageMode.APP)
        .values({"usage_mode": VFolderUsageMode.GENERAL.value})
    )
    connection.execute(vfolder_fetch_query)

    sql = f"""DELETE FROM pg_enum
        WHERE enumlabel = '{enum_val}'
        AND enumtypid = (
            SELECT oid FROM pg_type WHERE typname = '{enum_name}'
        )"""
    op.execute(text(sql))
    # ### end Alembic commands ###
