"""add_password_changed_at_col

Revision ID: 673c9c64d140
Revises: fdc9d6ac49b4
Create Date: 2023-05-18 17:42:29.270969

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "673c9c64d140"
down_revision = "fdc9d6ac49b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password_changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_changed_at")
    # ### end Alembic commands ###
