"""add endpoints.domain to refer domain.name

Revision ID: 7745d29e3278
Revises: e5ca3c29c749
Create Date: 2023-02-16 20:49:52.491416

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7745d29e3278"
down_revision = "e5ca3c29c749"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoints", sa.Column("domain", sa.String(length=64), nullable=False))
    op.create_foreign_key(
        op.f("fk_endpoints_domain_domains"),
        "endpoints",
        "domains",
        ["domain"],
        ["name"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_endpoints_domain_domains"), "endpoints", type_="foreignkey")
    op.drop_column("endpoints", "domain")
    # ### end Alembic commands ###
