"""Add storage_objects table

Revision ID: 8526cf6e8c9c
Revises: 345551145801
Create Date: 2025-08-14 03:12:19.798496

"""

import sqlalchemy as sa
from alembic import op

from ai.backend.manager.models.base import GUID

# revision identifiers, used by Alembic.
revision = "8526cf6e8c9c"
down_revision = "345551145801"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_objects",
        sa.Column("id", GUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("artifact_id", sa.String(), nullable=False),
        sa.Column("object_key", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_objects")),
        sa.UniqueConstraint("artifact_id", "object_key", name="uq_artifact_id_object_key"),
    )
    op.create_index(
        op.f("ix_storage_objects_artifact_id"), "storage_objects", ["artifact_id"], unique=False
    )
    op.create_index(
        op.f("ix_storage_objects_created_at"), "storage_objects", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storage_objects_created_at"), table_name="storage_objects")
    op.drop_index(op.f("ix_storage_objects_artifact_id"), table_name="storage_objects")
    op.drop_table("storage_objects")
    # ### end Alembic commands ###
