"""add groups.per_user_image_storage

Revision ID: 857b763b8618
Revises: 75ea2b136830
Create Date: 2024-03-22 14:20:28.772534

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "857b763b8618"
down_revision = "75ea2b136830"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups", sa.Column("per_user_image_storage_registry", postgresql.JSONB, nullable=True)
    )
    op.create_index(op.f("ix_kernels_role"), "kernels", ["role"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kernels_role"), table_name="kernels")
    op.drop_column("groups", "per_user_image_storage_registry")
    # ### end Alembic commands ###
