"""remove unique constraint of endpoint.url

Revision ID: 8b2ec7e3d22a
Revises: d3f8c74bf148
Create Date: 2024-01-11 11:02:39.253292

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8b2ec7e3d22a"
down_revision = "d3f8c74bf148"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_endpoints_url", "endpoints", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_endpoints_url", "endpoints", ["url"])
    # ### end Alembic commands ###
