"""add_audit_logs

Revision ID: 8ba4b0878e21
Revises: d3f8c74bf148
Create Date: 2024-01-03 16:54:07.371867

"""

# revision identifiers, used by Alembic.
revision = "8ba4b0878e21"
down_revision = "d3f8c74bf148"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
