"""add_max_pending_session_count

Revision ID: 8c84017dd6f2
Revises: eb9441fcf90a
Create Date: 2023-08-05 12:07:42.757608

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8c84017dd6f2"
down_revision = "eb9441fcf90a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "keypair_resource_policies",
        sa.Column("max_pending_session_count", sa.Integer(), nullable=True),
    )
    op.add_column(
        "keypair_resource_policies",
        sa.Column(
            "max_pending_session_resource_slots",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("keypair_resource_policies", "max_pending_session_resource_slots")
    op.drop_column("keypair_resource_policies", "max_pending_session_count")
    # ### end Alembic commands ###
