"""add_max_pending_session_count

Revision ID: 98aa54817228
Revises: ae7d4cd92aa7
Create Date: 2023-08-30 13:22:24.111739

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "98aa54817228"
down_revision = "ae7d4cd92aa7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "keypair_resource_policies",
        sa.Column("max_pending_session_count", sa.Integer(), nullable=True),
    )
    op.add_column(
        "keypair_resource_policies",
        sa.Column(
            "max_pending_session_resource_slots",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("keypair_resource_policies", "max_pending_session_resource_slots")
    op.drop_column("keypair_resource_policies", "max_pending_session_count")
    # ### end Alembic commands ###
