"""add_bgtask_column

Revision ID: a06a497c3db9
Revises: 35923972eddb
Create Date: 2022-08-16 17:14:45.801197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06a497c3db9'
down_revision = '35923972eddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kernels', sa.Column('bgtask_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kernels', 'bgtask_id')
    # ### end Alembic commands ###
