"""Allow duplicated session names across different user

Revision ID: a4289ef5f0cd
Revises: 25ac68cb28ba
Create Date: 2025-12-18 10:45:02.643554

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a4289ef5f0cd"
down_revision = "25ac68cb28ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_sessions_unique_name_nonterminal",
        table_name="sessions",
        postgresql_where="((status)::text <> ALL ((ARRAY['ERROR'::character varying, 'TERMINATED'::character varying, 'CANCELLED'::character varying])::text[]))",
    )
    op.create_index(
        "ix_sessions_unique_name_per_user_nonterminal",
        "sessions",
        ["name", "user_uuid"],
        unique=True,
        postgresql_where=sa.text("status NOT IN ('ERROR', 'TERMINATED', 'CANCELLED')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_sessions_unique_name_per_user_nonterminal",
        table_name="sessions",
        postgresql_where=sa.text("status NOT IN ('ERROR', 'TERMINATED', 'CANCELLED')"),
    )
    op.create_index(
        "ix_sessions_unique_name_nonterminal",
        "sessions",
        ["name"],
        unique=True,
        postgresql_where="((status)::text <> ALL ((ARRAY['ERROR'::character varying, 'TERMINATED'::character varying, 'CANCELLED'::character varying])::text[]))",
    )
    # ### end Alembic commands ###
