"""add_agent_abusing_report_col

Revision ID: b0004bcf6cdf
Revises: c53397a490be
Create Date: 2022-12-04 17:53:51.720409

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b0004bcf6cdf"
down_revision = "c53397a490be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("abuse_report_path", sa.String(length=128), nullable=True))
    op.add_column(
        "agents",
        sa.Column("auto_terminate", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "auto_terminate")
    op.drop_column("agents", "abuse_report_path")
    # ### end Alembic commands ###
