"""alter_unchanged_use_host_network_col

Revision ID: b39f0ac2e9ee
Revises: 213a04e90ecf
Create Date: 2022-12-05 16:26:46.059332

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b39f0ac2e9ee"
down_revision = "213a04e90ecf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scaling_groups",
        "use_host_network",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "scaling_groups",
        "use_host_network",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###
