"""Add artifact_registries table

Revision ID: ba5207c55924
Revises: 11ee5c074009
Create Date: 2025-08-26 06:29:20.265879

"""

import sqlalchemy as sa
from alembic import op

from ai.backend.manager.models.base import GUID

# revision identifiers, used by Alembic.
revision = "ba5207c55924"
down_revision = "11ee5c074009"
branch_labels = None
depends_on = None


# TODO: 데이터 마이그레이션 로직까지 넣어야 함.
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifact_registries",
        sa.Column("id", GUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("registry_id", GUID(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifact_registries")),
        sa.UniqueConstraint("name", name=op.f("uq_artifact_registries_name")),
        sa.UniqueConstraint("registry_id", name=op.f("uq_artifact_registries_registry_id")),
    )
    op.drop_constraint("uq_huggingface_registries_name", "huggingface_registries", type_="unique")
    op.drop_column("huggingface_registries", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "huggingface_registries",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint(
        "uq_huggingface_registries_name", "huggingface_registries", ["name"]
    )
    op.drop_table("artifact_registries")
    # ### end Alembic commands ###
