"""add_abusing_report_path_col_in_agent

Revision ID: c90040f108c0
Revises: 213a04e90ecf
Create Date: 2022-12-06 17:51:40.069859

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c90040f108c0"
down_revision = "213a04e90ecf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("abuse_report_path", sa.String(length=128), nullable=True))
    op.add_column(
        "agents",
        sa.Column("auto_terminate", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "auto_terminate")
    op.drop_column("agents", "abuse_report_path")
    # ### end Alembic commands ###
