"""change_kernel_requested_slot_not_nullable

Revision ID: d6a9f9b137e8
Revises: eb9441fcf90a
Create Date: 2023-08-10 10:40:01.977335

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "d6a9f9b137e8"
down_revision = "eb9441fcf90a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("kernels", "requested_slots", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("kernels", "requested_slots", nullable=True)
    # ### end Alembic commands ###
