"""Add storage_type column to reservoir_registries

Revision ID: e0cedd0e0cbe
Revises: de1032a11cca
Create Date: 2025-10-13 12:31:19.161776

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e0cedd0e0cbe"
down_revision = "de1032a11cca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservoir_registries",
        sa.Column("storage_type", sa.String(), nullable=False, server_default="object_storage"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reservoir_registries", "storage_type")
    # ### end Alembic commands ###
