"""add_allowed_ip_column

Revision ID: e12b7f360d42
Revises: 35923972eddb
Create Date: 2022-08-30 18:06:05.960652

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e12b7f360d42"
down_revision = "35923972eddb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("keypairs", sa.Column("allowed_client_ip", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("keypairs", "allowed_client_ip")
    # ### end Alembic commands ###
