"""substitue endpoints.project to groups.id

Revision ID: e5ca3c29c749
Revises: 1e653457d769
Create Date: 2023-02-16 19:53:48.408768

"""
import sqlalchemy as sa
from alembic import op

from ai.backend.manager.models.base import GUID

# revision identifiers, used by Alembic.
revision = "e5ca3c29c749"
down_revision = "1e653457d769"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("endpoints", sa.Column("project", GUID(), nullable=False))
    op.create_foreign_key(
        op.f("fk_endpoints_project_groups"),
        "endpoints",
        "groups",
        ["project"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_endpoints_project_groups"), "endpoints", type_="foreignkey")
    op.drop_column("endpoints", "project")
    # ### end Alembic commands ###
