"""add_scheduled_at

Revision ID: ecab6c18446f
Revises: 5fbd368d12a2
Create Date: 2023-06-19 14:42:08.987826

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ecab6c18446f"
down_revision = "5fbd368d12a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("kernels", sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_kernels_scheduled_at"), "kernels", ["scheduled_at"], unique=False)
    op.add_column("sessions", sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_sessions_scheduled_at"), "sessions", ["scheduled_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_scheduled_at"), table_name="sessions")
    op.drop_column("sessions", "scheduled_at")
    op.drop_index(op.f("ix_kernels_scheduled_at"), table_name="kernels")
    op.drop_column("kernels", "scheduled_at")
    # ### end Alembic commands ###
