"""add_auto_terminate_col

Revision ID: f87f5e2d3299
Revises: b6b884fbae1f
Create Date: 2023-02-03 18:45:16.597352

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f87f5e2d3299"
down_revision = "b6b884fbae1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column("auto_terminate", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "auto_terminate")
    # ### end Alembic commands ###
