"""
Scheduling history DTOs v2 for Manager API.
"""

from ai.backend.common.dto.manager.v2.scheduling_history.request import (
    AdminSearchDeploymentHistoriesInput,
    AdminSearchKernelHistoriesInput,
    AdminSearchRouteHistoriesInput,
    AdminSearchSessionHistoriesInput,
    DeploymentHistoryFilter,
    DeploymentHistoryOrder,
    KernelHistoryFilter,
    KernelHistoryOrder,
    RouteHistoryFilter,
    RouteHistoryOrder,
    ScopedSearchKernelHistoriesInput,
    SearchDeploymentHistoryInput,
    SearchRouteHistoryInput,
    SearchSessionHistoryInput,
    SessionHistoryFilter,
    SessionHistoryOrder,
)
from ai.backend.common.dto.manager.v2.scheduling_history.response import (
    AdminSearchDeploymentHistoriesPayload,
    AdminSearchKernelHistoriesPayload,
    AdminSearchRouteHistoriesPayload,
    AdminSearchSessionHistoriesPayload,
    DeploymentHistoryNode,
    KernelHistoryNode,
    ListDeploymentHistoryPayload,
    ListRouteHistoryPayload,
    ListSessionHistoryPayload,
    RouteHistoryNode,
    SessionHistoryNode,
)
from ai.backend.common.dto.manager.v2.scheduling_history.types import (
    DeploymentHistoryOrderField,
    DeploymentHistoryScopeDTO,
    KernelHistoryOrderField,
    KernelHistoryScopeDTO,
    OrderDirection,
    RouteHistoryOrderField,
    RouteHistoryScopeDTO,
    SchedulingResultType,
    SessionHistoryOrderField,
    SessionHistoryScopeDTO,
    SubStepResultInfo,
)

__all__ = (
    # Types
    "DeploymentHistoryOrderField",
    "DeploymentHistoryScopeDTO",
    "KernelHistoryOrderField",
    "KernelHistoryScopeDTO",
    "OrderDirection",
    "RouteHistoryOrderField",
    "RouteHistoryScopeDTO",
    "SchedulingResultType",
    "SessionHistoryOrderField",
    "SessionHistoryScopeDTO",
    "SubStepResultInfo",
    # Input models (request)
    "AdminSearchDeploymentHistoriesInput",
    "AdminSearchKernelHistoriesInput",
    "AdminSearchRouteHistoriesInput",
    "AdminSearchSessionHistoriesInput",
    "DeploymentHistoryFilter",
    "DeploymentHistoryOrder",
    "KernelHistoryFilter",
    "KernelHistoryOrder",
    "RouteHistoryFilter",
    "RouteHistoryOrder",
    "ScopedSearchKernelHistoriesInput",
    "SearchDeploymentHistoryInput",
    "SearchRouteHistoryInput",
    "SearchSessionHistoryInput",
    "SessionHistoryFilter",
    "SessionHistoryOrder",
    # Response models
    "AdminSearchDeploymentHistoriesPayload",
    "AdminSearchKernelHistoriesPayload",
    "AdminSearchRouteHistoriesPayload",
    "AdminSearchSessionHistoriesPayload",
    "DeploymentHistoryNode",
    "KernelHistoryNode",
    "ListDeploymentHistoryPayload",
    "ListRouteHistoryPayload",
    "ListSessionHistoryPayload",
    "RouteHistoryNode",
    "SessionHistoryNode",
)
