"""
Keypair DTOs v2 for Manager API.
"""

from ai.backend.common.dto.manager.v2.keypair.request import (
    AdminCreateKeypairInput,
    AdminDeleteKeypairInput,
    AdminDeleteSSHKeypairInput,
    AdminGetSSHKeypairInput,
    AdminRegisterSSHKeypairInput,
    AdminSearchKeypairsInput,
    AdminUpdateKeypairInput,
    KeypairFilter,
    KeypairOrderBy,
    RevokeMyKeypairInput,
    SearchMyKeypairsRequest,
    SwitchMyMainAccessKeyInput,
    UpdateMyKeypairInput,
)
from ai.backend.common.dto.manager.v2.keypair.response import (
    AdminCreateKeypairPayload,
    AdminDeleteKeypairPayload,
    AdminDeleteSSHKeypairPayload,
    AdminGetSSHKeypairPayload,
    AdminRegisterSSHKeypairPayload,
    AdminSearchKeypairsPayload,
    AdminUpdateKeypairPayload,
    IssueMyKeypairPayload,
    KeypairNode,
    RevokeMyKeypairPayload,
    SearchMyKeypairsPayload,
    SSHKeypairNode,
    SwitchMyMainAccessKeyPayload,
    UpdateMyKeypairPayload,
)
from ai.backend.common.dto.manager.v2.keypair.types import KeypairOrderField

__all__ = (
    "AdminCreateKeypairInput",
    "AdminCreateKeypairPayload",
    "AdminDeleteKeypairInput",
    "AdminDeleteKeypairPayload",
    "AdminDeleteSSHKeypairInput",
    "AdminDeleteSSHKeypairPayload",
    "AdminGetSSHKeypairInput",
    "AdminGetSSHKeypairPayload",
    "AdminRegisterSSHKeypairInput",
    "AdminRegisterSSHKeypairPayload",
    "AdminSearchKeypairsInput",
    "AdminSearchKeypairsPayload",
    "AdminUpdateKeypairInput",
    "AdminUpdateKeypairPayload",
    "IssueMyKeypairPayload",
    "KeypairFilter",
    "KeypairNode",
    "KeypairOrderBy",
    "KeypairOrderField",
    "RevokeMyKeypairInput",
    "RevokeMyKeypairPayload",
    "SearchMyKeypairsPayload",
    "SearchMyKeypairsRequest",
    "SSHKeypairNode",
    "SwitchMyMainAccessKeyInput",
    "SwitchMyMainAccessKeyPayload",
    "UpdateMyKeypairInput",
    "UpdateMyKeypairPayload",
)
