"""Generic services for ops-backed actions, replacing per-domain pass-through methods."""

from .service import (
    BatchPurgeService,
    BatchUpdateService,
    BulkDeleteService,
    BulkUpdateService,
    DeleteService,
    FieldCreateService,
    FieldPurgeService,
    GetService,
    GlobalBatchPurgeService,
    GlobalBatchUpdateService,
    GlobalCreateService,
    GlobalPurgeService,
    GlobalSearchService,
    LookupService,
    ScopedBulkCreateService,
    ScopedBulkPurgeService,
    ScopedCreateService,
    ScopedPurgeService,
    ScopedUpsertService,
    SearchService,
    UpdateService,
)

__all__ = (
    "BatchPurgeService",
    "BatchUpdateService",
    "ScopedBulkCreateService",
    "BulkDeleteService",
    "ScopedBulkPurgeService",
    "BulkUpdateService",
    "FieldCreateService",
    "FieldPurgeService",
    "GlobalBatchPurgeService",
    "GlobalBatchUpdateService",
    "GlobalCreateService",
    "ScopedCreateService",
    "DeleteService",
    "GetService",
    "GlobalSearchService",
    "LookupService",
    "GlobalPurgeService",
    "ScopedPurgeService",
    "SearchService",
    "UpdateService",
    "ScopedUpsertService",
)
