# https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
- name: 💬 Discussions
  url: https://github.com/lablup/backend.ai/discussions
  about: Please start usage discussions here
