python_test_utils(
    name="test_utils",
    sources=[
        "conftest.py",
        "fixtures.py",
        "utils.py",
    ],
)

python_tests(
    name="tests",
    dependencies=[
        "src/ai/backend/manager:src",
    ],
)
