import enum
import uuid
from typing import Any, Final, Mapping

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pgsql
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import relationship, selectinload
from sqlalchemy.orm.exc import NoResultFound

from ai.backend.manager.models.base import (
    GUID,
    Base,
    IDColumn,
    SlugType,
)

__all__: Final[tuple[str, ...]] = (
    "NetworkRow",
    "NetworkType",
)


class NetworkType(enum.StrEnum):
    VOLATILE = "volatile"
    PERSISTENT = "persistent"
    HOST = "host"


class NetworkRow(Base):
    __tablename__ = "networks"

    id = IDColumn()

    name = sa.Column("name", sa.String(length=128), nullable=False)
    """Name of the network"""
    ref_name = sa.Column("ref_name", sa.String(length=128), nullable=False)
    """Network ID generated by network plugin"""
    driver = sa.Column("driver", sa.String(length=64), nullable=False)
    """Network plugin in charge of the network created"""
    options = sa.Column("options", pgsql.JSONB, nullable=False, default="{}", server_default="{}")

    project = sa.Column(
        "project",
        GUID,
        nullable=False,
    )
    domain_name = sa.Column(
        "domain_name",
        SlugType(length=64, allow_unicode=True, allow_dot=True),
        nullable=False,
    )

    created_at = sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        nullable=True,
    )
    updated_at = sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        server_default=sa.text("now()"),
        nullable=True,
    )

    project_row = relationship(
        "GroupRow",
        back_populates="networks",
        primaryjoin="GroupRow.id==foreign(NetworkRow.project)",
    )
    domain_row = relationship(
        "DomainRow",
        back_populates="networks",
        primaryjoin="DomainRow.name==foreign(NetworkRow.domain_name)",
    )

    def __init__(
        self,
        name: str,
        ref_name: str,
        driver: str,
        domain: str,
        project: uuid.UUID,
        *,
        options: Mapping[str, Any] | None = None,
    ) -> None:
        self.id = uuid.uuid4()
        self.name = name
        self.ref_name = ref_name
        self.driver = driver
        self.domain_name = domain
        self.project = project
        self.options = options

    @classmethod
    async def get(
        cls,
        session: AsyncSession,
        network_id: uuid.UUID,
        load_project=False,
        load_domain=False,
    ) -> "NetworkRow":
        query = sa.select(NetworkRow).filter(NetworkRow.id == network_id)
        if load_project:
            query = query.options(selectinload(cls.project_row))
        if load_domain:
            query = query.options(selectinload(cls.domain_row))
        row = await session.scalar(query)
        if not row:
            raise NoResultFound

        return row
