"""
Resource slot DTOs v2 for Manager API.
"""

from ai.backend.common.dto.manager.v2.resource_slot.request import (
    AdminSearchAgentResourcesInput,
    AdminSearchResourceAllocationsInput,
    AdminSearchResourceSlotTypesInput,
    AgentResourceFilter,
    AgentResourceOrder,
    AllocatedResourceSlotFilter,
    AllocatedResourceSlotOrder,
    CreateResourceSlotTypeInput,
    PurgeResourceSlotTypeInput,
    ResourceAllocationFilter,
    ResourceAllocationOrder,
    ResourceSlotTypeFilter,
    ResourceSlotTypeOrder,
    SearchAllocatedResourceSlotsInput,
    UpdateResourceSlotTypeInput,
)
from ai.backend.common.dto.manager.v2.resource_slot.response import (
    ActiveResourceOverviewInfoDTO,
    AdminSearchAgentResourcesPayload,
    AdminSearchResourceAllocationsPayload,
    AdminSearchResourceSlotTypesPayload,
    AgentResourceNode,
    AllocatedResourceSlotNode,
    CreateResourceSlotTypePayload,
    PurgeResourceSlotTypePayload,
    ResourceAllocationNode,
    ResourceSlotTypeNode,
    SearchAllocatedResourceSlotsPayload,
    UpdateResourceSlotTypePayload,
)
from ai.backend.common.dto.manager.v2.resource_slot.types import (
    AgentResourceOrderField,
    AllocatedResourceSlotOrderField,
    NumberFormatInfo,
    NumberFormatInput,
    OrderDirection,
    ResourceAllocationOrderField,
    ResourceOptsDTOInput,
    ResourceOptsEntryDTO,
    ResourceSlotTypeOrderField,
    ServicePortEntryInfoDTO,
    ServicePortsInfoDTO,
)

__all__ = (
    # Types
    "AgentResourceOrderField",
    "AllocatedResourceSlotOrderField",
    "NumberFormatInfo",
    "NumberFormatInput",
    "OrderDirection",
    "ResourceAllocationOrderField",
    "ResourceOptsEntryDTO",
    "ResourceOptsDTOInput",
    "ResourceSlotTypeOrderField",
    "ServicePortEntryInfoDTO",
    "ServicePortsInfoDTO",
    # Request models
    "AdminSearchAgentResourcesInput",
    "AdminSearchResourceAllocationsInput",
    "AdminSearchResourceSlotTypesInput",
    "AgentResourceFilter",
    "AgentResourceOrder",
    "AllocatedResourceSlotFilter",
    "AllocatedResourceSlotOrder",
    "ResourceAllocationFilter",
    "ResourceAllocationOrder",
    "ResourceSlotTypeFilter",
    "CreateResourceSlotTypeInput",
    "PurgeResourceSlotTypeInput",
    "ResourceSlotTypeOrder",
    "SearchAllocatedResourceSlotsInput",
    "UpdateResourceSlotTypeInput",
    # Response models
    "ActiveResourceOverviewInfoDTO",
    "AdminSearchAgentResourcesPayload",
    "AdminSearchResourceAllocationsPayload",
    "AdminSearchResourceSlotTypesPayload",
    "AgentResourceNode",
    "AllocatedResourceSlotNode",
    "ResourceAllocationNode",
    "CreateResourceSlotTypePayload",
    "PurgeResourceSlotTypePayload",
    "ResourceSlotTypeNode",
    "SearchAllocatedResourceSlotsPayload",
    "UpdateResourceSlotTypePayload",
)
