{
 "title": "\bBackend.ai Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "component",
    "query": {
     "query": "label_values(up{job!=\"prometheus\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job!=\"prometheus\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "up time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "backendai_up_time", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "$component Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "component" },
  {
   "title": "Total API Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(backendai_api_request_count_total{job=\"$component\"}[1m])) by (method, endpoint, status_code)",
     "legendFormat": "{{method}} : {{endpoint}} / {{status_code}}"
    }
   ]
  },
  {
   "title": "API Failure Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(backendai_api_request_count_total{status_code=~\"4..|500\", job=\"$component\"}[1m])) by (method, endpoint, status_code)",
     "legendFormat": "{{method}} : {{endpoint}} / {{status_code}}"
    }
   ]
  },
  {
   "title": "API Request Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, endpoint) (increase(backendai_api_request_duration_sec_sum{job=\"$component\"}[1m])) \n/\nsum by (method, endpoint) (increase(backendai_api_request_duration_sec_count{job=\"$component\"}[1m]))",
     "legendFormat": "{{method}} : {{endpoint}}"
    }
   ]
  },
  {
   "title": "API Request Duration (P90, P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(backendai_api_request_duration_sec_bucket{job=\"$component\"}) by (le, method, endpoint))",
     "legendFormat": "P95 {{method}} : {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_api_request_duration_sec_bucket{job=\"$component\"}) by (le, method, endpoint))",
     "legendFormat": "P90 {{method}} : {{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Event Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(backendai_event_count_total{job=\"$component\"}[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Event Failure Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(backendai_event_failure_count{job=\"$component\"}[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Event Processing Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (event_type) (increase(backendai_event_processing_time_sec_sum{job=\"$component\"}[1m])) \n/\nsum by (event_type) (increase(backendai_event_processing_time_sec_count{job=\"$component\"}[1m]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Event Processing Duration (P90, P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(backendai_event_processing_time_sec_bucket{job=\"$component\"}) by (le, event_type))",
     "legendFormat": "P95 {{event_type}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_event_processing_time_sec_bucket{job=\"$component\"}) by (le, event_type))",
     "legendFormat": "P90 {{event_type}}"
    }
   ]
  },
  {
   "title": "Total BgTask Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(backendai_bgtask_count{job=\"$component\"}) by (task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Total BgTask Done Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(increase(backendai_bgtask_done_count_total{job=\"$component\"}[1m])) by (task_name, status)",
     "legendFormat": "{{task_name}} / {{status}}"
    }
   ]
  },
  {
   "title": "BgTask Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (task_name, status) (increase(backendai_bgtask_processing_time_sec_sum{job=\"$component\"}[1m])) \n/\nsum by (task_name, status) (increase(backendai_bgtask_processing_time_sec_count{job=\"$component\"}[1m]))",
     "legendFormat": "{{task_name}} / {{status}}"
    }
   ]
  },
  {
   "title": "BgTask Duration (P90, P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(backendai_bgtask_processing_time_sec_bucket{job=\"$component\"}) by (le, task_name, status))",
     "legendFormat": "P95 {{task_name}} / {{status}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_bgtask_processing_time_sec_bucket{job=\"$component\"}) by (le, task_name, status))",
     "legendFormat": "P90 {{task_name}} / {{status}}"
    }
   ]
  },
  {
   "title": "Coroutine count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "backendai_coroutines{job=\"$component\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}