{
 "title": "Backend.ai half Dashboard",
 "time": { "from": "now-20m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "services", "query": { "query": "label_values(up,service_group)" } }
  ]
 },
 "panels": [
  { "title": "$services Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "jobs" },
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{job=\"$services\", level!=\"INFO\"}"
    }
   ]
  },
  {
   "title": "Total API Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(backendai_api_request_count_total{service_group=\"$services\"}[5m])",
     "legendFormat": "{{method}} : {{endpoint}} / {{status_code}}"
    }
   ]
  },
  {
   "title": "API Failure Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(backendai_api_request_count_total{service_group=\"$services\", status_code=~\"4..|500\"}[5m])) by (method, endpoint, status_code)",
     "legendFormat": "{{method}} : {{endpoint}} / {{status_code}}"
    }
   ]
  },
  {
   "title": "API Request Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, endpoint) (increase(backendai_api_request_duration_sec_sum{service_group=\"$services\"}[5m])) \n/\nsum by (method, endpoint) (increase(backendai_api_request_duration_sec_count{service_group=\"$services\"}[5m]))",
     "legendFormat": "{{method}} : {{endpoint}}"
    }
   ]
  },
  {
   "title": "API Request Duration (P90, P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(backendai_api_request_duration_sec_bucket{service_group=\"$services\"}) by (le, method, endpoint))",
     "legendFormat": "P95 {{method}} : {{endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_api_request_duration_sec_bucket{service_group=\"$services\"}) by (le, method, endpoint))",
     "legendFormat": "P90 {{method}} : {{endpoint}}"
    }
   ]
  },
  {
   "title": "Total GraphQL Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(backendai_graphql_request_count_total{service_group=\"$services\", success=\"True\"}[5m])",
     "legendFormat": "{{parent_type}} / {{operation_type}} / {{operation_name}} / {{field_name}} : Success"
    },
    {
     "expr": "increase(backendai_graphql_request_count_total{service_group=\"$services\", success=\"False\"}[5m])",
     "legendFormat": "{{parent_type}} / {{operation_type}} / {{operation_name}} / {{field_name}} : Failed"
    }
   ]
  },
  {
   "title": "GraphQL Failure Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(backendai_graphql_request_count_total{service_group=\"$services\", success=\"False\"}[5m])) by (parent_type, operation_type, operation_name, field_name)",
     "legendFormat": "{{parent_type}} / {{operation_type}} / {{operation_name}} / {{field_name}} : Success"
    }
   ]
  },
  {
   "title": "GraphQL Request Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (parent_type, operation_type, operation_name, field_name) (increase(backendai_graphql_request_duration_sec_sum{service_group=\"$services\", success=\"True\"}[5m])) \n/\nsum by (parent_type, operation_type, operation_name, field_name) (increase(backendai_graphql_request_duration_sec_count{service_group=\"$services\", success=\"True\"}[5m]))",
     "legendFormat": "{{parent_type}} / {{operation_type}} / {{operation_name}} / {{field_name}} : Success"
    },
    {
     "expr": "sum by (parent_type, operation_type, operation_name, field_name) (increase(backendai_graphql_request_duration_sec_sum{service_group=\"$services\", success=\"False\"}[5m])) \n/\nsum by (parent_type, operation_type, operation_name, field_name) (increase(backendai_graphql_request_duration_sec_count{service_group=\"$services\", success=\"False\"}[5m]))",
     "legendFormat": "{{parent_type}} / {{operation_type}} / {{operation_name}} / {{field_name}} : Fail"
    }
   ]
  },
  {
   "title": "GraphQL Request Duration (P90, P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(backendai_graphql_request_duration_sec_bucket{service_group=\"$services\", success=\"True\"}) by (le, parent_type, operation_type, operation_name, field_name))",
     "legendFormat": "P95 {{parent_type}} / {{operation_type}} / {{operation_name}} / {{field_name}} : Success"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_graphql_request_duration_sec_bucket{service_group=\"$services\", success=\"True\"}) by (le, parent_type, operation_type, operation_name, field_name))",
     "legendFormat": "P90 {{parent_type}} / {{operation_type}} / {{operation_name}} / {{field_name}} : Success"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_graphql_request_duration_sec_bucket{service_group=\"$services\", success=\"False\"}) by (le, parent_type, operation_type, operation_name, field_name))",
     "legendFormat": "P95 {{parent_type}} / {{operation_type}} / {{operation_name}} / {{field_name}} : Fail"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_graphql_request_duration_sec_bucket{service_group=\"$services\", success=\"False\"}) by (le, parent_type, operation_type, operation_name, field_name))",
     "legendFormat": "P90 {{parent_type}} / {{operation_type}} / {{operation_name}} / {{field_name}} : Fail"
    }
   ]
  },
  {
   "title": "Total Event Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(backendai_event_count_total{service_group=\"$services\"}[5m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Event Failure Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(backendai_event_failure_count{service_group=\"$services\"}[5m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Event Processing Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (event_type) (increase(backendai_event_processing_time_sec_sum{service_group=\"$services\"}[5m])) \n/\nsum by (event_type) (increase(backendai_event_processing_time_sec_count{service_group=\"$services\"}[5m]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Event Processing Duration (P90, P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(backendai_event_processing_time_sec_bucket{service_group=\"$services\"}) by (le, event_type))",
     "legendFormat": "P95 {{event_type}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_event_processing_time_sec_bucket{service_group=\"$services\"}) by (le, event_type))",
     "legendFormat": "P90 {{event_type}}"
    }
   ]
  },
  {
   "title": "Total BgTask Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(backendai_bgtask_count{service_group=\"$services\"}) by (task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Total BgTask Done Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(backendai_bgtask_done_count_total{service_group=\"$services\"}[5m])) by (task_name, status)",
     "legendFormat": "{{task_name}} / {{status}}"
    }
   ]
  },
  {
   "title": "BgTask Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (task_name, status) (increase(backendai_bgtask_processing_time_sec_sum{service_group=\"$services\"}[5m])) \n/\nsum by (task_name, status) (increase(backendai_bgtask_processing_time_sec_count{service_group=\"$services\"}[5m]))",
     "legendFormat": "{{task_name}} / {{status}}"
    }
   ]
  },
  {
   "title": "BgTask Duration (P90, P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(backendai_bgtask_processing_time_sec_bucket{service_group=\"$services\"}) by (le, task_name, status))",
     "legendFormat": "P95 {{task_name}} / {{status}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_bgtask_processing_time_sec_bucket{service_group=\"$services\"}) by (le, task_name, status))",
     "legendFormat": "P90 {{task_name}} / {{status}}"
    }
   ]
  },
  {
   "title": "Total RPC Call Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(backendai_rpc_requests_total{service_group=\"$services\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Total RPC Call Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(backendai_rpc_failure_requests_total{service_group=\"$services\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC Call Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method, endpoint) (increase(backendai_rpc_request_duration_seconds_sum{service_group=\"$services\"}[5m])) \n/\nsum by (method, endpoint) (increase(backendai_rpc_request_duration_seconds_count{service_group=\"$services\"}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC Call Duration (P95, P90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(backendai_rpc_request_duration_seconds_bucket{service_group=\"$services\"}) by (le, method))",
     "legendFormat": "P95 {{method}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(backendai_rpc_request_duration_seconds_bucket{service_group=\"$services\"}) by (le, method))",
     "legendFormat": "P90 {{method}}"
    }
   ]
  },
  {
   "title": "Async Task Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "backendai_async_task_count{service_group=\"$services\"}",
     "legendFormat": "{{service_group}}"
    }
   ]
  },
  {
   "title": "CPU Profile",
   "type": "flamegraph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "labelSelector": "{service_name=~\".*$services\"}",
     "legendFormat": "__auto",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "labelSelector": "{service_name=~\".*$services\"}",
     "legendFormat": "__auto",
     "profileTypeId": "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
    }
   ]
  },
  {
   "title": "CPU Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "backendai_cpu_usage_percent{service_group=\"$services\"}",
     "legendFormat": "{{service_group}}"
    }
   ]
  },
  {
   "title": "Memory Usage (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "backendai_memory_used_rss{service_group=\"$services\"}",
     "legendFormat": "{{service_group}}"
    }
   ]
  },
  {
   "title": "Memory Usage (VMS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "backendai_memory_used_vms{service_group=\"$services\"}",
     "legendFormat": "{{service_group}}"
    }
   ]
  }
 ]
}