# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/backend/agent/containerd/_grpcapi/api/services/events/v1/events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai/backend/agent/containerd/_grpcapi/api/services/events/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.backend.agent.containerd._grpcapi.protobuf.plugin import fieldpath_pb2 as ai_dot_backend_dot_agent_dot_containerd_dot___grpcapi_dot_protobuf_dot_plugin_dot_fieldpath__pb2
from ai.backend.agent.containerd._grpcapi.gogoproto import gogo_pb2 as ai_dot_backend_dot_agent_dot_containerd_dot___grpcapi_dot_gogoproto_dot_gogo__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHai/backend/agent/containerd/_grpcapi/api/services/events/v1/events.proto\x12\x1d\x63ontainerd.services.events.v1\x1a\x44\x61i/backend/agent/containerd/_grpcapi/protobuf/plugin/fieldpath.proto\x1a\x39\x61i/backend/agent/containerd/_grpcapi/gogoproto/gogo.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12#\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"K\n\x0e\x46orwardRequest\x12\x39\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32\'.containerd.services.events.v1.Envelope\"#\n\x10SubscribeRequest\x12\x0f\n\x07\x66ilters\x18\x01 \x03(\t\"\x90\x01\n\x08\x45nvelope\x12\x37\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\xc8\xde\x1f\x00\x90\xdf\x1f\x01\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\r\n\x05topic\x18\x03 \x01(\t\x12#\n\x05\x65vent\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any:\x04\x80\xb9\x1f\x01\x32\x95\x02\n\x06\x45vents\x12P\n\x07Publish\x12-.containerd.services.events.v1.PublishRequest\x1a\x16.google.protobuf.Empty\x12P\n\x07\x46orward\x12-.containerd.services.events.v1.ForwardRequest\x1a\x16.google.protobuf.Empty\x12g\n\tSubscribe\x12/.containerd.services.events.v1.SubscribeRequest\x1a\'.containerd.services.events.v1.Envelope0\x01\x42@Z>github.com/containerd/containerd/api/services/events/v1;eventsX\x00X\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.backend.agent.containerd._grpcapi.api.services.events.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z>github.com/containerd/containerd/api/services/events/v1;events'
  _globals['_ENVELOPE'].fields_by_name['timestamp']._loaded_options = None
  _globals['_ENVELOPE'].fields_by_name['timestamp']._serialized_options = b'\310\336\037\000\220\337\037\001'
  _globals['_ENVELOPE']._loaded_options = None
  _globals['_ENVELOPE']._serialized_options = b'\200\271\037\001'
  _globals['_PUBLISHREQUEST']._serialized_start=325
  _globals['_PUBLISHREQUEST']._serialized_end=393
  _globals['_FORWARDREQUEST']._serialized_start=395
  _globals['_FORWARDREQUEST']._serialized_end=470
  _globals['_SUBSCRIBEREQUEST']._serialized_start=472
  _globals['_SUBSCRIBEREQUEST']._serialized_end=507
  _globals['_ENVELOPE']._serialized_start=510
  _globals['_ENVELOPE']._serialized_end=654
  _globals['_EVENTS']._serialized_start=657
  _globals['_EVENTS']._serialized_end=934
# @@protoc_insertion_point(module_scope)
