# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/backend/agent/containerd/_grpcapi/api/services/diff/v1/diff.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai/backend/agent/containerd/_grpcapi/api/services/diff/v1/diff.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.backend.agent.containerd._grpcapi.gogoproto import gogo_pb2 as ai_dot_backend_dot_agent_dot_containerd_dot___grpcapi_dot_gogoproto_dot_gogo__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from ai.backend.agent.containerd._grpcapi.api.types import mount_pb2 as ai_dot_backend_dot_agent_dot_containerd_dot___grpcapi_dot_api_dot_types_dot_mount__pb2
from ai.backend.agent.containerd._grpcapi.api.types import descriptor_pb2 as ai_dot_backend_dot_agent_dot_containerd_dot___grpcapi_dot_api_dot_types_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDai/backend/agent/containerd/_grpcapi/api/services/diff/v1/diff.proto\x12\x1b\x63ontainerd.services.diff.v1\x1a\x39\x61i/backend/agent/containerd/_grpcapi/gogoproto/gogo.proto\x1a\x19google/protobuf/any.proto\x1a:ai/backend/agent/containerd/_grpcapi/api/types/mount.proto\x1a?ai/backend/agent/containerd/_grpcapi/api/types/descriptor.proto\"\xf5\x01\n\x0c\x41pplyRequest\x12*\n\x04\x64iff\x18\x01 \x01(\x0b\x32\x1c.containerd.types.Descriptor\x12\'\n\x06mounts\x18\x02 \x03(\x0b\x32\x17.containerd.types.Mount\x12I\n\x08payloads\x18\x03 \x03(\x0b\x32\x37.containerd.services.diff.v1.ApplyRequest.PayloadsEntry\x1a\x45\n\rPayloadsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\">\n\rApplyResponse\x12-\n\x07\x61pplied\x18\x01 \x01(\x0b\x32\x1c.containerd.types.Descriptor\"\xf2\x01\n\x0b\x44iffRequest\x12%\n\x04left\x18\x01 \x03(\x0b\x32\x17.containerd.types.Mount\x12&\n\x05right\x18\x02 \x03(\x0b\x32\x17.containerd.types.Mount\x12\x12\n\nmedia_type\x18\x03 \x01(\t\x12\x0b\n\x03ref\x18\x04 \x01(\t\x12\x44\n\x06labels\x18\x05 \x03(\x0b\x32\x34.containerd.services.diff.v1.DiffRequest.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\":\n\x0c\x44iffResponse\x12*\n\x04\x64iff\x18\x03 \x01(\x0b\x32\x1c.containerd.types.Descriptor2\xc3\x01\n\x04\x44iff\x12^\n\x05\x41pply\x12).containerd.services.diff.v1.ApplyRequest\x1a*.containerd.services.diff.v1.ApplyResponse\x12[\n\x04\x44iff\x12(.containerd.services.diff.v1.DiffRequest\x1a).containerd.services.diff.v1.DiffResponseB<Z:github.com/containerd/containerd/api/services/diff/v1;diffX\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.backend.agent.containerd._grpcapi.api.services.diff.v1.diff_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/containerd/containerd/api/services/diff/v1;diff'
  _globals['_APPLYREQUEST_PAYLOADSENTRY']._loaded_options = None
  _globals['_APPLYREQUEST_PAYLOADSENTRY']._serialized_options = b'8\001'
  _globals['_DIFFREQUEST_LABELSENTRY']._loaded_options = None
  _globals['_DIFFREQUEST_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_APPLYREQUEST']._serialized_start=313
  _globals['_APPLYREQUEST']._serialized_end=558
  _globals['_APPLYREQUEST_PAYLOADSENTRY']._serialized_start=489
  _globals['_APPLYREQUEST_PAYLOADSENTRY']._serialized_end=558
  _globals['_APPLYRESPONSE']._serialized_start=560
  _globals['_APPLYRESPONSE']._serialized_end=622
  _globals['_DIFFREQUEST']._serialized_start=625
  _globals['_DIFFREQUEST']._serialized_end=867
  _globals['_DIFFREQUEST_LABELSENTRY']._serialized_start=822
  _globals['_DIFFREQUEST_LABELSENTRY']._serialized_end=867
  _globals['_DIFFRESPONSE']._serialized_start=869
  _globals['_DIFFRESPONSE']._serialized_end=927
  _globals['_DIFF']._serialized_start=930
  _globals['_DIFF']._serialized_end=1125
# @@protoc_insertion_point(module_scope)
