receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 15s
    send_batch_size: 512

exporters:
  loki:
    endpoint: http://backendai-half-loki:3100/loki/api/v1/push
  otlp/tempo:
    endpoint: http://backendai-half-tempo:4317
    tls:
      insecure: true
      insecure_skip_verify: true 

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
