python_test_utils(
    dependencies=[
        "//:reqs#authlib",  # pants: no-infer-dep in conftest.py
    ],
)

python_tests(
    name="tests",
    dependencies=[
        "//:reqs#authlib",  # pants: no-infer-dep in conftest.py
    ],
)
