"""
Session DTOs v2 for Manager API.
"""

from ai.backend.common.dto.manager.v2.session.request import (
    AdminSearchSessionsInput,
    CommitSessionInput,
    DestroySessionInput,
    DownloadFilesInput,
    ExecuteInput,
    GetContainerLogsInput,
    ListFilesInput,
    RenameSessionInput,
    RestartSessionInput,
    SearchSessionsInput,
    SessionFilter,
    SessionIdPathParam,
    SessionOrder,
    SessionPathParam,
    ShutdownServiceInput,
    StartServiceInput,
    TerminateSessionsInProjectInput,
    UploadFilesInput,
)
from ai.backend.common.dto.manager.v2.session.response import (
    AdminSearchSessionsPayload,
    CommitSessionPayload,
    DestroySessionPayload,
    ExecutePayload,
    RestartSessionPayload,
    SearchSessionsPayload,
    SessionLifecycleInfo,
    SessionMetadataInfo,
    SessionNetworkInfo,
    SessionNode,
    SessionResourceInfo,
    SessionRuntimeInfo,
    StartServicePayload,
)
from ai.backend.common.dto.manager.v2.session.types import (
    OrderDirection,
    ProjectSessionScope,
    SessionOrderField,
    SessionResultEnum,
    SessionStatusEnum,
    SessionStatusFilter,
    SessionTypeEnum,
)

__all__ = (
    # Types
    "OrderDirection",
    "ProjectSessionScope",
    "SessionOrderField",
    "SessionResultEnum",
    "SessionStatusEnum",
    "SessionStatusFilter",
    "SessionTypeEnum",
    # Input models (request)
    "AdminSearchSessionsInput",
    "CommitSessionInput",
    "DestroySessionInput",
    "DownloadFilesInput",
    "ExecuteInput",
    "GetContainerLogsInput",
    "ListFilesInput",
    "RenameSessionInput",
    "RestartSessionInput",
    "SearchSessionsInput",
    "SessionFilter",
    "SessionIdPathParam",
    "SessionOrder",
    "SessionPathParam",
    "ShutdownServiceInput",
    "StartServiceInput",
    "TerminateSessionsInProjectInput",
    "UploadFilesInput",
    # Node and Payload models (response)
    "AdminSearchSessionsPayload",
    "CommitSessionPayload",
    "DestroySessionPayload",
    "ExecutePayload",
    "RestartSessionPayload",
    "SearchSessionsPayload",
    "SessionLifecycleInfo",
    "SessionMetadataInfo",
    "SessionNetworkInfo",
    "SessionNode",
    "SessionResourceInfo",
    "SessionRuntimeInfo",
    "StartServicePayload",
)
