from .mutation import (
    admin_create_keypair_resource_policy_v2,
    admin_create_project_resource_policy_v2,
    admin_create_user_resource_policy_v2,
    admin_delete_keypair_resource_policy_v2,
    admin_delete_project_resource_policy_v2,
    admin_delete_user_resource_policy_v2,
    admin_update_keypair_resource_policy_v2,
    admin_update_project_resource_policy_v2,
    admin_update_user_resource_policy_v2,
)
from .query import (
    admin_keypair_resource_policies_v2,
    admin_keypair_resource_policy_v2,
    admin_project_resource_policies_v2,
    admin_project_resource_policy_v2,
    admin_user_resource_policies_v2,
    admin_user_resource_policy_v2,
    my_keypair_resource_policy_v2,
    my_user_resource_policy_v2,
)

__all__ = (
    "admin_create_keypair_resource_policy_v2",
    "admin_create_project_resource_policy_v2",
    "admin_create_user_resource_policy_v2",
    "admin_delete_keypair_resource_policy_v2",
    "admin_delete_project_resource_policy_v2",
    "admin_delete_user_resource_policy_v2",
    "admin_keypair_resource_policies_v2",
    "admin_keypair_resource_policy_v2",
    "admin_project_resource_policies_v2",
    "admin_project_resource_policy_v2",
    "admin_update_keypair_resource_policy_v2",
    "admin_update_project_resource_policy_v2",
    "admin_update_user_resource_policy_v2",
    "admin_user_resource_policies_v2",
    "admin_user_resource_policy_v2",
    "my_keypair_resource_policy_v2",
    "my_user_resource_policy_v2",
)
