"""
Artifact DTOs v2 for Manager API.
"""

from ai.backend.common.dto.manager.v2.artifact.request import (
    AdminSearchArtifactsInput,
    ArtifactFilter,
    ArtifactOrder,
    CancelImportTaskInput,
    CleanupRevisionsInput,
    DelegateeTargetInput,
    DelegateImportArtifactsInput,
    DelegateScanArtifactsInput,
    DeleteArtifactsInput,
    ImportArtifactsInput,
    ImportArtifactsOptionsInput,
    ModelTargetInput,
    ScanArtifactModelsInput,
    ScanArtifactsInput,
    UpdateArtifactInput,
)
from ai.backend.common.dto.manager.v2.artifact.response import (
    AdminSearchArtifactsPayload,
    ApproveRevisionPayload,
    ArtifactNode,
    ArtifactRevisionImportTaskInfo,
    ArtifactRevisionNode,
    CancelImportTaskPayload,
    CleanupRevisionsPayload,
    DeleteArtifactsPayload,
    GetRevisionDownloadProgressPayload,
    GetRevisionReadmePayload,
    GetRevisionVerificationResultPayload,
    ImportArtifactsPayload,
    RejectRevisionPayload,
    UpdateArtifactPayload,
)
from ai.backend.common.dto.manager.v2.artifact.types import (
    ArtifactAvailability,
    ArtifactAvailabilityFilter,
    ArtifactOrderField,
    ArtifactRegistryType,
    ArtifactRevisionInfo,
    ArtifactRevisionOrderField,
    ArtifactStatus,
    ArtifactType,
    ArtifactTypeFilter,
    CombinedDownloadProgress,
    OrderDirection,
    VerificationStepResult,
)

__all__ = (
    # Types
    "ArtifactAvailability",
    "ArtifactAvailabilityFilter",
    "ArtifactOrderField",
    "ArtifactRegistryType",
    "ArtifactRevisionInfo",
    "ArtifactRevisionOrderField",
    "ArtifactStatus",
    "ArtifactType",
    "ArtifactTypeFilter",
    "CombinedDownloadProgress",
    "OrderDirection",
    "VerificationStepResult",
    # Input models (request)
    "AdminSearchArtifactsInput",
    "ArtifactFilter",
    "ArtifactOrder",
    "CancelImportTaskInput",
    "CleanupRevisionsInput",
    "DeleteArtifactsInput",
    "DelegateeTargetInput",
    "DelegateImportArtifactsInput",
    "DelegateScanArtifactsInput",
    "ImportArtifactsInput",
    "ImportArtifactsOptionsInput",
    "ModelTargetInput",
    "ScanArtifactModelsInput",
    "ScanArtifactsInput",
    "UpdateArtifactInput",
    # Node and Payload models (response)
    "AdminSearchArtifactsPayload",
    "ArtifactNode",
    "ArtifactRevisionImportTaskInfo",
    "ArtifactRevisionNode",
    "ApproveRevisionPayload",
    "CancelImportTaskPayload",
    "CleanupRevisionsPayload",
    "DeleteArtifactsPayload",
    "GetRevisionDownloadProgressPayload",
    "GetRevisionReadmePayload",
    "GetRevisionVerificationResultPayload",
    "ImportArtifactsPayload",
    "RejectRevisionPayload",
    "UpdateArtifactPayload",
)
