"""
RBAC DTOs v2 for Manager API.
"""

from ai.backend.common.dto.manager.v2.rbac.request import (
    AdminSearchEntitiesGQLInput,
    AdminSearchPermissionsGQLInput,
    AdminSearchRoleAssignmentsGQLInput,
    AdminSearchRolesGQLInput,
    AssignRoleInput,
    BulkAssignRoleInput,
    BulkRevokeRoleInput,
    CreatePermissionInput,
    CreateRoleInput,
    DeletePermissionInput,
    DeleteRoleInput,
    EntityFilter,
    EntityOrderBy,
    PermissionFilter,
    PermissionOrderBy,
    PurgeRoleInput,
    RevokeRoleInput,
    RoleAssignmentFilter,
    RoleAssignmentOrderBy,
    RoleFilter,
    RoleNestedFilter,
    RoleOrderBy,
    UpdatePermissionInput,
    UpdateRoleInput,
)
from ai.backend.common.dto.manager.v2.rbac.response import (
    CreateRolePayload,
    DeletePermissionPayload,
    DeleteRolePayload,
    PurgeRolePayload,
    RoleNode,
    UpdateRolePayload,
)
from ai.backend.common.dto.manager.v2.rbac.types import (
    EntityOrderField,
    EntityType,
    EntityTypeFilter,
    OperationType,
    OrderDirection,
    PermissionOrderField,
    PermissionSummary,
    RoleAssignmentOrderField,
    RoleOrderField,
    RoleSource,
    RoleSourceFilter,
    RoleStatus,
    RoleStatusFilter,
)

__all__ = (
    # Types
    "EntityOrderField",
    "EntityType",
    "EntityTypeFilter",
    "OperationType",
    "OrderDirection",
    "PermissionOrderField",
    "PermissionSummary",
    "RoleAssignmentOrderField",
    "RoleOrderField",
    "RoleSource",
    "RoleSourceFilter",
    "RoleStatus",
    "RoleStatusFilter",
    # Input models (request)
    "AdminSearchEntitiesGQLInput",
    "AdminSearchPermissionsGQLInput",
    "AdminSearchRoleAssignmentsGQLInput",
    "AdminSearchRolesGQLInput",
    "AssignRoleInput",
    "BulkAssignRoleInput",
    "BulkRevokeRoleInput",
    "CreatePermissionInput",
    "CreateRoleInput",
    "DeletePermissionInput",
    "DeleteRoleInput",
    "EntityFilter",
    "EntityOrderBy",
    "PermissionFilter",
    "PermissionOrderBy",
    "PurgeRoleInput",
    "RevokeRoleInput",
    "RoleAssignmentFilter",
    "RoleAssignmentOrderBy",
    "RoleFilter",
    "RoleNestedFilter",
    "RoleOrderBy",
    "UpdatePermissionInput",
    "UpdateRoleInput",
    # Node and Payload models (response)
    "CreateRolePayload",
    "DeletePermissionPayload",
    "DeleteRolePayload",
    "PurgeRolePayload",
    "RoleNode",
    "UpdateRolePayload",
)
