"""GraphQL notification module."""

from .resolver import (
    admin_create_notification_channel,
    admin_create_notification_rule,
    admin_delete_notification_channel,
    admin_delete_notification_rule,
    admin_notification_channel,
    admin_notification_channels,
    admin_notification_rule,
    admin_notification_rules,
    admin_update_notification_channel,
    admin_update_notification_rule,
    admin_validate_notification_channel,
    admin_validate_notification_rule,
    create_notification_channel,
    create_notification_rule,
    delete_notification_channel,
    delete_notification_rule,
    notification_channel,
    notification_channels,
    notification_rule,
    notification_rule_types,
    notification_rules,
    update_notification_channel,
    update_notification_rule,
    validate_notification_channel,
    validate_notification_rule,
)
from .types import (
    CreateNotificationChannelInput,
    CreateNotificationChannelPayload,
    CreateNotificationRuleInput,
    CreateNotificationRulePayload,
    DeleteNotificationChannelInput,
    DeleteNotificationChannelPayload,
    DeleteNotificationRuleInput,
    DeleteNotificationRulePayload,
    NotificationChannel,
    NotificationChannelFilter,
    NotificationChannelOrderBy,
    NotificationRule,
    NotificationRuleFilter,
    NotificationRuleOrderBy,
    UpdateNotificationChannelInput,
    UpdateNotificationChannelPayload,
    UpdateNotificationRuleInput,
    UpdateNotificationRulePayload,
    ValidateNotificationChannelInput,
    ValidateNotificationChannelPayload,
    ValidateNotificationRuleInput,
    ValidateNotificationRulePayload,
)

__all__ = (
    # Types
    "NotificationChannel",
    "NotificationRule",
    "NotificationChannelFilter",
    "NotificationChannelOrderBy",
    "NotificationRuleFilter",
    "NotificationRuleOrderBy",
    "CreateNotificationChannelInput",
    "CreateNotificationChannelPayload",
    "UpdateNotificationChannelInput",
    "UpdateNotificationChannelPayload",
    "DeleteNotificationChannelInput",
    "DeleteNotificationChannelPayload",
    "CreateNotificationRuleInput",
    "CreateNotificationRulePayload",
    "UpdateNotificationRuleInput",
    "UpdateNotificationRulePayload",
    "DeleteNotificationRuleInput",
    "DeleteNotificationRulePayload",
    "ValidateNotificationChannelInput",
    "ValidateNotificationChannelPayload",
    "ValidateNotificationRuleInput",
    "ValidateNotificationRulePayload",
    # Query Resolvers - Admin
    "admin_notification_channel",
    "admin_notification_channels",
    "admin_notification_rule",
    "admin_notification_rules",
    # Mutation Resolvers - Admin
    "admin_create_notification_channel",
    "admin_update_notification_channel",
    "admin_delete_notification_channel",
    "admin_validate_notification_channel",
    "admin_create_notification_rule",
    "admin_update_notification_rule",
    "admin_delete_notification_rule",
    "admin_validate_notification_rule",
    # Query Resolvers - Legacy (deprecated)
    "notification_channel",
    "notification_channels",
    "notification_rule",
    "notification_rules",
    "notification_rule_types",
    # Mutation Resolvers - Legacy (deprecated)
    "create_notification_channel",
    "update_notification_channel",
    "delete_notification_channel",
    "create_notification_rule",
    "update_notification_rule",
    "delete_notification_rule",
    "validate_notification_channel",
    "validate_notification_rule",
)
