"""add auto_created field to static_addresses

Revision ID: dcf5296f1919
Revises: f3a2d8e9c1b0
Create Date: 2025-07-14 11:26:28.498729

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dcf5296f1919"
down_revision = "f3a2d8e9c1b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "static_addresses",
        sa.Column("auto_created", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("static_addresses", "auto_created")
    # ### end Alembic commands ###
