# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/backend/agent/containerd/_grpcapi/api/types/platform.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai/backend/agent/containerd/_grpcapi/api/types/platform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.backend.agent.containerd._grpcapi.gogoproto import gogo_pb2 as ai_dot_backend_dot_agent_dot_containerd_dot___grpcapi_dot_gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=ai/backend/agent/containerd/_grpcapi/api/types/platform.proto\x12\x10\x63ontainerd.types\x1a\x39\x61i/backend/agent/containerd/_grpcapi/gogoproto/gogo.proto\"E\n\x08Platform\x12\x12\n\x02os\x18\x01 \x01(\tB\x06\xe2\xde\x1f\x02OS\x12\x14\n\x0c\x61rchitecture\x18\x02 \x01(\t\x12\x0f\n\x07variant\x18\x03 \x01(\tB2Z0github.com/containerd/containerd/api/types;typesX\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.backend.agent.containerd._grpcapi.api.types.platform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/containerd/containerd/api/types;types'
  _globals['_PLATFORM'].fields_by_name['os']._loaded_options = None
  _globals['_PLATFORM'].fields_by_name['os']._serialized_options = b'\342\336\037\002OS'
  _globals['_PLATFORM']._serialized_start=142
  _globals['_PLATFORM']._serialized_end=211
# @@protoc_insertion_point(module_scope)
