from __future__ import annotations

from .resolver import (
    admin_assign_role,
    admin_create_permission,
    admin_create_role,
    admin_delete_permission,
    admin_delete_role,
    admin_entities,
    admin_permissions,
    admin_purge_role,
    admin_revoke_role,
    admin_role,
    admin_role_assignments,
    admin_roles,
    admin_update_role,
)
from .types import (
    AssignRoleInput,
    CreatePermissionInput,
    CreateRoleInput,
    EntityConnection,
    EntityFilter,
    EntityOrderBy,
    EntityRefGQL,
    OperationTypeGQL,
    PermissionConnection,
    PermissionFilter,
    PermissionGQL,
    PermissionOrderBy,
    RBACElementTypeGQL,
    RevokeRoleInput,
    RoleAssignmentConnection,
    RoleAssignmentFilter,
    RoleAssignmentGQL,
    RoleConnection,
    RoleFilter,
    RoleGQL,
    RoleOrderBy,
    RoleSourceGQL,
    RoleStatusGQL,
    UpdateRoleInput,
)

__all__ = (
    # Enums
    "RBACElementTypeGQL",
    "OperationTypeGQL",
    "RoleSourceGQL",
    "RoleStatusGQL",
    # Types
    "RoleGQL",
    "PermissionGQL",
    "RoleAssignmentGQL",
    "EntityRefGQL",
    # Filters
    "RoleFilter",
    "PermissionFilter",
    "RoleAssignmentFilter",
    "EntityFilter",
    # OrderBy
    "RoleOrderBy",
    "PermissionOrderBy",
    "EntityOrderBy",
    # Inputs
    "CreateRoleInput",
    "UpdateRoleInput",
    "CreatePermissionInput",
    "AssignRoleInput",
    "RevokeRoleInput",
    # Connections
    "RoleConnection",
    "PermissionConnection",
    "RoleAssignmentConnection",
    "EntityConnection",
    # Query resolvers
    "admin_role",
    "admin_roles",
    "admin_permissions",
    "admin_role_assignments",
    "admin_entities",
    # Mutation resolvers
    "admin_create_role",
    "admin_update_role",
    "admin_delete_role",
    "admin_purge_role",
    "admin_create_permission",
    "admin_delete_permission",
    "admin_assign_role",
    "admin_revoke_role",
)
