from __future__ import annotations

from .resolver import (
    accept_role_invitation,
    admin_assign_role,
    admin_bulk_assign_role,
    admin_bulk_revoke_role,
    admin_cancel_role_invitation,
    admin_create_permission,
    admin_create_role,
    admin_delete_permission,
    admin_delete_role,
    admin_entities,
    admin_permissions,
    admin_purge_role,
    admin_resolve_effective_permissions,
    admin_revoke_role,
    admin_role,
    admin_role_assignments,
    admin_role_invitations,
    admin_roles,
    admin_update_permission,
    admin_update_role,
    create_role_invitation,
    my_effective_permissions,
    my_role_invitations,
    my_roles,
    project_roles,
    rbac_entity_operation_combinations,
    rbac_permission_matrix,
    rbac_scope_entity_combinations,
    reject_role_invitation,
    role_scoped_role_invitations,
)
from .types import (
    AssignRoleInput,
    BulkAssignRoleInputGQL,
    BulkAssignRolePayloadGQL,
    BulkRevokeRoleInputGQL,
    BulkRevokeRolePayloadGQL,
    CreatePermissionInput,
    CreateRoleInput,
    CreateRoleInvitationInputGQL,
    CreateRoleInvitationPayload,
    EffectivePermissionsPayloadGQL,
    EntityActionInfoGQL,
    EntityConnection,
    EntityEffectivePermissionsGQL,
    EntityFilter,
    EntityOperationCombinationGQL,
    EntityOrderBy,
    EntityRefGQL,
    OperationInfoGQL,
    OperationTypeGQL,
    PermissionConnection,
    PermissionFilter,
    PermissionGQL,
    PermissionOrderBy,
    RBACElementTypeGQL,
    ResolveEffectivePermissionsInputGQL,
    ResolveUserEffectivePermissionsInputGQL,
    RevokeRoleInput,
    RoleAssignmentConnection,
    RoleAssignmentFilter,
    RoleAssignmentGQL,
    RoleConnection,
    RoleFilter,
    RoleGQL,
    RoleInvitationConnection,
    RoleInvitationGQL,
    RoleOrderBy,
    RoleSourceGQL,
    RoleStatusGQL,
    ScopeEntityCombinationGQL,
    ScopeEntityOperationCombinationGQL,
    UpdatePermissionInput,
    UpdateRoleInput,
)

__all__ = (
    # Enums
    "RBACElementTypeGQL",
    "OperationTypeGQL",
    "RoleSourceGQL",
    "RoleStatusGQL",
    # Types
    "RoleGQL",
    "PermissionGQL",
    "RoleAssignmentGQL",
    "EntityRefGQL",
    "ScopeEntityCombinationGQL",
    "EntityOperationCombinationGQL",
    "OperationInfoGQL",
    "EntityActionInfoGQL",
    "ScopeEntityOperationCombinationGQL",
    # Filters
    "RoleFilter",
    "PermissionFilter",
    "RoleAssignmentFilter",
    "EntityFilter",
    # OrderBy
    "RoleOrderBy",
    "PermissionOrderBy",
    "EntityOrderBy",
    # Inputs
    "CreateRoleInput",
    "UpdateRoleInput",
    "CreatePermissionInput",
    "UpdatePermissionInput",
    "AssignRoleInput",
    "RevokeRoleInput",
    "BulkAssignRoleInputGQL",
    "BulkRevokeRoleInputGQL",
    # Payloads
    "BulkAssignRolePayloadGQL",
    "BulkRevokeRolePayloadGQL",
    # Role invitation types
    "RoleInvitationGQL",
    "RoleInvitationConnection",
    "CreateRoleInvitationInputGQL",
    "CreateRoleInvitationPayload",
    # Connections
    "RoleConnection",
    "PermissionConnection",
    "RoleAssignmentConnection",
    "EntityConnection",
    # Query resolvers
    "admin_role",
    "admin_roles",
    "admin_permissions",
    "admin_role_assignments",
    "admin_entities",
    "admin_resolve_effective_permissions",
    "my_effective_permissions",
    "my_roles",
    "project_roles",
    "rbac_entity_operation_combinations",
    "rbac_permission_matrix",
    "rbac_scope_entity_combinations",
    # Effective permissions types
    "ResolveEffectivePermissionsInputGQL",
    "ResolveUserEffectivePermissionsInputGQL",
    "EntityEffectivePermissionsGQL",
    "EffectivePermissionsPayloadGQL",
    # Mutation resolvers
    "admin_create_role",
    "admin_update_role",
    "admin_delete_role",
    "admin_purge_role",
    "admin_create_permission",
    "admin_update_permission",
    "admin_delete_permission",
    "admin_assign_role",
    "admin_revoke_role",
    "admin_bulk_assign_role",
    "admin_bulk_revoke_role",
    # Role invitation resolvers
    "my_role_invitations",
    "role_scoped_role_invitations",
    "admin_role_invitations",
    "create_role_invitation",
    "accept_role_invitation",
    "reject_role_invitation",
    "admin_cancel_role_invitation",
)
