supergraph:
  listen: 0.0.0.0:4000

include_subgraph_errors:
  all: true

headers:
  all:
    request:
      - propagate:
          matching: ".*"
      - insert:
          name: "host"
          value: "localhost:8091"
