"""Role preset GraphQL API package."""

from .resolver import (
    admin_bulk_add_role_preset_permissions,
    admin_bulk_remove_role_preset_permissions,
    admin_create_role_preset,
    admin_delete_role_presets,
    admin_purge_role_presets,
    admin_restore_role_presets,
    admin_role_preset,
    admin_role_presets,
    admin_update_role_preset,
)
from .types import (
    BulkAddRolePermissionPresetFailureInfoGQL,
    BulkAddRolePermissionPresetsInputGQL,
    BulkAddRolePermissionPresetsPayloadGQL,
    BulkDeleteRolePresetsInputGQL,
    BulkDeleteRolePresetsPayloadGQL,
    BulkPurgeRolePresetsInputGQL,
    BulkPurgeRolePresetsPayloadGQL,
    BulkRemoveRolePermissionPresetsInputGQL,
    BulkRemoveRolePermissionPresetsPayloadGQL,
    BulkRestoreRolePresetsInputGQL,
    BulkRestoreRolePresetsPayloadGQL,
    BulkRolePermissionPresetFailureInfoGQL,
    BulkRolePresetFailureInfoGQL,
    CreateRolePresetInputGQL,
    CreateRolePresetPayloadGQL,
    RolePermissionPresetConnection,
    RolePermissionPresetEdge,
    RolePermissionPresetEntryInputGQL,
    RolePermissionPresetFilterGQL,
    RolePermissionPresetGQL,
    RolePermissionPresetOrderByGQL,
    RolePermissionPresetOrderFieldGQL,
    RolePresetConnection,
    RolePresetEdge,
    RolePresetFilterGQL,
    RolePresetGQL,
    RolePresetOrderByGQL,
    RolePresetOrderFieldGQL,
    UpdateRolePresetInputGQL,
    UpdateRolePresetPayloadGQL,
)

__all__ = [
    # Queries
    "admin_role_preset",
    "admin_role_presets",
    # Mutations
    "admin_create_role_preset",
    "admin_update_role_preset",
    "admin_delete_role_presets",
    "admin_restore_role_presets",
    "admin_purge_role_presets",
    "admin_bulk_add_role_preset_permissions",
    "admin_bulk_remove_role_preset_permissions",
    # Node / Connection types
    "RolePresetGQL",
    "RolePresetEdge",
    "RolePresetConnection",
    "RolePermissionPresetGQL",
    "RolePermissionPresetEdge",
    "RolePermissionPresetConnection",
    # Filter / OrderBy types
    "RolePresetFilterGQL",
    "RolePresetOrderByGQL",
    "RolePresetOrderFieldGQL",
    "RolePermissionPresetFilterGQL",
    "RolePermissionPresetOrderByGQL",
    "RolePermissionPresetOrderFieldGQL",
    # Input types
    "CreateRolePresetInputGQL",
    "UpdateRolePresetInputGQL",
    "BulkDeleteRolePresetsInputGQL",
    "BulkRestoreRolePresetsInputGQL",
    "BulkPurgeRolePresetsInputGQL",
    "RolePermissionPresetEntryInputGQL",
    "BulkAddRolePermissionPresetsInputGQL",
    "BulkRemoveRolePermissionPresetsInputGQL",
    # Payload types
    "CreateRolePresetPayloadGQL",
    "UpdateRolePresetPayloadGQL",
    "BulkRolePresetFailureInfoGQL",
    "BulkDeleteRolePresetsPayloadGQL",
    "BulkRestoreRolePresetsPayloadGQL",
    "BulkPurgeRolePresetsPayloadGQL",
    "BulkRolePermissionPresetFailureInfoGQL",
    "BulkAddRolePermissionPresetFailureInfoGQL",
    "BulkAddRolePermissionPresetsPayloadGQL",
    "BulkRemoveRolePermissionPresetsPayloadGQL",
]
