apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bai-storage-proxy.fullname" . }}-secrets
  labels:
    {{- include "bai-storage-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.storageProxy.jwtSecret | quote }}
  manager-secret: {{ .Values.storageProxy.managerSecret | quote }}
