python_tests(
    name="tests",
    dependencies=[
        "src/ai/backend/manager:src",
    ],
)

python_tests(
    name="test_querybuilder",
    sources=["test_querybuilder.py"],
    dependencies=[
        "src/ai/backend/manager:src",
    ],
)

python_tests(
    name="test_base",
    sources=["test_base.py"],
    dependencies=[
        "src/ai/backend/manager:src",
    ],
)

python_tests(
    name="test_pagination",
    sources=["test_pagination.py"],
    dependencies=[
        "src/ai/backend/manager:src",
    ],
)

python_tests(
    name="test_purger",
    sources=["test_purger.py"],
    dependencies=[
        "src/ai/backend/manager:src",
    ],
)