[etcd]
namespace = "local"
addr = { host = "127.0.0.1", port = 8120 }
user = ""
password = ""


[db]
type = "postgresql"
addr = { host = "localhost", port = 8100 }
name = "backend"
user = "postgres"
password = "develove"
pool-recycle = 50
pool-pre-ping = false


[account-manager]
num-proc = 1
service-addr = { host = "0.0.0.0", port = 8088 }
internal-addr = { host = "0.0.0.0", port = 18088 }
#user = "nobody"
#group = "nobody"
ssl-enabled = false
#ssl-cert = "/etc/backend.ai/ssl/apiserver-fullchain.pem"   # env: BACKNED_SSL_CERT
#ssl-privkey = "/etc/backend.ai/ssl/apiserver-privkey.pem"  # env: BACKNED_SSL_KEY
# ipc-base-path = "/tmp/backend.ai/ipc"
#id = ""
pid-file = "./account-manager.pid"             # env: BACKEND_PID_FILE


[pyroscope]
enabled = true
app_name = "backendai-half-account-manager"
server_addr = "http://localhost:4040"
sample-rate = 100


[logging]
level = "INFO"
drivers = ["console"]

[logging.pkg-ns]
"" = "WARNING"
"aiotools" = "INFO"
"aiohttp" = "INFO"
"ai.backend" = "INFO"
"alembic" = "INFO"
"sqlalchemy" = "WARNING"

[logging.console]
colored = true
format = "verbose"

[logging.file]
path = "./logs"
filename = "manager.log"
backup-count = 5
rotation-size = "10M"

[logging.logstash]
endpoint = { host = "localhost", port = 9300 }
protocol = "tcp"
ssl-enabled = true
ssl-verify = true

[logging.graylog]
host = "127.0.0.1"
port = 12201
ssl-verify = false
ca-certs = ""
keyfile = ""
certfile = ""

[debug]
enabled = false
