"""
Agent-side error classes.
"""

from ai.backend.common.kernel_runner.errors import InvalidSocket

from .agent import (
    AgentInitializationError,
    AsyncioTaskNotAvailableError,
    ContainerCreationError,
    ContainerCreationFailedError,
    ContainerStartupCancelledError,
    ContainerStartupFailedError,
    ContainerStartupTimeoutError,
    ImageArchitectureMismatchError,
    ImageCommandRequiredError,
    ImagePullTimeoutError,
    InitializationError,
    InvalidAgentConfigError,
    InvalidArgumentError,
    InvalidChunkSizeError,
    InvalidLoggingConfigError,
    InvalidMountPathError,
    K8sError,
    KernelNotFoundError,
    ModelDefinitionEmptyError,
    ModelDefinitionInvalidYAMLError,
    ModelDefinitionNotFoundError,
    ModelFolderNotSpecifiedError,
    NetworkPluginNotFound,
    PortConflictError,
    ReservedPortError,
    ServicePortAlreadyUsedError,
    UnsupportedBaseDistroError,
)
from .kernel import (
    AsyncioContextError,
    KernelRunnerNotInitializedError,
    OutputQueueMismatchError,
    OutputQueueNotInitializedError,
    RunIdNotSetError,
    SubprocessStreamError,
)
from .resources import (
    AgentIdNotFoundError,
    FractionalResourceFragmented,
    InsufficientResource,
    InvalidAllocMapTypeError,
    InvalidConfigFormatError,
    InvalidContainerMeasurementError,
    InvalidMeasurementError,
    InvalidOvercommitFactorError,
    InvalidResourceArgument,
    InvalidResourceCombination,
    InvalidResourceConfigError,
    NotMultipleOfQuantum,
    ResourceAllocationError,
    ResourceError,
    ResourceOverAllocatedError,
    UnsupportedResource,
)

__all__ = [
    # agent
    "AgentInitializationError",
    "AsyncioTaskNotAvailableError",
    "ContainerCreationError",
    "ContainerCreationFailedError",
    "ContainerStartupCancelledError",
    "ContainerStartupFailedError",
    "ContainerStartupTimeoutError",
    "ImageArchitectureMismatchError",
    "ImageCommandRequiredError",
    "ImagePullTimeoutError",
    "InitializationError",
    "InvalidAgentConfigError",
    "InvalidArgumentError",
    "InvalidChunkSizeError",
    "InvalidLoggingConfigError",
    "InvalidMountPathError",
    "InvalidSocket",
    "K8sError",
    "KernelNotFoundError",
    "ModelDefinitionEmptyError",
    "ModelDefinitionInvalidYAMLError",
    "ModelDefinitionNotFoundError",
    "ModelFolderNotSpecifiedError",
    "NetworkPluginNotFound",
    "PortConflictError",
    "ReservedPortError",
    "ServicePortAlreadyUsedError",
    "UnsupportedBaseDistroError",
    # kernel
    "AsyncioContextError",
    "KernelRunnerNotInitializedError",
    "OutputQueueMismatchError",
    "OutputQueueNotInitializedError",
    "RunIdNotSetError",
    "SubprocessStreamError",
    # resources
    "AgentIdNotFoundError",
    "FractionalResourceFragmented",
    "InsufficientResource",
    "InvalidAllocMapTypeError",
    "InvalidConfigFormatError",
    "InvalidContainerMeasurementError",
    "InvalidMeasurementError",
    "InvalidOvercommitFactorError",
    "InvalidResourceArgument",
    "InvalidResourceCombination",
    "InvalidResourceConfigError",
    "NotMultipleOfQuantum",
    "ResourceAllocationError",
    "ResourceError",
    "ResourceOverAllocatedError",
    "UnsupportedResource",
]
