"""
Agent-side error classes.
"""

from .agent import (
    AgentInitializationError,
    AsyncioTaskNotAvailableError,
    ContainerCreationFailedError,
    ContainerStartupCancelledError,
    ContainerStartupFailedError,
    ContainerStartupTimeoutError,
    ImageArchitectureMismatchError,
    ImageCommandRequiredError,
    ImagePullTimeoutError,
    InvalidAgentConfigError,
    InvalidChunkSizeError,
    InvalidLoggingConfigError,
    InvalidMountPathError,
    KernelNotFoundError,
    ModelDefinitionEmptyError,
    ModelDefinitionInvalidYAMLError,
    ModelDefinitionNotFoundError,
    ModelDefinitionValidationError,
    ModelFolderNotSpecifiedError,
    PortConflictError,
    ReservedPortError,
)
from .kernel import (
    AsyncioContextError,
    KernelRunnerNotInitializedError,
    OutputQueueMismatchError,
    OutputQueueNotInitializedError,
    RunIdNotSetError,
    SubprocessStreamError,
)
from .resources import (
    AgentIdNotFoundError,
    InvalidAllocMapTypeError,
    InvalidConfigFormatError,
    InvalidContainerMeasurementError,
    InvalidMeasurementError,
    InvalidOvercommitFactorError,
    InvalidResourceConfigError,
    ResourceAllocationError,
    ResourceOverAllocatedError,
)

__all__ = [
    # agent
    "AgentInitializationError",
    "AsyncioTaskNotAvailableError",
    "ContainerCreationFailedError",
    "ContainerStartupCancelledError",
    "ContainerStartupFailedError",
    "ContainerStartupTimeoutError",
    "ImageArchitectureMismatchError",
    "ImageCommandRequiredError",
    "ImagePullTimeoutError",
    "InvalidAgentConfigError",
    "InvalidChunkSizeError",
    "InvalidLoggingConfigError",
    "InvalidMountPathError",
    "KernelNotFoundError",
    "ModelDefinitionEmptyError",
    "ModelDefinitionInvalidYAMLError",
    "ModelDefinitionNotFoundError",
    "ModelDefinitionValidationError",
    "ModelFolderNotSpecifiedError",
    "PortConflictError",
    "ReservedPortError",
    # kernel
    "AsyncioContextError",
    "KernelRunnerNotInitializedError",
    "OutputQueueMismatchError",
    "OutputQueueNotInitializedError",
    "RunIdNotSetError",
    "SubprocessStreamError",
    # resources
    "AgentIdNotFoundError",
    "InvalidAllocMapTypeError",
    "InvalidConfigFormatError",
    "InvalidContainerMeasurementError",
    "InvalidMeasurementError",
    "InvalidOvercommitFactorError",
    "InvalidResourceConfigError",
    "ResourceAllocationError",
    "ResourceOverAllocatedError",
]
