python_sources(
    name="src",
    # Prevent inclusion by automatic rule generation of
    # python_tests() and python_test_utils()
    sources=[
        "*.py",
        "admin/*.py",
        "user/*.py",
    ],
)
