# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/backend/agent/containerd/_grpcapi/api/events/container.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai/backend/agent/containerd/_grpcapi/api/events/container.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from ai.backend.agent.containerd._grpcapi.gogoproto import gogo_pb2 as ai_dot_backend_dot_agent_dot_containerd_dot___grpcapi_dot_gogoproto_dot_gogo__pb2
from ai.backend.agent.containerd._grpcapi.protobuf.plugin import fieldpath_pb2 as ai_dot_backend_dot_agent_dot_containerd_dot___grpcapi_dot_protobuf_dot_plugin_dot_fieldpath__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?ai/backend/agent/containerd/_grpcapi/api/events/container.proto\x12\x11\x63ontainerd.events\x1a\x19google/protobuf/any.proto\x1a\x39\x61i/backend/agent/containerd/_grpcapi/gogoproto/gogo.proto\x1a\x44\x61i/backend/agent/containerd/_grpcapi/protobuf/plugin/fieldpath.proto\"\xa9\x01\n\x0f\x43ontainerCreate\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12;\n\x07runtime\x18\x03 \x01(\x0b\x32*.containerd.events.ContainerCreate.Runtime\x1a>\n\x07Runtime\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x07options\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"\xb1\x01\n\x0f\x43ontainerUpdate\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12>\n\x06labels\x18\x03 \x03(\x0b\x32..containerd.events.ContainerUpdate.LabelsEntry\x12\x14\n\x0csnapshot_key\x18\x04 \x01(\t\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1d\n\x0f\x43ontainerDelete\x12\n\n\x02id\x18\x01 \x01(\tB8Z2github.com/containerd/containerd/api/events;events\xa0\xf4\x1e\x01X\x01X\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.backend.agent.containerd._grpcapi.api.events.container_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/containerd/containerd/api/events;events\240\364\036\001'
  _globals['_CONTAINERUPDATE_LABELSENTRY']._loaded_options = None
  _globals['_CONTAINERUPDATE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_CONTAINERCREATE']._serialized_start=243
  _globals['_CONTAINERCREATE']._serialized_end=412
  _globals['_CONTAINERCREATE_RUNTIME']._serialized_start=350
  _globals['_CONTAINERCREATE_RUNTIME']._serialized_end=412
  _globals['_CONTAINERUPDATE']._serialized_start=415
  _globals['_CONTAINERUPDATE']._serialized_end=592
  _globals['_CONTAINERUPDATE_LABELSENTRY']._serialized_start=547
  _globals['_CONTAINERUPDATE_LABELSENTRY']._serialized_end=592
  _globals['_CONTAINERDELETE']._serialized_start=594
  _globals['_CONTAINERDELETE']._serialized_end=623
# @@protoc_insertion_point(module_scope)
