# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/backend/agent/containerd/_grpcapi/api/events/image.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai/backend/agent/containerd/_grpcapi/api/events/image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.backend.agent.containerd._grpcapi.protobuf.plugin import fieldpath_pb2 as ai_dot_backend_dot_agent_dot_containerd_dot___grpcapi_dot_protobuf_dot_plugin_dot_fieldpath__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;ai/backend/agent/containerd/_grpcapi/api/events/image.proto\x12\x1d\x63ontainerd.services.images.v1\x1a\x44\x61i/backend/agent/containerd/_grpcapi/protobuf/plugin/fieldpath.proto\"\x92\x01\n\x0bImageCreate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x46\n\x06labels\x18\x02 \x03(\x0b\x32\x36.containerd.services.images.v1.ImageCreate.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x92\x01\n\x0bImageUpdate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x46\n\x06labels\x18\x02 \x03(\x0b\x32\x36.containerd.services.images.v1.ImageUpdate.LabelsEntry\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1b\n\x0bImageDelete\x12\x0c\n\x04name\x18\x01 \x01(\tB8Z2github.com/containerd/containerd/api/events;events\xa0\xf4\x1e\x01X\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.backend.agent.containerd._grpcapi.api.events.image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/containerd/containerd/api/events;events\240\364\036\001'
  _globals['_IMAGECREATE_LABELSENTRY']._loaded_options = None
  _globals['_IMAGECREATE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_IMAGEUPDATE_LABELSENTRY']._loaded_options = None
  _globals['_IMAGEUPDATE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_IMAGECREATE']._serialized_start=165
  _globals['_IMAGECREATE']._serialized_end=311
  _globals['_IMAGECREATE_LABELSENTRY']._serialized_start=266
  _globals['_IMAGECREATE_LABELSENTRY']._serialized_end=311
  _globals['_IMAGEUPDATE']._serialized_start=314
  _globals['_IMAGEUPDATE']._serialized_end=460
  _globals['_IMAGEUPDATE_LABELSENTRY']._serialized_start=266
  _globals['_IMAGEUPDATE_LABELSENTRY']._serialized_end=311
  _globals['_IMAGEDELETE']._serialized_start=462
  _globals['_IMAGEDELETE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
