# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/backend/agent/containerd/_grpcapi/api/events/snapshot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai/backend/agent/containerd/_grpcapi/api/events/snapshot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ai.backend.agent.containerd._grpcapi.protobuf.plugin import fieldpath_pb2 as ai_dot_backend_dot_agent_dot_containerd_dot___grpcapi_dot_protobuf_dot_plugin_dot_fieldpath__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>ai/backend/agent/containerd/_grpcapi/api/events/snapshot.proto\x12\x11\x63ontainerd.events\x1a\x44\x61i/backend/agent/containerd/_grpcapi/protobuf/plugin/fieldpath.proto\".\n\x0fSnapshotPrepare\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06parent\x18\x02 \x01(\t\"+\n\x0eSnapshotCommit\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1d\n\x0eSnapshotRemove\x12\x0b\n\x03key\x18\x01 \x01(\tB8Z2github.com/containerd/containerd/api/events;events\xa0\xf4\x1e\x01X\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.backend.agent.containerd._grpcapi.api.events.snapshot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/containerd/containerd/api/events;events\240\364\036\001'
  _globals['_SNAPSHOTPREPARE']._serialized_start=155
  _globals['_SNAPSHOTPREPARE']._serialized_end=201
  _globals['_SNAPSHOTCOMMIT']._serialized_start=203
  _globals['_SNAPSHOTCOMMIT']._serialized_end=246
  _globals['_SNAPSHOTREMOVE']._serialized_start=248
  _globals['_SNAPSHOTREMOVE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
