#!/usr/bin/env bash
# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Run pants from a locally built source clone.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

if [ -f '.pants.env' ]; then
  source .pants.env
fi
if [ -z "$PY" ]; then
  echo "The Python version for source-built Pants is not configured in ./.pants.env"
  exit 1
fi
PANTS_SOURCE="${PANTS_SOURCE:-$(pwd)/tools/pants-src}"

# When running pants from sources you are likely to be modifying those sources, so
# you won't want pantsd running.  You can override this by setting ENABLE_PANTSD=true.
ENABLE_PANTSD="${ENABLE_PANTSD:-false}"

export PANTS_VERSION="$(cat "${PANTS_SOURCE}/src/python/pants/VERSION")"
export PANTS_PANTSD="${ENABLE_PANTSD}"
export no_proxy="*"

exec "${PANTS_SOURCE}/pants" "--no-verify-config" "$@"
