python_sources(
    name="valkey_stat",
    dependencies=[
        "//src/ai/backend/common/clients/valkey_client:src",
        "//src/ai/backend/common:src",
        "//src/ai/backend/logging:src",
    ],
)