"""
Deployment DTOs v2 for Manager API.
"""

from ai.backend.common.dto.manager.v2.deployment.request import (
    ActivateDeploymentInput,
    AddRevisionInput,
    BlueGreenConfigInput,
    CreateDeploymentInput,
    DeleteDeploymentInput,
    ExtraVFolderMountInput,
    RevisionInput,
    RollingUpdateConfigInput,
    ScaleDeploymentInput,
    UpdateDeploymentInput,
)
from ai.backend.common.dto.manager.v2.deployment.response import (
    ActivateDeploymentPayload,
    AddRevisionPayload,
    CreateDeploymentPayload,
    DeleteDeploymentPayload,
    DeploymentNode,
    ExtraVFolderMountNode,
    RevisionNode,
    RouteNode,
    ScaleDeploymentPayload,
    UpdateDeploymentPayload,
)
from ai.backend.common.dto.manager.v2.deployment.types import (
    BlueGreenConfigInfo,
    ClusterMode,
    DeploymentBasicInfo,
    DeploymentOrderField,
    DeploymentPolicyInfo,
    DeploymentRevisionInfo,
    DeploymentStrategy,
    EndpointLifecycle,
    ModelDeploymentStatus,
    NetworkConfigInfo,
    OrderDirection,
    ReplicaStateInfo,
    RevisionOrderField,
    RollingUpdateConfigInfo,
    RouteOrderField,
    RouteStatus,
    RouteTrafficStatus,
    RuntimeVariant,
)

__all__ = (
    # Types
    "BlueGreenConfigInfo",
    "ClusterMode",
    "DeploymentBasicInfo",
    "DeploymentOrderField",
    "DeploymentPolicyInfo",
    "DeploymentRevisionInfo",
    "DeploymentStrategy",
    "EndpointLifecycle",
    "ModelDeploymentStatus",
    "NetworkConfigInfo",
    "OrderDirection",
    "ReplicaStateInfo",
    "RevisionOrderField",
    "RollingUpdateConfigInfo",
    "RouteOrderField",
    "RouteStatus",
    "RouteTrafficStatus",
    "RuntimeVariant",
    # Input models (request)
    "ActivateDeploymentInput",
    "AddRevisionInput",
    "BlueGreenConfigInput",
    "CreateDeploymentInput",
    "DeleteDeploymentInput",
    "ExtraVFolderMountInput",
    "RevisionInput",
    "RollingUpdateConfigInput",
    "ScaleDeploymentInput",
    "UpdateDeploymentInput",
    # Node and Payload models (response)
    "ActivateDeploymentPayload",
    "AddRevisionPayload",
    "CreateDeploymentPayload",
    "DeleteDeploymentPayload",
    "DeploymentNode",
    "ExtraVFolderMountNode",
    "RevisionNode",
    "RouteNode",
    "ScaleDeploymentPayload",
    "UpdateDeploymentPayload",
)
