"""Fair Share GQL types package."""

from .common import (
    FairShareCalculationSnapshotGQL,
    FairShareSpecGQL,
    ResourceSlotEntryGQL,
    ResourceSlotGQL,
    ResourceWeightEntryInputGQL,
)
from .domain import (
    BulkUpsertDomainFairShareWeightInput,
    BulkUpsertDomainFairShareWeightPayload,
    DomainFairShareConnection,
    DomainFairShareDomainNestedFilter,
    DomainFairShareEdge,
    DomainFairShareFilter,
    DomainFairShareGQL,
    DomainFairShareOrderBy,
    DomainFairShareOrderField,
    DomainWeightInputItem,
    RGDomainFairShareFilter,
    UpsertDomainFairShareWeightInput,
    UpsertDomainFairShareWeightPayload,
)
from .project import (
    BulkUpsertProjectFairShareWeightInput,
    BulkUpsertProjectFairShareWeightPayload,
    ProjectFairShareConnection,
    ProjectFairShareEdge,
    ProjectFairShareFilter,
    ProjectFairShareGQL,
    ProjectFairShareOrderBy,
    ProjectFairShareOrderField,
    ProjectFairShareProjectNestedFilter,
    ProjectFairShareTypeEnum,
    ProjectFairShareTypeEnumFilter,
    ProjectWeightInputItem,
    RGProjectFairShareFilter,
    UpsertProjectFairShareWeightInput,
    UpsertProjectFairShareWeightPayload,
)
from .user import (
    BulkUpsertUserFairShareWeightInput,
    BulkUpsertUserFairShareWeightPayload,
    RGUserFairShareFilter,
    UpsertUserFairShareWeightInput,
    UpsertUserFairShareWeightPayload,
    UserFairShareConnection,
    UserFairShareEdge,
    UserFairShareFilter,
    UserFairShareGQL,
    UserFairShareOrderBy,
    UserFairShareOrderField,
    UserFairShareUserNestedFilter,
    UserWeightInputItem,
)

__all__ = [
    # Common
    "ResourceSlotEntryGQL",
    "ResourceSlotGQL",
    "ResourceWeightEntryInputGQL",
    "FairShareSpecGQL",
    "FairShareCalculationSnapshotGQL",
    # Domain
    "DomainFairShareGQL",
    "DomainFairShareConnection",
    "DomainFairShareDomainNestedFilter",
    "DomainFairShareEdge",
    "DomainFairShareFilter",
    "DomainFairShareOrderField",
    "DomainFairShareOrderBy",
    "RGDomainFairShareFilter",
    "UpsertDomainFairShareWeightInput",
    "UpsertDomainFairShareWeightPayload",
    "DomainWeightInputItem",
    "BulkUpsertDomainFairShareWeightInput",
    "BulkUpsertDomainFairShareWeightPayload",
    # Project
    "ProjectFairShareGQL",
    "ProjectFairShareConnection",
    "ProjectFairShareEdge",
    "ProjectFairShareFilter",
    "ProjectFairShareOrderField",
    "ProjectFairShareOrderBy",
    "ProjectFairShareProjectNestedFilter",
    "ProjectFairShareTypeEnum",
    "ProjectFairShareTypeEnumFilter",
    "RGProjectFairShareFilter",
    "UpsertProjectFairShareWeightInput",
    "UpsertProjectFairShareWeightPayload",
    "ProjectWeightInputItem",
    "BulkUpsertProjectFairShareWeightInput",
    "BulkUpsertProjectFairShareWeightPayload",
    # User
    "UserFairShareGQL",
    "UserFairShareConnection",
    "UserFairShareEdge",
    "UserFairShareFilter",
    "UserFairShareOrderField",
    "UserFairShareOrderBy",
    "UserFairShareUserNestedFilter",
    "RGUserFairShareFilter",
    "UpsertUserFairShareWeightInput",
    "UpsertUserFairShareWeightPayload",
    "UserWeightInputItem",
    "BulkUpsertUserFairShareWeightInput",
    "BulkUpsertUserFairShareWeightPayload",
]
