from __future__ import annotations

import os
from collections.abc import Sequence
from typing import Protocol

from cryptography.exceptions import InvalidSignature, UnsupportedAlgorithm
from cryptography.hazmat.primitives import serialization as crypto_serialization
from cryptography.hazmat.primitives.asymmetric import ec, ed25519, rsa
from cryptography.hazmat.primitives.asymmetric.padding import PKCS1v15
from cryptography.hazmat.primitives.asymmetric.types import PrivateKeyTypes, PublicKeyTypes
from cryptography.hazmat.primitives.hashes import SHA256

from ai.backend.common.types import SSHPrivateKey, SSHPublicKey
from ai.backend.manager.errors.keypair import (
    InvalidSSHPrivateKey,
    InvalidSSHPublicKey,
    SSHKeypairMismatch,
)

# Size of the random message signed to verify that the keypair matches.
_VERIFY_MESSAGE_SIZE = 32


class PrivateKeyLoader(Protocol):
    def __call__(self, data: bytes, password: bytes | None) -> PrivateKeyTypes: ...


class PublicKeyLoader(Protocol):
    def __call__(self, data: bytes) -> PublicKeyTypes: ...


# Try the traditional PEM (OpenSSL) format first, then the OpenSSH container format
# (``-----BEGIN OPENSSH PRIVATE KEY-----``), so that keys generated by modern
# ``ssh-keygen`` (e.g. ed25519) are accepted as well.
DEFAULT_PRIVATE_KEY_LOADERS: tuple[PrivateKeyLoader, ...] = (
    crypto_serialization.load_pem_private_key,
    crypto_serialization.load_ssh_private_key,
)
DEFAULT_PUBLIC_KEY_LOADER: PublicKeyLoader = crypto_serialization.load_ssh_public_key


class SSHKeyValidator:
    """
    Validate an SSH keypair (private + public) used for SSH/SFTP connections.

    The set of accepted formats is determined by the injected loaders. By default the
    private key is accepted in either the traditional PEM (OpenSSL) format
    (``-----BEGIN RSA PRIVATE KEY-----`` / ``-----BEGIN PRIVATE KEY-----``) or the
    OpenSSH container format (``-----BEGIN OPENSSH PRIVATE KEY-----``), and the public
    key is accepted in the OpenSSH single-line format (e.g. ``ssh-ed25519 AAAA...``).
    """

    _private_key_loaders: Sequence[PrivateKeyLoader]
    _public_key_loader: PublicKeyLoader

    def __init__(
        self,
        private_key_loaders: Sequence[PrivateKeyLoader] = DEFAULT_PRIVATE_KEY_LOADERS,
        public_key_loader: PublicKeyLoader = DEFAULT_PUBLIC_KEY_LOADER,
    ) -> None:
        self._private_key_loaders = private_key_loaders
        self._public_key_loader = public_key_loader

    def validate(self, private_key: SSHPrivateKey, public_key: SSHPublicKey) -> None:
        """
        Validate that the keypair is well-formed and that the public key matches
        the private key.

        :raises InvalidSSHPrivateKey: the private key cannot be parsed.
        :raises InvalidSSHPublicKey: the public key cannot be parsed.
        :raises SSHKeypairMismatch: the keys are of incompatible types or do not match.
        """
        loaded_private_key = self._load_private_key(private_key)
        loaded_public_key = self._load_public_key(public_key)
        self._verify_match(loaded_private_key, loaded_public_key)

    def _load_private_key(self, private_key: SSHPrivateKey) -> PrivateKeyTypes:
        key_bytes = private_key.encode()
        # Each loader raises ValueError when the key does not match its format.
        for loader in self._private_key_loaders:
            try:
                return loader(key_bytes, None)
            except (ValueError, UnsupportedAlgorithm):
                continue
            except TypeError:
                # The key is encrypted (password-protected); we never supply a password.
                raise InvalidSSHPrivateKey(
                    "Password-protected private keys are not supported"
                ) from None
        raise InvalidSSHPrivateKey("Invalid private key format")

    def _load_public_key(self, public_key: SSHPublicKey) -> PublicKeyTypes:
        try:
            return self._public_key_loader(public_key.encode())
        except (ValueError, UnsupportedAlgorithm) as e:
            raise InvalidSSHPublicKey("Invalid public key format") from e

    def _verify_match(self, private_key: PrivateKeyTypes, public_key: PublicKeyTypes) -> None:
        message = os.urandom(_VERIFY_MESSAGE_SIZE)
        try:
            match private_key, public_key:
                case rsa.RSAPrivateKey(), rsa.RSAPublicKey():
                    signature = private_key.sign(message, PKCS1v15(), SHA256())
                    public_key.verify(signature, message, PKCS1v15(), SHA256())
                case ec.EllipticCurvePrivateKey(), ec.EllipticCurvePublicKey():
                    signature = private_key.sign(message, ec.ECDSA(SHA256()))
                    public_key.verify(signature, message, ec.ECDSA(SHA256()))
                case ed25519.Ed25519PrivateKey(), ed25519.Ed25519PublicKey():
                    signature = private_key.sign(message)
                    public_key.verify(signature, message)
                case _:
                    raise SSHKeypairMismatch(
                        "The private and public keys are of incompatible types"
                    )
        except InvalidSignature as e:
            raise SSHKeypairMismatch("Public key does not match the private key") from e
        except (ValueError, UnsupportedAlgorithm) as e:
            # sign() may reject an otherwise loadable key (e.g. an RSA key too small
            # for the chosen hash/padding).
            raise InvalidSSHPrivateKey(f"Unable to sign with the provided private key: {e}") from e
