"""
Fair share DTOs v2 for Manager API.
"""

from ai.backend.common.dto.manager.v2.fair_share.request import (
    BulkUpsertDomainFairShareWeightInput,
    BulkUpsertProjectFairShareWeightInput,
    BulkUpsertUserFairShareWeightInput,
    DomainFairShareFilter,
    DomainFairShareOrder,
    DomainUsageBucketFilter,
    DomainUsageBucketOrder,
    DomainWeightEntryInput,
    GetDomainFairShareInput,
    GetProjectFairShareInput,
    GetResourceGroupFairShareSpecInput,
    GetUserFairShareInput,
    ProjectFairShareFilter,
    ProjectFairShareOrder,
    ProjectUsageBucketFilter,
    ProjectUsageBucketOrder,
    ProjectWeightEntryInput,
    ResourceWeightEntryInput,
    SearchDomainFairSharesInput,
    SearchDomainUsageBucketsInput,
    SearchProjectFairSharesInput,
    SearchProjectUsageBucketsInput,
    SearchUserFairSharesInput,
    SearchUserUsageBucketsInput,
    UpdateResourceGroupFairShareSpecInput,
    UpsertDomainFairShareWeightInput,
    UpsertProjectFairShareWeightInput,
    UpsertUserFairShareWeightInput,
    UserFairShareFilter,
    UserFairShareOrder,
    UserUsageBucketFilter,
    UserUsageBucketOrder,
    UserWeightEntryInput,
)
from ai.backend.common.dto.manager.v2.fair_share.response import (
    BulkUpsertDomainFairShareWeightPayload,
    BulkUpsertProjectFairShareWeightPayload,
    BulkUpsertUserFairShareWeightPayload,
    DomainFairShareNode,
    DomainUsageBucketNode,
    GetDomainFairSharePayload,
    GetProjectFairSharePayload,
    GetResourceGroupFairShareSpecPayload,
    GetUserFairSharePayload,
    ProjectFairShareNode,
    ProjectUsageBucketNode,
    ResourceGroupFairShareSpecNode,
    SearchDomainFairSharesPayload,
    SearchDomainUsageBucketsPayload,
    SearchProjectFairSharesPayload,
    SearchProjectUsageBucketsPayload,
    SearchUserFairSharesPayload,
    SearchUserUsageBucketsPayload,
    UpdateResourceGroupFairShareSpecPayload,
    UpsertDomainFairShareWeightPayload,
    UpsertProjectFairShareWeightPayload,
    UpsertUserFairShareWeightPayload,
    UserFairShareNode,
    UserUsageBucketNode,
)
from ai.backend.common.dto.manager.v2.fair_share.types import (
    DomainFairShareOrderField,
    DomainUsageBucketOrderField,
    FairShareCalculationSnapshotInfo,
    FairShareSpecInfo,
    OrderDirection,
    ProjectFairShareOrderField,
    ProjectUsageBucketOrderField,
    ResourceSlotEntryInfo,
    ResourceSlotInfo,
    UsageBucketMetadataInfo,
    UserFairShareOrderField,
    UserUsageBucketOrderField,
)

__all__ = (
    # Types (enums)
    "OrderDirection",
    "DomainFairShareOrderField",
    "ProjectFairShareOrderField",
    "UserFairShareOrderField",
    "DomainUsageBucketOrderField",
    "ProjectUsageBucketOrderField",
    "UserUsageBucketOrderField",
    # Types (sub-models)
    "ResourceSlotEntryInfo",
    "ResourceSlotInfo",
    "FairShareSpecInfo",
    "FairShareCalculationSnapshotInfo",
    "UsageBucketMetadataInfo",
    # Request (filter models)
    "DomainFairShareFilter",
    "ProjectFairShareFilter",
    "UserFairShareFilter",
    "DomainUsageBucketFilter",
    "ProjectUsageBucketFilter",
    "UserUsageBucketFilter",
    # Request (order models)
    "DomainFairShareOrder",
    "ProjectFairShareOrder",
    "UserFairShareOrder",
    "DomainUsageBucketOrder",
    "ProjectUsageBucketOrder",
    "UserUsageBucketOrder",
    # Request (get inputs)
    "GetDomainFairShareInput",
    "GetProjectFairShareInput",
    "GetUserFairShareInput",
    "GetResourceGroupFairShareSpecInput",
    # Request (search inputs)
    "SearchDomainFairSharesInput",
    "SearchProjectFairSharesInput",
    "SearchUserFairSharesInput",
    "SearchDomainUsageBucketsInput",
    "SearchProjectUsageBucketsInput",
    "SearchUserUsageBucketsInput",
    # Request (upsert weight inputs)
    "UpsertDomainFairShareWeightInput",
    "UpsertProjectFairShareWeightInput",
    "UpsertUserFairShareWeightInput",
    # Request (bulk upsert entry types)
    "DomainWeightEntryInput",
    "ProjectWeightEntryInput",
    "UserWeightEntryInput",
    # Request (bulk upsert inputs)
    "BulkUpsertDomainFairShareWeightInput",
    "BulkUpsertProjectFairShareWeightInput",
    "BulkUpsertUserFairShareWeightInput",
    # Request (update spec)
    "ResourceWeightEntryInput",
    "UpdateResourceGroupFairShareSpecInput",
    # Response (fair share nodes)
    "DomainFairShareNode",
    "ProjectFairShareNode",
    "UserFairShareNode",
    # Response (usage bucket nodes)
    "DomainUsageBucketNode",
    "ProjectUsageBucketNode",
    "UserUsageBucketNode",
    # Response (resource group spec node)
    "ResourceGroupFairShareSpecNode",
    # Response (get payloads)
    "GetDomainFairSharePayload",
    "GetProjectFairSharePayload",
    "GetUserFairSharePayload",
    # Response (search payloads)
    "SearchDomainFairSharesPayload",
    "SearchProjectFairSharesPayload",
    "SearchUserFairSharesPayload",
    "SearchDomainUsageBucketsPayload",
    "SearchProjectUsageBucketsPayload",
    "SearchUserUsageBucketsPayload",
    # Response (upsert weight payloads)
    "UpsertDomainFairShareWeightPayload",
    "UpsertProjectFairShareWeightPayload",
    "UpsertUserFairShareWeightPayload",
    # Response (bulk upsert weight payloads)
    "BulkUpsertDomainFairShareWeightPayload",
    "BulkUpsertProjectFairShareWeightPayload",
    "BulkUpsertUserFairShareWeightPayload",
    # Response (resource group spec payloads)
    "UpdateResourceGroupFairShareSpecPayload",
    "GetResourceGroupFairShareSpecPayload",
)
