name: auto-recoder
on: 
  pull_request:
permissions:
  contents: write
#defaults:
#  run:
#    working-directory: scripts

jobs:
  auto-recode:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: a
      run: pwd
    - name: b
      run: ls -al
    - name: c
      working-directory: scripts
      run: ls -al
    - name: d
      working-directory: changes
      run: ls -al
    - name: e
      working-directory: .github/workflows
      run: ls -al
    - name: run do work
      working-directory: scripts
      run: python dowork.py ${{github.event.pull_request.number}} ${{github.event.pull_request.title}}
    - name: see that dowork.py work correctly
      working-directory: changes
      run: ls -al
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: GitHub Actions added ${{github.event.pull_request.number}}.YOUR_PR_FEAT.md file in backend.ai/changes folder and its content is your PR's title without feature. 

    #- name: d
    #  run: echo The Title of your PR is ${{ github.event.pull_request.title }}
    #- name: e
    #  run: echo The Number of your PR is ${{ github.event.pull_request.number }}
    #- name: f
    #  working-directory: scripts
    #  run: python dowork.py ${{github.event.pull_request.number}} ${{github.event.pull_request.title}}
    #- run: ls -al
    #- uses: stefanzweifel/git-auto-commit-action@v4
    #  with:
    #    commit_message: GitHub Actions added ${{github.event.pull_request.number}}.YOUR_PR_FEAT.md file in backend.ai/changes folder and its content is your PR's title without feature. 
        
    
