name: auto-recorder
on: 
  pull_request:
permissions:
  contents: write
#defaults:
#  run:
#    working-directory: scripts

jobs:
  auto-record:
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v3
    #  with:
    #    ref: ${{ github.head_ref }}
    - run: ls -al
    - run: echo The Title of your PR is ${{ github.event.pull_request.title }}
    - run: echo The Number of your PR is ${{ github.event.pull_request.number }}
    - name: dodo
      working-directory: scripts/
      run: python dowork.py ${{github.event.pull_request.number}} ${{github.event.pull_request.title}}
    - run: ls -al
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: GitHub Actions added ${{github.event.pull_request.number}}.YOUR_PR_FEAT.md file in backend.ai/changes folder and its content is your PR's title without feature. 
        
    
