name: 'Auto Label'

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - uses: lablup/auto-label-in-issue@1.3.0
