name: Build static wsproxy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The WebUI branch to use'
        required: true
        default: 'main'
        type: string

jobs:
  build-static-wsproxy:
    strategy:
      fail-fast: false
      matrix:
        # ubuntu-latest: intel
        # linux-aarch64: aarch64 (self-hosted)
        # macos-12: intel
        # macos-13: apple silicon
        os: [ubuntu-latest, linux-aarch64, macos-13-xlarge, macos-12-large]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone the webui repo
      uses: actions/checkout@v4
      with:
        repository: lablup/backend.ai-webui
        ref: ${{ inputs.branch }}
    - if: ${{ !endsWith(matrix.os, 'linux-aarch64') }}
      uses: actions/setup-node@v3
      with:
        node-version: '20.8.0'
      # For linux-aarch64 runner, we assume that we have the correct NodeJS version already (using asdf).
    - name: Build wsproxy
      run: |
        npm i
        OS_TYPE=$(uname -s)
        CPU_ARCH=$(uname -m)
        SYSTEM="$OS_TYPE $CPU_ARCH"
        case "$SYSTEM" in
          "Linux x86_64" )
            PLATFORM="linux_x64"
            ;;
          "Linux aarch64" )
            PLATFORM="linux_arm64"
            ;;
          "Darwin x86_64" )
            PLATFORM="mac_x64"
            npm rebuild
            ;;
          "Darwin arm64" )
            PLATFORM="mac_arm64"
            npm rebuild
            ;;
        esac
        make -j1 "$PLATFORM"
    - name: Show the build result
      run: |
        ls -lh app/
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: static-wsproxy
        path: app/backend.ai-local-proxy-*
