"""Tests of the harness itself.

A leak checker is trusted precisely when nobody looks at it, so it is the one component whose own
failure mode is silent. Every collector below is fed output captured verbatim from a live host
running this branch, and the guard is checked against the two ways it could lie: reporting a
pre-existing resource as a leak, and reporting a leaking host as clean.

These run with no privileges and no `BAI_DATAPLANE_NODES`, so they execute in ordinary CI.
"""

from __future__ import annotations

import json

import pytest

from ai.backend.testutils.dataplane.collectors.base import Resource
from ai.backend.testutils.dataplane.collectors.containerd_objects import ContainerdObjectCollector
from ai.backend.testutils.dataplane.collectors.docker_objects import (
    DockerKernelContainerCollector,
    DockerNetworkCollector,
    DockerSandboxCollector,
)
from ai.backend.testutils.dataplane.collectors.etcd_keys import EtcdNetworkKeyCollector, flatten
from ai.backend.testutils.dataplane.collectors.gauges import (
    ProcessGauge,
    ProcessGaugeCollector,
    assert_no_drift,
)
from ai.backend.testutils.dataplane.collectors.host import (
    IptablesRuleCollector,
    MountCollector,
    NeighbourCollector,
    NetworkLinkCollector,
    ScratchDirCollector,
    StateFileCollector,
)
from ai.backend.testutils.dataplane.guard import LeakGuard
from ai.backend.testutils.dataplane.nodes import (
    CommandFailed,
    CommandResult,
    Node,
    SshNode,
    parse_node_specs,
)


class FakeNode:
    """Replays canned output for exact argv matches, and fails loudly on anything else.

    An unmatched command raises rather than returning empty output: a collector that quietly asked
    the wrong question would otherwise pass its own test.
    """

    _name: str
    _responses: dict[tuple[str, ...], str]
    calls: list[tuple[str, ...]]

    def __init__(self, name: str, responses: dict[tuple[str, ...], str]) -> None:
        self._name = name
        self._responses = responses
        self.calls = []

    @property
    def name(self) -> str:
        return self._name

    async def run(self, argv: list[str], *, check: bool = True) -> CommandResult:
        key = tuple(argv)
        self.calls.append(key)
        if key not in self._responses:
            raise CommandFailed(f"[{self._name}] unstubbed command: {argv}")
        return CommandResult(self._name, key, 0, self._responses[key], "")


# --- captured from a host running this branch -------------------------------------------------

IP_LINK_JSON = json.dumps([
    {"ifindex": 1, "ifname": "lo", "link_type": "loopback", "mtu": 65536, "operstate": "UNKNOWN"},
    {"ifindex": 2, "ifname": "enp4s0", "link_type": "ether", "mtu": 1500, "operstate": "UP"},
    {"ifindex": 4, "ifname": "docker0", "link_type": "ether", "mtu": 1500, "operstate": "DOWN"},
    {"ifindex": 31, "ifname": "baibr4098", "link_type": "ether", "mtu": 1450, "operstate": "UP"},
    {
        "ifindex": 30,
        "ifname": "baivx4098",
        "link_type": "ether",
        "mtu": 1450,
        "operstate": "UNKNOWN",
        "master": "baibr4098",
    },
    {"ifindex": 33, "ifname": "bailo4098", "link_type": "ether", "mtu": 1500, "operstate": "UP"},
    {
        "ifindex": 35,
        "ifname": "bai7a702208f38",
        "link_type": "ether",
        "mtu": 1450,
        "operstate": "UP",
        "master": "baibr4098",
    },
    # A veth on our bridge that the runner never got to rename — caught by its master.
    {
        "ifindex": 37,
        "ifname": "veth5cd2afe",
        "link_type": "ether",
        "mtu": 1500,
        "operstate": "UP",
        "master": "bailo4098",
    },
    # Docker's own veth, on Docker's bridge — must not be collected.
    {
        "ifindex": 39,
        "ifname": "vethd1f7ef2",
        "link_type": "ether",
        "mtu": 1500,
        "operstate": "UP",
        "master": "docker0",
    },
])

# Captured from `ip -details -json link show` on iproute2 6.1.0 with a vxlan device present: the
# fan-map is printed as raw text inside the JSON object. This is why the collector must not pass
# `-details`.
IP_LINK_DETAILS_BROKEN = (
    '[{"ifindex":30,"ifname":"baivx4098","mtu":1450,"linkinfo":{"info_kind":"vxlan",'
    '"info_data":{"id":4098fan-map 83.114.0.0/14615:128.38.35.57/6464 ,"link":"enp4s0"}}}]'
)
IPTABLES_FILTER = """\
# Generated by iptables-save v1.8.10 (nf_tables) on Wed Jul 22 11:18:23 2026
*filter
:INPUT ACCEPT [1234:567890]
:FORWARD DROP [0:0]
:CNI-FORWARD-a1b2c3 - [0:0]
-A FORWARD -i enp4s0 -o bailo4098 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i bailo4098 -o bailo4098 -j ACCEPT
-A FORWARD -i bailo4098 -o enp4s0 -j ACCEPT
-A FORWARD -o bailo4098 -j DROP
-A FORWARD -i baibr4098 -o baibr4098 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
COMMIT
"""

IPTABLES_NAT = """\
*nat
:POSTROUTING ACCEPT [3062607:185414194]
:CNI-95b9743ca5b72ed0449af657 - [0:0]
-A PREROUTING -d 127.0.0.1/32 -p tcp -m tcp --dport 30000 -m comment --comment "bai:807185dc-6fc6-4b74-a1c5-7333712a5de9" -j DNAT --to-destination 172.30.0.2:2200
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
COMMIT
"""

CTR_CONTAINERS = """\
CONTAINER                               IMAGE                                                 RUNTIME
257886a7-af2d-4049-99dd-503e1cc151f9    cr.backend.ai/stable/python:3.11-ubuntu24.04-amd64    io.containerd.runc.v2
807185dc-6fc6-4b74-a1c5-7333712a5de9    cr.backend.ai/stable/python:3.11-ubuntu24.04-amd64    io.containerd.runc.v2
"""

CTR_TASKS = """\
TASK                                    PID       STATUS
257886a7-af2d-4049-99dd-503e1cc151f9    813955    RUNNING
ba0d0ba1-4dc3-4fdc-903b-f1e807a04496    813956    RUNNING
"""

CTR_SNAPSHOTS = """\
KEY                                     PARENT                    KIND
257886a7-af2d-4049-99dd-503e1cc151f9    sha256:8138cce9d5726       Active
"""

CTR_LEASES = "ID CREATED AT LABELS\n"


def _containerd_responses(
    *,
    containers: str = CTR_CONTAINERS,
    tasks: str = CTR_TASKS,
    snapshots: str = CTR_SNAPSHOTS,
    leases: str = CTR_LEASES,
) -> dict[tuple[str, ...], str]:
    base = ("ctr", "-a", "/run/containerd/containerd.sock", "-n", "backend-ai")
    return {
        (*base, "containers", "list"): containers,
        (*base, "tasks", "list"): tasks,
        (*base, "snapshots", "list"): snapshots,
        (*base, "leases", "list"): leases,
    }


# --- link collector ---------------------------------------------------------------------------


class TestNetworkLinkCollector:
    async def test_collects_our_devices_and_ignores_the_hosts(self) -> None:
        node = FakeNode("n1", {("ip", "-json", "link", "show"): IP_LINK_JSON})
        found = await NetworkLinkCollector(node).collect()
        assert {r.ident for r in found} == {
            "baibr4098",
            "baivx4098",
            "bailo4098",
            "bai7a702208f38",
            "veth5cd2afe",
        }

    async def test_docker_veth_on_a_docker_bridge_is_not_ours(self) -> None:
        node = FakeNode("n1", {("ip", "-json", "link", "show"): IP_LINK_JSON})
        found = await NetworkLinkCollector(node).collect()
        assert "vethd1f7ef2" not in {r.ident for r in found}

    async def test_non_json_output_raises_rather_than_reading_as_clean(self) -> None:
        node = FakeNode(
            "n1",
            {("ip", "-json", "link", "show"): 'Option "-json" is unknown\n'},
        )
        with pytest.raises(CommandFailed, match="did not return JSON"):
            await NetworkLinkCollector(node).collect()

    async def test_details_is_never_requested(self) -> None:
        """`ip -details -json` is unparseable wherever a vxlan device exists — see the
        `IP_LINK_DETAILS_BROKEN` capture. Passing `-details` would make the collector raise on
        exactly the hosts this suite exists for."""
        node = FakeNode("n1", {("ip", "-json", "link", "show"): IP_LINK_JSON})
        await NetworkLinkCollector(node).collect()
        assert node.calls == [("ip", "-json", "link", "show")]

    async def test_the_iproute2_fanmap_output_would_be_rejected(self) -> None:
        node = FakeNode("n1", {("ip", "-json", "link", "show"): IP_LINK_DETAILS_BROKEN})
        with pytest.raises(CommandFailed, match="did not return JSON"):
            await NetworkLinkCollector(node).collect()

    async def test_state_change_alone_is_not_a_different_resource(self) -> None:
        """`detail` carries operstate, so a bridge going UP must not read as a new device."""
        down = Resource("link", "n1", "baibr4098", "bridge mtu=1450 state=DOWN")
        up = Resource("link", "n1", "baibr4098", "bridge mtu=1450 state=UP")
        assert down == up
        assert {down} - {up} == set()


# --- iptables collector -----------------------------------------------------------------------


class TestIptablesRuleCollector:
    def test_collects_our_rules_and_cni_chains_only(self) -> None:
        collector = IptablesRuleCollector(FakeNode("n1", {}))
        found = collector.parse("filter", IPTABLES_FILTER)
        idents = {r.ident for r in found}
        assert "filter chain CNI-FORWARD-a1b2c3" in idents
        assert "filter -A FORWARD -i baibr4098 -o baibr4098 -j ACCEPT" in idents
        assert "filter -A FORWARD -i docker0 -o docker0 -j ACCEPT" not in idents

    def test_builtin_chain_counters_are_not_collected(self) -> None:
        """`:FORWARD DROP [0:0]` moves on every packet; collecting it would make every diff dirty."""
        collector = IptablesRuleCollector(FakeNode("n1", {}))
        found = collector.parse("filter", IPTABLES_FILTER)
        assert not any("chain FORWARD" in r.ident for r in found)
        assert not any("chain INPUT" in r.ident for r in found)

    def test_published_port_rule_is_found_by_its_bai_comment(self) -> None:
        collector = IptablesRuleCollector(FakeNode("n1", {}))
        found = collector.parse("nat", IPTABLES_NAT)
        assert any("--dport 30000" in r.ident for r in found)
        assert not any("172.17.0.0/16" in r.ident for r in found)

    async def test_reads_every_configured_table(self) -> None:
        node = FakeNode(
            "n1",
            {
                ("iptables-save", "-t", "filter"): IPTABLES_FILTER,
                ("iptables-save", "-t", "nat"): IPTABLES_NAT,
            },
        )
        found = await IptablesRuleCollector(node).collect()
        assert {r.detail for r in found if r.detail} == {"filter", "nat"}


# --- state files, mounts, neighbours ------------------------------------------------------------


class TestStateFileCollector:
    async def test_content_is_part_of_identity(self) -> None:
        node = FakeNode("n1", {})
        collector = StateFileCollector(node, dirs=("/var/lib/backend.ai/net-local-subnet",))
        first = collector.parse("/var/lib/backend.ai/net-local-subnet/3\tsession-a\n")
        second = collector.parse("/var/lib/backend.ai/net-local-subnet/3\tsession-b\n")
        # Same path, different owner: block 3 changed hands, and that must not read as no change.
        assert first != second

    async def test_layout_marker_is_excluded(self) -> None:
        node = FakeNode(
            "n1",
            {
                (
                    "sh",
                    "-c",
                    "for d in /var/lib/backend.ai/net-local-subnet; do "
                    '[ -d "$d" ] || continue; '
                    'find "$d" -type f ! -name .layout | while read -r f; do '
                    'printf "%s\\t%s\\n" "$f" "$(tr -d "\\n" < "$f")"; '
                    "done; done",
                ): "/var/lib/backend.ai/net-local-subnet/3\tsession-a\n",
            },
        )
        collector = StateFileCollector(node, dirs=("/var/lib/backend.ai/net-local-subnet",))
        found = await collector.collect()
        assert {r.ident for r in found} == {"/var/lib/backend.ai/net-local-subnet/3=session-a"}


class TestMountCollector:
    async def test_only_scratch_mounts_are_collected(self) -> None:
        node = FakeNode(
            "n1",
            {
                ("findmnt", "-rno", "TARGET,FSTYPE"): (
                    "/ ext4\n"
                    "/var/lib/backend.ai/scratches/807185dc/tmp tmpfs\n"
                    "/var/lib/docker/overlay2/abc/merged overlay\n"
                ),
            },
        )
        found = await MountCollector(node, prefixes=("/var/lib/backend.ai/scratches",)).collect()
        assert {r.ident for r in found} == {"/var/lib/backend.ai/scratches/807185dc/tmp"}


class TestNeighbourCollector:
    def test_fdb_entries_on_our_bridges_only(self) -> None:
        collector = NeighbourCollector(FakeNode("n1", {}))
        raw = (
            "02:42:0a:80:00:02 dev baivx4098 dst 192.168.0.20 self permanent\n"
            "00:00:00:00:00:00 dev baivx4098 dst 192.168.0.20 self permanent\n"
            "33:33:00:00:00:01 dev docker0 self permanent\n"
        )
        found = collector.parse_fdb(raw)
        assert len(found) == 2
        assert all("baivx4098" in r.ident for r in found)

    def test_arp_entries_carry_the_lladdr_as_detail(self) -> None:
        collector = NeighbourCollector(FakeNode("n1", {}))
        found = collector.parse_neigh(
            "10.128.0.2 dev baibr4098 lladdr 02:42:0a:80:00:02 PERMANENT\n"
        )
        assert [r.detail for r in found] == ["02:42:0a:80:00:02"]


# --- containerd collector ---------------------------------------------------------------------


class TestContainerdObjectCollector:
    async def test_containers_tasks_and_snapshots_are_distinct_resources(self) -> None:
        node = FakeNode("n1", _containerd_responses())
        found = await ContainerdObjectCollector(node).collect()
        idents = {r.ident for r in found}
        # 257886a7 has all three; a report must be able to say which of them survived.
        assert "container 257886a7-af2d-4049-99dd-503e1cc151f9" in idents
        assert "task 257886a7-af2d-4049-99dd-503e1cc151f9" in idents
        assert "snapshot 257886a7-af2d-4049-99dd-503e1cc151f9" in idents

    async def test_a_task_with_no_container_is_visible(self) -> None:
        """The asymmetry is surfaced, not interpreted.

        A task with no container record is either a shim that outlived its delete or a container
        created between the two listings — the captured output above is in fact the *second*, from
        a session that was mid-creation. Only `LeakGuard`, which requires the picture to repeat,
        can tell them apart; this collector's job is to make the asymmetry visible at all.
        """
        node = FakeNode("n1", _containerd_responses())
        found = await ContainerdObjectCollector(node).collect()
        idents = {r.ident for r in found}
        assert "task ba0d0ba1-4dc3-4fdc-903b-f1e807a04496" in idents
        assert "container ba0d0ba1-4dc3-4fdc-903b-f1e807a04496" not in idents

    async def test_headers_are_dropped(self) -> None:
        node = FakeNode("n1", _containerd_responses())
        found = await ContainerdObjectCollector(node).collect()
        assert not any(r.ident.endswith(("CONTAINER", "TASK", "KEY", "ID")) for r in found)

    async def test_empty_listings_yield_nothing(self) -> None:
        node = FakeNode(
            "n1",
            _containerd_responses(
                containers="CONTAINER IMAGE RUNTIME\n",
                tasks="TASK PID STATUS\n",
                snapshots="KEY PARENT KIND\n",
            ),
        )
        assert await ContainerdObjectCollector(node).collect() == set()

    async def test_task_pid_is_not_part_of_identity(self) -> None:
        collector = ContainerdObjectCollector(FakeNode("n1", {}))
        before = collector.parse_tasks("TASK PID STATUS\nabc  100  RUNNING\n")
        after = collector.parse_tasks("TASK PID STATUS\nabc  200  RUNNING\n")
        assert before == after


class TestScratchDirCollector:
    SCRATCH_ROOT = "/srv/scratches"
    PROBE = (
        "sh",
        "-c",
        f'for d in {SCRATCH_ROOT}; do if [ -d "$d" ]; then printf "%s\\n" "$d"; fi; done',
    )
    LIST = (
        "sh",
        "-c",
        f'for d in {SCRATCH_ROOT}; do find "$d" -mindepth 1 -maxdepth 1 -type d; done',
    )

    def _node(self, *, root_exists: bool, listing: str) -> FakeNode:
        return FakeNode(
            "n1",
            {
                self.PROBE: f"{self.SCRATCH_ROOT}\n" if root_exists else "",
                self.LIST: listing,
            },
        )

    async def _collect(self, node: FakeNode, live: set[str]) -> set[Resource]:
        async def live_ids() -> set[str]:
            return live

        return await ScratchDirCollector(
            node, roots=(self.SCRATCH_ROOT,), live_ids=live_ids
        ).collect()

    async def test_a_scratch_whose_kernel_is_gone_is_reported(self) -> None:
        node = self._node(
            root_exists=True,
            listing=f"{self.SCRATCH_ROOT}/live-kernel\n{self.SCRATCH_ROOT}/783ad6cc\n",
        )
        found = await self._collect(node, {"live-kernel"})
        assert {r.ident for r in found} == {f"{self.SCRATCH_ROOT}/783ad6cc"}

    async def test_a_scratch_with_a_live_container_record_is_not_a_leak(self) -> None:
        node = self._node(root_exists=True, listing=f"{self.SCRATCH_ROOT}/live-kernel\n")
        assert await self._collect(node, {"live-kernel"}) == set()

    async def test_a_missing_root_raises_instead_of_reporting_clean(self) -> None:
        """A scratch-root that does not exist means the harness was pointed at the wrong
        directory. Returning an empty set would certify every host as clean."""
        node = self._node(root_exists=False, listing="")
        with pytest.raises(CommandFailed, match="none of the configured scratch roots exist"):
            await self._collect(node, set())


class TestKernelIdProviders:
    async def test_containerd_kernel_ids_come_from_container_records(self) -> None:
        """Record, not task: an exited kernel still owns its scratch until the record is gone."""
        node = FakeNode("n1", _containerd_responses())
        assert await ContainerdObjectCollector(node).kernel_ids() == {
            "257886a7-af2d-4049-99dd-503e1cc151f9",
            "807185dc-6fc6-4b74-a1c5-7333712a5de9",
        }

    async def test_docker_kernel_ids_are_the_last_dotted_field(self) -> None:
        node = FakeNode("n1", {("docker", "ps", "-a", "--format", "{{json .}}"): DOCKER_PS})
        assert await DockerKernelContainerCollector(node).kernel_ids() == {
            "af8cde4a-72d0-46e0-b7d3-b9543e17d7ec"
        }


# --- docker collectors ------------------------------------------------------------------------

# `docker network ls --format '{{json .}}'` / `docker ps -a --format '{{json .}}'`, captured live.
DOCKER_NETWORKS = "\n".join([
    json.dumps({
        "ID": "ca2f4cec823d",
        "Name": "backendai_half",
        "Driver": "bridge",
        "Labels": "com.docker.compose.project=backendai",
    }),
    json.dumps({"ID": "0a4394bea101", "Name": "docker_gwbridge", "Driver": "bridge", "Labels": ""}),
    json.dumps({"ID": "w7890l4900sl", "Name": "ingress", "Driver": "overlay", "Labels": ""}),
    json.dumps({
        "ID": "aabbccddeeff",
        "Name": "bai-multinode-1234-nw",
        "Driver": "overlay",
        "Labels": "ai.backend.cluster-network=1",
    }),
])

DOCKER_PS = "\n".join([
    json.dumps({
        "ID": "31b7f52274bf",
        "Names": "backendai-socket-relay.i-testing-Zp_0DPCmofM",
        "State": "running",
    }),
    json.dumps({
        "ID": "623b1344f640",
        "Names": "backendai-backendai-half-grafana-1",
        "State": "running",
    }),
    json.dumps({
        "ID": "0ed9434f1c50",
        "Names": "kernel.python.af8cde4a-72d0-46e0-b7d3-b9543e17d7ec",
        "State": "exited",
    }),
])


class TestDockerNetworkCollector:
    def test_only_cluster_networks_are_collected(self) -> None:
        found = DockerNetworkCollector(FakeNode("n1", {})).parse(DOCKER_NETWORKS)
        assert {r.ident for r in found} == {"bai-multinode-1234-nw"}

    def test_swarm_ingress_is_not_a_leak(self) -> None:
        """`ingress` is swarm's permanent network; reporting it would fail on every swarm host."""
        found = DockerNetworkCollector(FakeNode("n1", {})).parse(DOCKER_NETWORKS)
        assert "ingress" not in {r.ident for r in found}

    def test_non_json_output_raises(self) -> None:
        with pytest.raises(CommandFailed, match="non-JSON"):
            DockerNetworkCollector(FakeNode("n1", {})).parse("Cannot connect to the daemon\n")


class TestDockerKernelContainerCollector:
    def test_only_kernel_containers_are_collected(self) -> None:
        found = DockerKernelContainerCollector(FakeNode("n1", {})).parse(DOCKER_PS)
        assert {r.ident for r in found} == {"kernel.python.af8cde4a-72d0-46e0-b7d3-b9543e17d7ec"}

    def test_state_is_detail_not_identity(self) -> None:
        collector = DockerKernelContainerCollector(FakeNode("n1", {}))
        running = collector.parse(json.dumps({"Names": "kernel.python.x", "State": "running"}))
        exited = collector.parse(json.dumps({"Names": "kernel.python.x", "State": "exited"}))
        assert running == exited


class TestDockerSandboxCollector:
    NETNS_LISTING = "\n".join([
        "037aa310d6b6",
        "1-w7890l4900",
        "bcb1f37355b6",
        "default",
        "ingress_sbox",
        "deadbeef99",
    ])

    def test_a_sandbox_its_container_claims_is_not_a_leak(self) -> None:
        """The false alarm this collector exists to prevent: a healthy host has one sandbox per
        running container, and listing the directory alone flags every service as leaked."""
        collector = DockerSandboxCollector(FakeNode("n1", {}))
        found = collector.parse(
            self.NETNS_LISTING,
            "/var/run/docker/netns/037aa310d6b6 /var/run/docker/netns/bcb1f37355b6",
        )
        assert {r.ident for r in found} == {"/var/run/docker/netns/deadbeef99"}

    def test_host_and_swarm_sandboxes_are_never_reported(self) -> None:
        collector = DockerSandboxCollector(FakeNode("n1", {}))
        found = collector.parse(self.NETNS_LISTING, "")
        idents = {r.ident for r in found}
        assert not any(name in i for i in idents for name in ("default", "ingress_sbox"))

    def test_an_overlay_networks_own_sandbox_is_left_to_the_network_collector(self) -> None:
        """`1-<netid>` belongs to a network, not a container. Reporting it would double-count a
        leaked cluster network and would flag swarm's permanent `ingress` on every host."""
        collector = DockerSandboxCollector(FakeNode("n1", {}))
        found = collector.parse(self.NETNS_LISTING, "")
        assert not any("1-w7890l4900" in r.ident for r in found)


# --- etcd collector ---------------------------------------------------------------------------


class FakeEtcd:
    _trees: dict[str, dict[str, object]]

    def __init__(self, trees: dict[str, dict[str, object]]) -> None:
        self._trees = trees

    async def get_prefix(self, key_prefix: str) -> dict[str, object]:
        return self._trees.get(key_prefix, {})


class TestEtcdNetworkKeyCollector:
    def test_flatten_rebuilds_absolute_keys(self) -> None:
        tree = {
            "sess-1": {
                "meta": '{"vni": 4098}',
                "members": {"i-node1": '{"vtep_ip": "192.168.0.20"}'},
                "ipam": {"10.128.0.2": "kernel-a"},
            }
        }
        flat = flatten("network/session/", tree)
        assert flat == {
            "network/session/sess-1/meta": '{"vni": 4098}',
            "network/session/sess-1/members/i-node1": '{"vtep_ip": "192.168.0.20"}',
            "network/session/sess-1/ipam/10.128.0.2": "kernel-a",
        }

    async def test_value_change_is_a_different_resource(self) -> None:
        """A member record rewritten to a null VTEP is the destructive case; identity by key
        alone would report it as unchanged."""
        good = FakeEtcd({
            "network/session/": {"s": {"members": {"i-1": '{"vtep_ip": "192.168.0.20"}'}}},
            "network/agent/": {},
        })
        bad = FakeEtcd({
            "network/session/": {"s": {"members": {"i-1": '{"vtep_ip": null}'}}},
            "network/agent/": {},
        })
        assert (
            await EtcdNetworkKeyCollector(good).collect()
            != await EtcdNetworkKeyCollector(bad).collect()
        )

    async def test_etcd_resources_are_cluster_scoped(self) -> None:
        collector = EtcdNetworkKeyCollector(
            FakeEtcd({"network/session/": {"s": {"meta": "{}"}}, "network/agent/": {}})
        )
        assert {r.node for r in await collector.collect()} == {""}


# --- the guard --------------------------------------------------------------------------------


class ScriptedCollector:
    """Returns a different snapshot on each call, so a settle loop can be driven deterministically."""

    _snapshots: list[set[Resource]]
    calls: int

    def __init__(self, snapshots: list[set[Resource]]) -> None:
        self._snapshots = snapshots
        self.calls = 0

    @property
    def kind(self) -> str:
        return "scripted"

    async def collect(self) -> set[Resource]:
        index = min(self.calls, len(self._snapshots) - 1)
        self.calls += 1
        return set(self._snapshots[index])


def _r(ident: str) -> Resource:
    return Resource("scripted", "n1", ident)


class TestLeakGuard:
    async def test_preexisting_resources_are_not_leaks(self) -> None:
        collector = ScriptedCollector([{_r("baibr1")}, {_r("baibr1")}])
        guard = LeakGuard([collector])
        await guard.baseline(max_wait=10, interval=0)
        report = await guard.settle(max_wait=0, interval=0)
        assert report.clean

    async def test_baseline_waits_for_two_agreeing_samples(self) -> None:
        """A single sample can catch a half-created object — a containerd task whose container
        record did not exist yet when `containers list` ran. Baselining that phantom makes the
        test report COLLATERAL when it resolves."""
        collector = ScriptedCollector([
            {_r("baibr1"), _r("phantom")},  # mid-creation skew
            {_r("baibr1")},
            {_r("baibr1")},
        ])
        guard = LeakGuard([collector])
        assert await guard.baseline(max_wait=10, interval=0) == {_r("baibr1")}
        assert guard.quiesced

    async def test_a_resolving_phantom_is_not_reported_as_collateral(self) -> None:
        collector = ScriptedCollector([
            {_r("baibr1"), _r("phantom")},
            {_r("baibr1")},
            {_r("baibr1")},
        ])
        guard = LeakGuard([collector])
        await guard.baseline(max_wait=10, interval=0)
        report = await guard.settle(max_wait=0, interval=0)
        assert report.clean

    async def test_a_never_quiescent_host_falls_back_to_what_was_seen_twice(self) -> None:
        collector = ScriptedCollector([
            {_r("stable"), _r("churn-a")},
            {_r("stable"), _r("churn-b")},
        ])
        guard = LeakGuard([collector])
        # The scripted collector repeats its last snapshot, so make the deadline immediate.
        assert await guard.baseline(max_wait=0, interval=0) == {_r("stable")}
        assert not guard.quiesced

    async def test_a_survivor_is_reported(self) -> None:
        collector = ScriptedCollector([
            {_r("baibr1")},
            {_r("baibr1")},
            {_r("baibr1"), _r("baibr2")},
        ])
        guard = LeakGuard([collector])
        await guard.baseline(max_wait=10, interval=0)
        report = await guard.settle(max_wait=0, interval=0)
        assert [r.ident for r in report.leaked] == ["baibr2"]
        assert "LEAKED" in report.format()

    async def test_settle_waits_for_asynchronous_teardown(self) -> None:
        collector = ScriptedCollector([
            {_r("baibr1")},  # baseline, sample 1
            {_r("baibr1")},  # baseline, sample 2 — agrees, so it is trusted
            {_r("baibr1"), _r("baibr2")},  # still tearing down
            {_r("baibr1")},  # settled
        ])
        guard = LeakGuard([collector])
        await guard.baseline(max_wait=10, interval=0)
        report = await guard.settle(max_wait=10, interval=0)
        assert report.clean
        assert report.polls == 2

    async def test_timeout_reports_what_survived(self) -> None:
        collector = ScriptedCollector([
            {_r("baibr1")},
            {_r("baibr1")},
            {_r("baibr1"), _r("baibr2")},
        ])
        guard = LeakGuard([collector])
        await guard.baseline(max_wait=10, interval=0)
        report = await guard.settle(max_wait=0.05, interval=0.01)
        assert not report.clean
        assert report.polls > 1

    async def test_destroying_someone_elses_resource_is_reported_as_collateral(self) -> None:
        """The `bailo{n}` name-space collision: a teardown deleting another session's bridge."""
        collector = ScriptedCollector([
            {_r("bailo1"), _r("bailo2")},
            {_r("bailo1"), _r("bailo2")},
            {_r("bailo1")},
        ])
        guard = LeakGuard([collector])
        await guard.baseline(max_wait=10, interval=0)
        report = await guard.settle(max_wait=0, interval=0)
        assert not report.clean
        assert [r.ident for r in report.collateral] == ["bailo2"]
        assert "COLLATERAL" in report.format()

    async def test_a_failing_collector_fails_the_guard(self) -> None:
        class BrokenCollector:
            kind = "broken"

            async def collect(self) -> set[Resource]:
                raise CommandFailed("iptables-save: Permission denied")

        guard = LeakGuard([BrokenCollector()])
        with pytest.raises(CommandFailed):
            await guard.baseline()

    async def test_diff_without_a_baseline_is_an_error(self) -> None:
        guard = LeakGuard([ScriptedCollector([set()])])
        with pytest.raises(RuntimeError, match="baseline"):
            await guard.settle(max_wait=0, interval=0)

    async def test_assert_clean_raises_with_the_report_attached(self) -> None:
        collector = ScriptedCollector([set(), set(), {_r("baibr2")}])
        guard = LeakGuard([collector])
        await guard.baseline(max_wait=10, interval=0)
        with pytest.raises(AssertionError, match="baibr2"):
            await guard.assert_clean(max_wait=0, interval=0)


# --- gauges -----------------------------------------------------------------------------------


class TestProcessGauges:
    def test_parses_one_line_per_process(self) -> None:
        collector = ProcessGaugeCollector(FakeNode("n1", {}), pattern="ai.backend.agent")
        gauges = collector.parse("4242\tpython -m ai.backend.agent\t137\t9\t512000\n")
        assert gauges[4242].fds == 137
        assert gauges[4242].rss_kib == 512000

    def test_our_own_pgrep_shell_is_not_a_gauge(self) -> None:
        """`pgrep -f <pattern>` also matches the shell running it, and that PID changes on every
        poll — enough churn to hide real drift behind a set that never repeats."""
        collector = ProcessGaugeCollector(FakeNode("n1", {}), pattern="ai.backend.agent")
        gauges = collector.parse(
            "4242\tpython -m ai.backend.agent.server\t137\t9\t512000\n"
            "9001\tsh -c pgrep -f 'ai.backend.agent' | while read -r p\t3\t1\t1520\n"
            "9002\tsudo -n sh -c pgrep -f 'ai.backend.agent'\t8\t1\t5848\n"
        )
        assert sorted(gauges) == [4242]

    def test_a_row_split_across_lines_is_rejected(self) -> None:
        """A command line containing a newline used to spill one row onto two. Failing loudly
        beats silently dropping the process whose fd count is the thing being watched."""
        collector = ProcessGaugeCollector(FakeNode("n1", {}), pattern="ai.backend.agent")
        with pytest.raises(CommandFailed, match="unexpected gauge line"):
            collector.parse("4242\t/usr/bin/zsh -c source /home/x/snapshot\n")

    def test_fd_growth_beyond_the_allowance_fails(self) -> None:
        before = {1: ProcessGauge("n1", 1, "agent", 100, 8, 1000)}
        after = {1: ProcessGauge("n1", 1, "agent", 400, 8, 1000)}
        with pytest.raises(AssertionError, match="fds 100 -> 400"):
            assert_no_drift(before, after)

    def test_a_restarted_process_is_not_compared(self) -> None:
        before = {1: ProcessGauge("n1", 1, "agent", 100, 8, 1000)}
        after = {2: ProcessGauge("n1", 2, "agent", 9999, 99, 9_000_000)}
        assert_no_drift(before, after)


# --- node plumbing ----------------------------------------------------------------------------


class TestNodeSpecs:
    def test_local_and_ssh_specs(self) -> None:
        parsed = parse_node_specs("local, ssh://root@10.0.0.2")
        assert [n.name for n in parsed] == ["local", "node1"]

    def test_explicit_names(self) -> None:
        parsed = parse_node_specs("a=local,b=ssh://root@10.0.0.2")
        assert [n.name for n in parsed] == ["a", "b"]

    def test_unknown_scheme_is_rejected(self) -> None:
        with pytest.raises(ValueError, match="unrecognized node spec"):
            parse_node_specs("telnet://10.0.0.2")

    def test_ssh_argv_is_quoted_once(self) -> None:
        node = SshNode("root@10.0.0.2")
        wire = node.wire_argv(["sh", "-c", 'printf "%s\\n" "$f"'])
        assert wire[:2] == ["ssh", "-o"]
        assert wire[-2] == "--"
        # The remote shell must receive the script as a single argument.
        assert wire[-1].count("printf") == 1

    def test_node_protocol_is_satisfied(self) -> None:
        assert isinstance(FakeNode("n1", {}), Node)
        assert isinstance(SshNode("root@10.0.0.2"), Node)
